<a href="https://colab.research.google.com/github/raghad-cs/Esnad/blob/upscaling/alarb_pipeline_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Esnad — ALARB Semantic Search Pipeline

This notebook builds the ALARB component of **Esnad**, an Arabic semantic search engine for Saudi commercial judgments.

**MVP scope:** 6000 judgments from `THIQAH-RD/ALARB`.

**Pipeline:** judgment text → BGE-M3 embeddings → FAISS index → top similar judgments.

The system retrieves references for research and learning. It does not predict case outcomes or provide legal advice.

## 1. Environment Setup

Google Colab with a GPU runtime is recommended. Checkpoints are saved to Google Drive so an interrupted session can resume without regenerating completed embeddings.

In [1]:
!pip install -q datasets sentence-transformers faiss-cpu pandas pyarrow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 61.5 MB/s eta 0:00:00

In [2]:
import json
import re
import time
from pathlib import Path

import faiss
import numpy as np
import pandas as pd
import torch
from datasets import load_dataset
from sentence_transformers import SentenceTransformer

DATASET_NAME = "THIQAH-RD/ALARB"
DATASET_SPLIT = "train"
SAMPLE_SIZE = 6000

MODEL_NAME = "BAAI/bge-m3"
MAX_SEQUENCE_LENGTH = 1024
EMBEDDING_DIMENSION = 1024
EMBEDDING_BATCH_SIZE = 8
CHECKPOINT_SIZE = 50
TOP_K = 5

In [3]:
try:
    from google.colab import drive

    drive.mount("/content/drive")
    project_dir = Path("/content/drive/MyDrive/Esnad")
except ImportError:
    project_dir = Path.cwd() / "Esnad"

checkpoint_dir = project_dir / "alarb_6000_checkpoints"
artifact_dir = project_dir / "final_artifacts"

checkpoint_dir.mkdir(parents=True, exist_ok=True)
artifact_dir.mkdir(parents=True, exist_ok=True)

print("Project directory:", project_dir)

Mounted at /content/drive
Project directory: /content/drive/MyDrive/Esnad

## 2. Load and Prepare 200 Judgments

The retrieval representation contains **case facts and court reasoning**. Applicable laws and the final verdict remain in the metadata and are displayed with each result.

In [4]:
dataset = load_dataset(DATASET_NAME)
df = dataset[DATASET_SPLIT].select(range(SAMPLE_SIZE)).to_pandas()

print("Available columns:", df.columns.tolist())
print("Selected cases:", len(df))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/1.83k [00:00<?, ?B/s]

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 19.1MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 2.15MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/12012 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1329 [00:00<?, ? examples/s]

Available columns: ['case_facts', 'court_reasoning', 'applicable_laws', 'verdict']
Selected cases: 6000

In [5]:
def clean_text(value):
    if isinstance(value, (list, tuple, np.ndarray)):
        value = " ".join(
            str(item) for item in value
            if item is not None
        )
    elif value is None or (
        isinstance(value, float) and pd.isna(value)
    ):
        return ""
    else:
        value = str(value)

    value = re.sub(
        r"[​-‏‪-‮⁠-]",
        " ",
        value,
    )
    return re.sub(r"\s+", " ", value).strip()


text_columns = [
    "case_facts",
    "court_reasoning",
    "applicable_laws",
    "verdict",
]

for column in text_columns:
    df[column] = df[column].apply(clean_text)

df["case_id"] = range(1, len(df) + 1)
df["retrieval_text"] = (
    "وقائع القضية: " + df["case_facts"]
    + "\nتسبيب المحكمة: " + df["court_reasoning"]
)

empty_fields = df[text_columns].apply(
    lambda column: column.str.strip().eq("").sum()
)
duplicate_count = df.duplicated(
    subset=["case_facts", "court_reasoning", "verdict"]
).sum()

print("Prepared cases:", len(df))
print("Unique case IDs:", df["case_id"].nunique())
print("Duplicate cases:", duplicate_count)
print("\nEmpty fields:")
print(empty_fields)

display(
    df[
        [
            "case_id",
            "case_facts",
            "court_reasoning",
            "applicable_laws",
            "verdict",
        ]
    ].head(2)
)

Prepared cases: 6000
Unique case IDs: 6000
Duplicate cases: 0

Empty fields:
case_facts           0
court_reasoning      0
applicable_laws    441
verdict              0
dtype: int64

,case_id,case_facts,court_reasoning,applicable_laws,verdict
0,1,1 بتاريخ 1443/09/06 اتفق أطراف الدعوى على أن ت...,1 بناءً على الدعوى والإجابة، طلب وكيل المدعية ...,نظام المحاكم التجارية:22: ١.تحيل الإدارة المخت...,إثبات الصلح بين الطرفين وإلزام المدعى عليها بس...
1,2,1. سبق أن تم رفع دعوى من مصنع تكنولوجيا الحديد...,1. اعتبرت الدائرة أن اختصاص النظر في النزاع ين...,نظام المحاكم التجارية:16: تختص المحكمة بالنظر ...,"إلزام المدعى عليها بدفع مبلغ 72,000 ريال للمدع..."

## 3. Load BGE-M3 and Check Token Lengths

The same model configuration must be used for both judgment embeddings and user-query embeddings.

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"

model = SentenceTransformer(
    MODEL_NAME,
    device=device,
)
model.max_seq_length = MAX_SEQUENCE_LENGTH

if device == "cuda":
    model.half()

tokenizer = model.tokenizer
model_dimension = model.get_embedding_dimension()

assert model_dimension == EMBEDDING_DIMENSION

print("Device:", device)
print("Model:", MODEL_NAME)
print("Maximum sequence length:", model.max_seq_length)
print("Embedding dimension:", model_dimension)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.27GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Device: cuda
Model: BAAI/bge-m3
Maximum sequence length: 1024
Embedding dimension: 1024

In [9]:

def count_tokens(text):
    encoded_text = tokenizer(
        text,
        add_special_tokens=True,
        truncation=False,
        verbose=False,
    )
    return len(encoded_text["input_ids"])


df["token_count"] = df["retrieval_text"].apply(count_tokens)

cases_over_limit = int(
    (df["token_count"] > MAX_SEQUENCE_LENGTH).sum()
)

print("Token count statistics:")
display(df["token_count"].describe().to_frame())
print("Cases over the sequence limit:", cases_over_limit)
print("Maximum token count:", df["token_count"].max())

if cases_over_limit > 0:
    display(
        df.loc[
            df["token_count"] > MAX_SEQUENCE_LENGTH,
            ["case_id", "token_count"],
        ]
    )

Token count statistics:

       token_count
count  6000.000000
mean    576.056833
std     128.928829
min     170.000000
25%     488.000000
50%     571.000000
75%     662.000000
max    1102.000000

Cases over the sequence limit: 2
Maximum token count: 1102

      case_id  token_count
3405     3406         1102
5814     5815         1030

In [10]:

df["embedding_text"] = df["retrieval_text"].apply(
    lambda text: tokenizer.decode(
        tokenizer(
            text,
            add_special_tokens=False,
            truncation=True,
            max_length=MAX_SEQUENCE_LENGTH - 2,
        )["input_ids"],
        skip_special_tokens=True,
    )
)

embedding_token_counts = df["embedding_text"].apply(
    lambda text: len(
        tokenizer(
            text,
            add_special_tokens=True,
            truncation=False,
            verbose=False,
        )["input_ids"]
    )
)

assert embedding_token_counts.max() <= MAX_SEQUENCE_LENGTH

## 4. Generate Embeddings with Checkpoints

The 200 cases are processed in four groups of 50. Existing checkpoint files are reused automatically. Every vector is normalized for cosine-style similarity with `IndexFlatIP`.

In [11]:
retrieval_texts = df["retrieval_text"].tolist()
embedding_chunks = []
generation_start_time = time.perf_counter()

for start_position in range(
    0,
    len(retrieval_texts),
    CHECKPOINT_SIZE,
):
    end_position = min(
        start_position + CHECKPOINT_SIZE,
        len(retrieval_texts),
    )

    first_case_id = start_position + 1
    last_case_id = end_position
    checkpoint_path = checkpoint_dir / (
        f"embeddings_cases_{first_case_id:03d}_"
        f"{last_case_id:03d}.npy"
    )

    if checkpoint_path.exists():
        print(
            f"Loading checkpoint: cases "
            f"{first_case_id}-{last_case_id}"
        )
        chunk_embeddings = np.load(checkpoint_path)
    else:
        print(
            f"Generating embeddings: cases "
            f"{first_case_id}-{last_case_id}"
        )
        chunk_embeddings = model.encode(
            retrieval_texts[start_position:end_position],
            batch_size=EMBEDDING_BATCH_SIZE,
            show_progress_bar=True,
            convert_to_numpy=True,
            normalize_embeddings=True,
        ).astype("float32")
        np.save(checkpoint_path, chunk_embeddings)

    expected_shape = (
        end_position - start_position,
        EMBEDDING_DIMENSION,
    )
    assert chunk_embeddings.shape == expected_shape
    embedding_chunks.append(
        chunk_embeddings.astype("float32")
    )

embeddings = np.vstack(embedding_chunks).astype("float32")
faiss.normalize_L2(embeddings)

complete_embeddings_path = (
    checkpoint_dir / "alarb_embeddings_200.npy"
)
np.save(complete_embeddings_path, embeddings)

generation_elapsed_time = (
    time.perf_counter() - generation_start_time
)

print("Embedding generation completed.")
print("Embeddings shape:", embeddings.shape)
print("Data type:", embeddings.dtype)
print("First vector norm:", np.linalg.norm(embeddings[0]))
print(
    f"Elapsed time: {generation_elapsed_time:.2f} seconds"
)

Generating embeddings: cases 1-50

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 51-100

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 101-150

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 151-200

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 201-250

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 251-300

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 301-350

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 351-400

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 401-450

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 451-500

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 501-550

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 551-600

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 601-650

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 651-700

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 701-750

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 751-800

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 801-850

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 851-900

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 901-950

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 951-1000

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1001-1050

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1051-1100

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1101-1150

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1151-1200

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1201-1250

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1251-1300

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1301-1350

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1351-1400

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1401-1450

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1451-1500

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1501-1550

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1551-1600

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1601-1650

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1651-1700

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1701-1750

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1751-1800

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1801-1850

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1851-1900

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1901-1950

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 1951-2000

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2001-2050

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2051-2100

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2101-2150

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2151-2200

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2201-2250

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2251-2300

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2301-2350

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2351-2400

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2401-2450

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2451-2500

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2501-2550

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2551-2600

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2601-2650

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2651-2700

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2701-2750

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2751-2800

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2801-2850

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2851-2900

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2901-2950

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 2951-3000

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3001-3050

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3051-3100

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3101-3150

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3151-3200

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3201-3250

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3251-3300

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3301-3350

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3351-3400

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3401-3450

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3451-3500

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3501-3550

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3551-3600

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3601-3650

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3651-3700

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3701-3750

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3751-3800

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3801-3850

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3851-3900

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3901-3950

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 3951-4000

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4001-4050

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4051-4100

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4101-4150

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4151-4200

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4201-4250

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4251-4300

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4301-4350

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4351-4400

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4401-4450

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4451-4500

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4501-4550

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4551-4600

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4601-4650

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4651-4700

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4701-4750

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4751-4800

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4801-4850

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4851-4900

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4901-4950

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 4951-5000

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5001-5050

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5051-5100

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5101-5150

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5151-5200

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5201-5250

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5251-5300

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5301-5350

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5351-5400

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5401-5450

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5451-5500

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5501-5550

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5551-5600

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5601-5650

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5651-5700

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5701-5750

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5751-5800

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5801-5850

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5851-5900

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5901-5950

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Generating embeddings: cases 5951-6000

Batches:   0%|          | 0/7 [00:00<?, ?it/s]

Embedding generation completed.
Embeddings shape: (6000, 1024)
Data type: float32
First vector norm: 1.0
Elapsed time: 195.47 seconds

## 5. Build and Save the FAISS Index

`IndexFlatIP` performs exact inner-product search. Because all vectors are normalized, the score behaves like cosine similarity.

In [12]:
index = faiss.IndexFlatIP(EMBEDDING_DIMENSION)
index.add(embeddings)

index_path = artifact_dir / "alarb_judgments_6000.index"
metadata_path = (
    artifact_dir / "alarb_judgments_metadata_6000.parquet"
)
config_path = artifact_dir / "alarb_search_config.json"

faiss.write_index(index, str(index_path))
df.to_parquet(metadata_path, index=False)

search_config = {
    "dataset_name": DATASET_NAME,
    "dataset_split": DATASET_SPLIT,
    "number_of_cases": SAMPLE_SIZE,
    "model_name": MODEL_NAME,
    "max_sequence_length": MAX_SEQUENCE_LENGTH,
    "embedding_dimension": EMBEDDING_DIMENSION,
    "normalize_embeddings": True,
    "faiss_index_type": "IndexFlatIP",
    "retrieval_fields": [
        "case_facts",
        "court_reasoning",
    ],
}

with config_path.open("w", encoding="utf-8") as config_file:
    json.dump(
        search_config,
        config_file,
        ensure_ascii=False,
        indent=4,
    )

loaded_index = faiss.read_index(str(index_path))
loaded_metadata = pd.read_parquet(metadata_path)

assert loaded_index.ntotal == len(loaded_metadata)
assert loaded_index.d == EMBEDDING_DIMENSION
assert loaded_metadata["case_id"].nunique() == SAMPLE_SIZE

print("Final artifacts saved and verified.")
print("FAISS index:", index_path)
print("Metadata:", metadata_path)
print("Configuration:", config_path)
print("Indexed cases:", loaded_index.ntotal)
print("Metadata rows:", len(loaded_metadata))

Final artifacts saved and verified.
FAISS index: /content/drive/MyDrive/Esnad/final_artifacts/alarb_judgments_6000.index
Metadata: /content/drive/MyDrive/Esnad/final_artifacts/alarb_judgments_metadata_6000.parquet
Configuration: /content/drive/MyDrive/Esnad/final_artifacts/alarb_search_config.json
Indexed cases: 6000
Metadata rows: 6000

## 6. Validate Index-to-Metadata Alignment

This test uses excerpts from three judgments stored in different checkpoints. Each excerpt must retrieve its original case as the top result.

In [13]:
validation_case_ids = [75, 125, 175]
validation_queries = []

for case_id in validation_case_ids:
    case_facts = loaded_metadata.loc[
        loaded_metadata["case_id"] == case_id,
        "case_facts",
    ].iloc[0]
    validation_queries.append(case_facts[:300])

validation_embeddings = model.encode(
    validation_queries,
    convert_to_numpy=True,
    normalize_embeddings=True,
).astype("float32")

validation_scores, validation_positions = loaded_index.search(
    validation_embeddings,
    k=1,
)

retrieved_case_ids = [
    int(loaded_metadata.iloc[position]["case_id"])
    for position in validation_positions[:, 0]
]

validation_results = pd.DataFrame({
    "expected_case_id": validation_case_ids,
    "retrieved_case_id": retrieved_case_ids,
    "similarity_score": validation_scores[:, 0],
})

assert retrieved_case_ids == validation_case_ids
display(validation_results)

   expected_case_id  retrieved_case_id  similarity_score
0                75                 75          0.849247
1               125                125          0.887049
2               175                175          0.825960

## 7. Semantic Search Function

The similarity score ranks semantic closeness within the indexed collection. It is not a legal confidence score, accuracy percentage, or prediction.

In [14]:
def semantic_search(
    query,
    model,
    index,
    metadata,
    top_k=5,
):
    query = query.strip()
    if not query:
        raise ValueError("The query must not be empty.")

    top_k = min(top_k, index.ntotal)

    embedding_start_time = time.perf_counter()
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True,
    ).astype("float32")
    embedding_time = time.perf_counter() - embedding_start_time

    search_start_time = time.perf_counter()
    scores, positions = index.search(query_embedding, top_k)
    search_time = time.perf_counter() - search_start_time

    results = metadata.iloc[positions[0]][
        [
            "case_id",
            "case_facts",
            "court_reasoning",
            "applicable_laws",
            "verdict",
        ]
    ].copy().reset_index(drop=True)

    results.insert(0, "rank", range(1, len(results) + 1))
    results.insert(2, "similarity_score", scores[0])
    results["facts_preview"] = (
        results["case_facts"].str[:180] + "..."
    )

    timings = {
        "query_embedding_seconds": embedding_time,
        "faiss_search_seconds": search_time,
        "total_seconds": embedding_time + search_time,
    }
    return results, timings

## 8. Final Natural-Language Search Test

In [15]:
user_query = (
    "شركة وفرت عمالة لشركة أخرى، لكن الشركة الثانية "
    "ما دفعت المستحقات، وبعدها اتفقوا على الصلح "
    "وجدولة المبلغ."
)

search_results, search_timings = semantic_search(
    query=user_query,
    model=model,
    index=loaded_index,
    metadata=loaded_metadata,
    top_k=TOP_K,
)

display(
    search_results[
        [
            "rank",
            "case_id",
            "similarity_score",
            "facts_preview",
            "applicable_laws",
            "verdict",
        ]
    ]
)

print(
    "Query embedding time: "
    f"{search_timings['query_embedding_seconds']:.4f} seconds"
)
print(
    "FAISS search time: "
    f"{search_timings['faiss_search_seconds']:.6f} seconds"
)
print(
    "Total search time: "
    f"{search_timings['total_seconds']:.4f} seconds"
)

,rank,case_id,similarity_score,facts_preview,applicable_laws,verdict
0,1,5533,0.677802,1. تعاقد المدعي مع المدعى عليها على تنفيذ مقاو...,,إثبات الصلح بين الطرفين وإلزامهما بالالتزام بم...
1,2,4194,0.640208,بتاريخ 8/5/1441هـ أبرم المدعي والمدعى عليها عق...,نظام المرافعات الشرعية:70: للخصوم أن يطلبوا من...,إثبات الصلح بين الطرفين وإلزام المدعى عليها بس...
2,3,1,0.632745,1 بتاريخ 1443/09/06 اتفق أطراف الدعوى على أن ت...,نظام المحاكم التجارية:22: ١.تحيل الإدارة المخت...,إثبات الصلح بين الطرفين وإلزام المدعى عليها بس...
3,4,5908,0.630760,اتفق المدعى عليها مع المدعي وأوكلت إليه القيام...,,حكمت المحكمة بإثبات الصلح وإلزام المدعى عليها ...
4,5,943,0.629453,1 تقدم المدعي بصحيفة دعوى إلى المحكمة التجارية...,اللائحة التنفيذية لنظام المحاكم التجارية:90: ت...,إثبات الصلح بين الطرفين وإلزامهما بالتقيد به ب...

Query embedding time: 0.0858 seconds
FAISS search time: 0.002233 seconds
Total search time: 0.0881 seconds

---

### MVP limitation

This prototype indexes a 200-case sample from ALARB. Results must be reviewed by a legal specialist, and each case retains its own facts and circumstances. The architecture can be expanded to the full dataset without changing the search method.

In [16]:

from pathlib import Path

for path in Path("/content").rglob("*"):
    if path.is_file() and (
        path.suffix in [".index", ".parquet", ".npy"]
        or "search_config" in path.name
    ):
        print(
            path,
            f"| {path.stat().st_size / (1024**2):.2f} MB"
        )

/content/drive/MyDrive/Esnad/final_artifacts/alarb_judgments_6000.index | 23.44 MB
/content/drive/MyDrive/Esnad/final_artifacts/alarb_judgments_metadata_6000.parquet | 26.76 MB
/content/drive/MyDrive/Esnad/final_artifacts/alarb_search_config.json | 0.00 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_001_050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_051_100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_101_150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_151_200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_201_250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_251_300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_301_350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_351_400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_401_450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_451_500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_501_550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_551_600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_601_650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_651_700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_701_750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_751_800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_801_850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_851_900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_901_950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_951_1000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1001_1050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1051_1100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1101_1150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1151_1200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1201_1250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1251_1300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1301_1350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1351_1400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1401_1450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1451_1500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1501_1550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1551_1600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1601_1650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1651_1700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1701_1750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1751_1800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1801_1850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1851_1900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1901_1950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_1951_2000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2001_2050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2051_2100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2101_2150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2151_2200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2201_2250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2251_2300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2301_2350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2351_2400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2401_2450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2451_2500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2501_2550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2551_2600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2601_2650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2651_2700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2701_2750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2751_2800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2801_2850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2851_2900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2901_2950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_2951_3000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3001_3050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3051_3100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3101_3150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3151_3200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3201_3250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3251_3300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3301_3350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3351_3400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3401_3450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3451_3500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3501_3550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3551_3600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3601_3650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3651_3700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3701_3750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3751_3800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3801_3850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3851_3900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3901_3950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_3951_4000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4001_4050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4051_4100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4101_4150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4151_4200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4201_4250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4251_4300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4301_4350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4351_4400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4401_4450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4451_4500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4501_4550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4551_4600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4601_4650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4651_4700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4701_4750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4751_4800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4801_4850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4851_4900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4901_4950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_4951_5000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5001_5050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5051_5100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5101_5150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5151_5200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5201_5250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5251_5300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5301_5350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5351_5400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5401_5450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5451_5500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5501_5550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5551_5600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5601_5650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5651_5700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5701_5750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5751_5800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5801_5850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5851_5900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5901_5950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/embeddings_cases_5951_6000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints (1)/alarb_embeddings_6000.npy | 23.44 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_001_050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_051_100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_101_150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_151_200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_201_250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_251_300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_301_350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_351_400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_401_450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_451_500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_501_550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_551_600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_601_650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_651_700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_701_750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_751_800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_801_850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_851_900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_901_950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_951_1000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1001_1050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1051_1100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1101_1150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1151_1200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1201_1250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1251_1300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1301_1350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1351_1400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1401_1450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1451_1500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1501_1550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1551_1600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1601_1650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1651_1700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1701_1750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1751_1800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1801_1850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1851_1900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1901_1950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_1951_2000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2001_2050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2051_2100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2101_2150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2151_2200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2201_2250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2251_2300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2301_2350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2351_2400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2401_2450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2451_2500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2501_2550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2551_2600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2601_2650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2651_2700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2701_2750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2751_2800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2801_2850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2851_2900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2901_2950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_2951_3000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3001_3050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3051_3100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3101_3150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3151_3200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3201_3250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3251_3300.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3301_3350.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3351_3400.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3401_3450.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3451_3500.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3501_3550.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3551_3600.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3601_3650.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3651_3700.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3701_3750.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3751_3800.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3801_3850.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3851_3900.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3901_3950.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_3951_4000.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_4001_4050.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_4051_4100.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_4101_4150.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_4151_4200.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_4201_4250.npy | 0.20 MB
/content/drive/MyDrive/Esnad/alarb_6000_checkpoints/embeddings_cases_4251_4300.npy | 0.20 MB

In [17]:
from pathlib import Path

for p in Path("/content/drive/MyDrive/Esnad/final_artifacts").iterdir():
    if p.is_file():
        print(p.name, round(p.stat().st_size / (1024**2), 2), "MB")

alarb_judgments_6000.index 23.44 MB
alarb_judgments_metadata_6000.parquet 26.76 MB
alarb_search_config.json 0.0 MB

In [18]:

from pathlib import Path
import subprocess
import shutil
import os

drive_root = Path("/content/drive/MyDrive/Esnad")
artifacts_source = drive_root / "final_artifacts"

required_files = [
    "alarb_judgments_6000.index",
    "alarb_judgments_metadata_6000.parquet",
    "alarb_search_config.json",
]

for name in required_files:
    path = artifacts_source / name
    assert path.exists(), f"Missing file: {path}"
    print(name, f"{path.stat().st_size / (1024**2):.2f} MB")

repo_dir = Path("/content/Esnad")

if not repo_dir.exists():
    subprocess.run(
        [
            "git", "clone",
            "--branch", "upscaling",
            "https://github.com/raghad-cs/Esnad.git",
            str(repo_dir),
        ],
        check=True,
    )
else:
    print("Repository folder already exists:", repo_dir)

target = repo_dir / "artifacts" / "alarb"
target.mkdir(parents=True, exist_ok=True)

for name in required_files:
    shutil.copy2(artifacts_source / name, target / name)

print("\nFiles staged in:", target)
for name in required_files:
    p = target / name
    print(name, f"{p.stat().st_size / (1024**2):.2f} MB")

alarb_judgments_6000.index 23.44 MB
alarb_judgments_metadata_6000.parquet 26.76 MB
alarb_search_config.json 0.00 MB

Files staged in: /content/Esnad/artifacts/alarb
alarb_judgments_6000.index 23.44 MB
alarb_judgments_metadata_6000.parquet 26.76 MB
alarb_search_config.json 0.00 MB