In [1]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))

PyTorch: 2.11.0+cu128
CUDA: True
GPU: Tesla T4

In [2]:
from sentence_transformers import SentenceTransformer
import torch

MODEL_NAME = "BAAI/bge-m3"

model = SentenceTransformer(
    MODEL_NAME,
    device="cuda"
)

model.max_seq_length = 8192

print("Model loaded successfully!")
print("Device:", model.device)
print("GPU:", torch.cuda.get_device_name(0))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/15.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin: reconstructing file:   0%|          |  0.00B / 2.27GB

pytorch_model.bin: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Model loaded successfully!
Device: cuda:0
GPU: Tesla T4

In [4]:
!pip install -q faiss-cpu

In [7]:

import os
import re
import sys
import subprocess
import pandas as pd
import numpy as np
import torch
from tqdm.auto import tqdm
from google.colab import files

# 1. Check GPU
assert torch.cuda.is_available(), "GPU is not available. Enable GPU in Colab first."
print("GPU:", torch.cuda.get_device_name(0))

# 2. Upload dataset
uploaded = files.upload()
csv_file = next(
    (name for name in uploaded if name.lower().endswith(".csv")),
    None
)
assert csv_file is not None, "Please upload the CSV dataset."

try:
    df = pd.read_csv(csv_file, encoding="utf-8-sig")
except UnicodeDecodeError:
    df = pd.read_csv(csv_file, encoding="cp1256")

print("Original dataset:", df.shape)

# 3. Validate columns
required = ["case_text", "EVENTS", "REASONING", "RULING"]
missing = [c for c in required if c not in df.columns]
assert not missing, f"Missing columns: {missing}"

# 4. Remove exact duplicate judgments
df_clean = df.drop_duplicates(
    subset=required,
    keep="first"
).copy().reset_index(drop=True)

# 5. Prepare text
def clean_text(text):
    text = str(text)
    text = text.replace("⏎", "\n")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n+", "\n", text)
    return text.strip()

df_clean["search_text"] = (
    "الوقائع:\n"
    + df_clean["EVENTS"].fillna("").apply(clean_text)
    + "\n\nأسباب الحكم:\n"
    + df_clean["REASONING"].fillna("").apply(clean_text)
)

# 6. Load tokenizer
from transformers import AutoTokenizer

MODEL_NAME = "BAAI/bge-m3"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# 7. Split documents into manageable chunks
MAX_TOKENS = 3000
OVERLAP = 200

chunks = []
chunk_to_doc = []

for doc_id, text in enumerate(tqdm(df_clean["search_text"], desc="Preparing chunks")):
    token_ids = tokenizer(
        text,
        add_special_tokens=False,
        truncation=False
    )["input_ids"]

    if len(token_ids) <= MAX_TOKENS:
        chunks.append(text)
        chunk_to_doc.append(doc_id)
    else:
        start = 0
        while start < len(token_ids):
            end = min(start + MAX_TOKENS, len(token_ids))
            chunk = tokenizer.decode(
                token_ids[start:end],
                skip_special_tokens=True
            )
            chunks.append(chunk)
            chunk_to_doc.append(doc_id)
            start += MAX_TOKENS - OVERLAP

print("Judgments:", len(df_clean))
print("Chunks:", len(chunks))

# 8. Load embedding model
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(MODEL_NAME, device="cuda")
model.max_seq_length = MAX_TOKENS

# 9. Generate embeddings
embeddings = model.encode(
    chunks,
    batch_size=2,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
).astype("float32")

# 10. Install FAISS if needed
try:
    import faiss
except ImportError:
    subprocess.check_call([
        sys.executable, "-m", "pip",
        "install", "-q", "faiss-cpu"
    ])
    import faiss

# 11. Build vector index
index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings)

# 12. Save everything
np.save("/content/esnad_embeddings.npy", embeddings)
np.save("/content/esnad_chunk_to_doc.npy", np.array(chunk_to_doc))
faiss.write_index(index, "/content/esnad_faiss.index")
df_clean.to_pickle("/content/esnad_metadata.pkl")

print("\n========== ESNAD RESULTS ==========")
print("Original rows:", len(df))
print("Unique judgments:", len(df_clean))
print("Total chunks:", len(chunks))
print("Embedding shape:", embeddings.shape)
print("FAISS vectors:", index.ntotal)
print("GPU:", torch.cuda.get_device_name(0))
print("\nAll files saved successfully!")

GPU: Tesla T4

Saving ArabiCCR-dataset.csv to ArabiCCR-dataset.csv
Original dataset: (12806, 12)

Preparing chunks:   0%|          | 0/12477 [00:00<?, ?it/s]

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (10786 > 8192). Running this sequence through the model will result in indexing errors

Judgments: 12477
Chunks: 15532

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Batches:   0%|          | 0/7766 [00:00<?, ?it/s]

========== ESNAD RESULTS ==========
Original rows: 12806
Unique judgments: 12477
Total chunks: 15532
Embedding shape: (15532, 1024)
FAISS vectors: 15532
GPU: Tesla T4

All files saved successfully!

In [8]:
import numpy as np
import pandas as pd

# سؤال قانوني تجريبي
query = "مطالبة شركة بمستحقات عقد توريد بعد تسليم البضائع وامتناع الطرف الآخر عن السداد"

# تحويل السؤال إلى متجه
query_embedding = model.encode(
    [query],
    convert_to_numpy=True,
    normalize_embeddings=True
).astype("float32")

# البحث عن أفضل 200 مقطع
k = min(200, index.ntotal)
scores, indices = index.search(query_embedding, k)

# إزالة تكرار الأحكام والاحتفاظ بأعلى درجة لكل حكم
results = []
seen_docs = set()

for score, chunk_idx in zip(scores[0], indices[0]):
    if chunk_idx < 0:
        continue

    doc_id = int(chunk_to_doc[chunk_idx])

    if doc_id in seen_docs:
        continue

    seen_docs.add(doc_id)
    row = df_clean.iloc[doc_id]

    results.append({
        "similarity": round(float(score), 4),
        "judgment_number": row.get("judgment_number"),
        "case_number": row.get("case_number"),
        "judgment_date": row.get("judgment_date"),
        "city": row.get("city"),
        "details_url": row.get("details_url"),
        "preview": row["search_text"][:500]
    })

    if len(results) == 10:
        break

results_df = pd.DataFrame(results)

print("Search query:", query)
print("Retrieved chunks:", len(indices[0]))
print("Unique judgments returned:", len(results_df))
print("Duplicate judgments in results:", results_df["judgment_number"].duplicated().sum()
      if not results_df.empty else 0)

display(results_df)

Search query: مطالبة شركة بمستحقات عقد توريد بعد تسليم البضائع وامتناع الطرف الآخر عن السداد
Retrieved chunks: 200
Unique judgments returned: 10
Duplicate judgments in results: 0

,similarity,judgment_number,case_number,judgment_date,city,details_url,preview
0,0.7184,5648,5648,1442-06-27,جدة,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص وقائع هذه الدعوى بالقدر اللازم...
1,0.6802,1545,1545,1442-11-04,الرياض,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص وقائع الدعوى بما يكفي لإصدار ه...
2,0.6773,10876,10876,1442-05-06,الرياض,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص وقائع هذه الدعوى في أنه وردت إ...
3,0.6734,6380,6380,1442-08-04,جدة,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص وقائع هذه الدعوى في أنه وردت إ...
4,0.6681,2754,2754,1442-08-16,جدة,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص وقائع هذه الدعوى بلائحة دعوى أ...
5,0.6627,3274 لعام 1438 هـ,3274 لعام 1438 هـ,1439-03-02,الرياض,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص في أن وكيل [Person Name] دعوى ...
6,0.6626,7332,7332,1442-07-16,جدة,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتقدم المدعي [Person Name]: لي بذمة ا...
7,0.6623,937,937,1442-06-26,جدة,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتقدم وكيل [Person Name] : تم الاتفاق...
8,0.6622,1812,1812,1442-07-23,جدة,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتقدم وكيل [Person Name]: قام موكلي ع...
9,0.6614,2557,2557,1440-07-17,الرياض,https://laws.moj.gov.sa/ar/JudicialDecisionsLi...,الوقائع:\nتتلخص وقائع هذه الدعوى بأن وكيل [Per...

In [9]:

import re
import pandas as pd
from collections import Counter

# 1. تجهيز النصوص
text_cols = ["case_text", "EVENTS", "REASONING", "RULING"]

audit_df = df_clean.copy()

audit_df["full_text"] = (
    audit_df[text_cols]
    .fillna("")
    .astype(str)
    .agg("\n".join, axis=1)
)

# 2. مؤشرات درجة التقاضي
degree_patterns = {
    "استئناف": [
        r"محكمة الاستئناف",
        r"الدائرة الاستئنافية",
        r"المحكمة التجارية الاستئنافية",
        r"الحكم المستأنف",
        r"الاستئناف المقدم"
    ],
    "عليا": [
        r"المحكمة العليا",
        r"الدائرة بالمحكمة العليا",
        r"المحكمة التجارية العليا"
    ],
    "ابتدائي - مؤشر صريح": [
        r"المحكمة الابتدائية",
        r"الدائرة الابتدائية",
        r"حكم ابتدائي",
        r"المحكمة التجارية الابتدائية"
    ]
}

def detect_degree(text):
    found = []
    for degree, patterns in degree_patterns.items():
        if any(re.search(p, text) for p in patterns):
            found.append(degree)
    return " | ".join(found) if found else "غير محدد"

audit_df["degree_candidate"] = audit_df["full_text"].apply(detect_degree)

# 3. تصنيف أولي لموضوع النزاع
dispute_patterns = {
    "توريد": [
        r"عقد توريد", r"توريد بضائع", r"توريد مواد",
        r"المورد", r"المورّد"
    ],
    "مقاولات وإنشاءات": [
        r"عقد مقاولة", r"أعمال المقاولة", r"مستخلصات",
        r"مقاول", r"مشروع إنشائي"
    ],
    "مطالبات مالية وديون": [
        r"مطالبة مالية", r"مستحقات مالية",
        r"مبلغ مستحق", r"سداد المبلغ", r"مديونية"
    ],
    "شراكات": [
        r"عقد شراكة", r"الشريك", r"الشركاء",
        r"تصفية الشراكة"
    ],
    "وكالات تجارية": [
        r"وكالة تجارية", r"الوكيل التجاري",
        r"عقد وكالة"
    ],
    "إيجار تجاري": [
        r"عقد إيجار", r"أجرة العقار",
        r"الأجرة المستحقة"
    ],
    "نقل وشحن": [
        r"عقد نقل", r"أجرة النقل",
        r"شحن البضائع", r"النقل التجاري"
    ],
    "أوراق تجارية": [
        r"شيك", r"كمبيالة", r"سند لأمر"
    ],
    "ملكية فكرية": [
        r"علامة تجارية", r"حقوق الملكية الفكرية",
        r"براءة اختراع"
    ],
    "إفلاس": [
        r"إجراء الإفلاس", r"إعادة التنظيم المالي",
        r"التصفية وفق نظام الإفلاس"
    ]
}

def classify_dispute(text):
    found = []
    for category, patterns in dispute_patterns.items():
        if any(re.search(p, text) for p in patterns):
            found.append(category)
    return " | ".join(found) if found else "غير مصنف"

audit_df["dispute_candidate"] = audit_df["full_text"].apply(
    classify_dispute
)

# 4. إحصائيات درجة التقاضي
print("=" * 55)
print("DEGREE OF LITIGATION AUDIT")
print("=" * 55)
print(audit_df["degree_candidate"].value_counts(dropna=False))

# 5. إحصائيات تصنيف النزاع
print("\n" + "=" * 55)
print("DISPUTE CLASSIFICATION AUDIT")
print("=" * 55)

category_counts = Counter()

for value in audit_df["dispute_candidate"]:
    for category in value.split(" | "):
        if category != "غير مصنف":
            category_counts[category] += 1

for category, count in category_counts.most_common():
    print(f"{category}: {count}")

print("غير مصنف:",
      (audit_df["dispute_candidate"] == "غير مصنف").sum())

# 6. عرض عينات للمراجعة
print("\n" + "=" * 55)
print("SAMPLE RESULTS")
print("=" * 55)

sample = audit_df[
    ["judgment_number", "judgment_date",
     "degree_candidate", "dispute_candidate"]
].sample(min(30, len(audit_df)), random_state=42)

display(sample)

# 7. حفظ نتائج الفحص
audit_df.drop(columns=["full_text"]).to_csv(
    "/content/esnad_classification_audit.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nAudit saved successfully:")
print("/content/esnad_classification_audit.csv")
print("Total judgments audited:", len(audit_df))

=======================================================
DEGREE OF LITIGATION AUDIT
=======================================================
degree_candidate
غير محدد                                10704
استئناف                                  1369
عليا                                      169
استئناف | ابتدائي - مؤشر صريح             105
ابتدائي - مؤشر صريح                        64
استئناف | عليا                             54
استئناف | عليا | ابتدائي - مؤشر صريح       11
عليا | ابتدائي - مؤشر صريح                  1
Name: count, dtype: int64

=======================================================
DISPUTE CLASSIFICATION AUDIT
=======================================================
مقاولات وإنشاءات: 4077
أوراق تجارية: 2540
شراكات: 2254
مطالبات مالية وديون: 1985
توريد: 1311
إيجار تجاري: 237
ملكية فكرية: 165
إفلاس: 89
نقل وشحن: 71
وكالات تجارية: 53
غير مصنف: 3848

=======================================================
SAMPLE RESULTS
=======================================================

,judgment_number,judgment_date,degree_candidate,dispute_candidate
429,4530236058,1445-02-01,غير محدد,مقاولات وإنشاءات
9056,1155,1442-11-19,استئناف,مقاولات وإنشاءات
7200,4430238822,1444-04-08,غير محدد,غير مصنف
5716,4430809287,1444-08-05,غير محدد,غير مصنف
5559,4430754413,1444-09-04,استئناف,مطالبات مالية وديون | إيجار تجاري | أوراق تجارية
4190,783/1/ق,1439-05-14,غير محدد,توريد | مقاولات وإنشاءات
4047,2292/1/ق,1439-07-15,غير محدد,شراكات | أوراق تجارية
6832,4430503399,1444-04-24,غير محدد,إيجار تجاري
2167,4089,1441-02-03,غير محدد,مطالبات مالية وديون
7768,4056,1443-03-07,غير محدد,شراكات
9927,1354,1442-09-15,غير محدد,توريد | مقاولات وإنشاءات
8222,2766,1443-02-01,غير محدد,أوراق تجارية
12162,8146,1442-06-14,غير محدد,غير مصنف
2982,5152,1440-04-20,غير محدد,مقاولات وإنشاءات
11047,6422,1442-07-25,غير محدد,مقاولات وإنشاءات | شراكات
10235,100,1442-08-25,غير محدد,غير مصنف
5674,4430669425,1444-08-11,غير محدد,مقاولات وإنشاءات | مطالبات مالية وديون
4454,3173/3/ق,1439-02-09,غير محدد,مقاولات وإنشاءات | أوراق تجارية
2487,5454,1440-11-27,غير محدد,مقاولات وإنشاءات
2732,1949,1440-08-06,غير محدد,أوراق تجارية
1369,6093,1441-06-04,غير محدد,مطالبات مالية وديون
8739,4832,1442-12-17,استئناف,مقاولات وإنشاءات
8432,9813,1443-01-15,غير محدد,توريد | أوراق تجارية
10924,4247,1442-08-03,غير محدد,شراكات
5579,4430847858,1444-08-30,غير محدد,مقاولات وإنشاءات
7774,6607,1443-03-07,غير محدد,أوراق تجارية
3954,1594/ 3/ق,1439-08-19,غير محدد,غير مصنف
1683,763,1441-03-29,غير محدد,مقاولات وإنشاءات
1498,7635,1441-04-27,غير محدد,أوراق تجارية
3169,402,1440-03-01,غير محدد,غير مصنف

Audit saved successfully:
/content/esnad_classification_audit.csv
Total judgments audited: 12477

In [10]:

import re
import pandas as pd

# البحث عن مؤشرات درجة التقاضي في كل حقل على حدة
patterns = {
    "استئناف": r"محكمة الاستئناف|الدائرة الاستئنافية|الحكم المستأنف|الاستئناف المقدم",
    "عليا": r"المحكمة العليا|الدائرة بالمحكمة العليا",
    "ابتدائي": r"المحكمة الابتدائية|الدائرة الابتدائية|حكم ابتدائي"
}

text_fields = ["case_text", "EVENTS", "REASONING", "RULING"]

print("=" * 60)
print("DEGREE EVIDENCE BY TEXT FIELD")
print("=" * 60)

for degree, pattern in patterns.items():
    print(f"\n--- {degree} ---")
    for field in text_fields:
        count = audit_df[field].fillna("").astype(str).str.contains(
            pattern, regex=True
        ).sum()
        print(f"{field}: {count}")

# عرض سياق العبارات التي ظهرت في الأحكام
print("\n" + "=" * 60)
print("REAL TEXT EVIDENCE SAMPLES")
print("=" * 60)

for degree, pattern in patterns.items():
    matched = audit_df[
        audit_df["full_text"].str.contains(pattern, regex=True, na=False)
    ]

    print(f"\n### {degree} | Total: {len(matched)}")

    for _, row in matched.head(5).iterrows():
        text = row["full_text"]
        match = re.search(pattern, text)
        start = max(0, match.start() - 180)
        end = min(len(text), match.end() + 250)

        print("\nJudgment:", row["judgment_number"])
        print("Date:", row["judgment_date"])
        print("Evidence:", text[start:end].replace("\n", " "))

# حفظ العينة
audit_df.to_csv(
    "/content/esnad_degree_evidence.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nAudit completed.")
print("Total judgments:", len(audit_df))

============================================================
DEGREE EVIDENCE BY TEXT FIELD
============================================================

--- استئناف ---
case_text: 1538
EVENTS: 1161
REASONING: 659
RULING: 79

--- عليا ---
case_text: 235
EVENTS: 130
REASONING: 122
RULING: 4

--- ابتدائي ---
case_text: 181
EVENTS: 121
REASONING: 70
RULING: 9

============================================================
REAL TEXT EVIDENCE SAMPLES
============================================================

### استئناف | Total: 1539

Judgment: 4530004948
Date: 1445-11-16
Evidence: قيته به، ولأن القول المختار في مدة التقادم راجع لاجتهاد القاضي، ولأن مدة سكوت المدعى عن إقامة الدعوى تعد طويلة جدا، لذلك فقد حكم القاضي [Person Name]، فاعترض المدعى، وصدق الحكم من محكمة الاستئناف، ولذلك فإن محكمة (الاستئناف) أوردت في قرارها رقم (275/ق5/ب) وتاريخ 25/6/1429هـ أن دلالة الحال تغني عن دلالة المقال، فالسكوت مدة طويلة عن المطالبة بالملك مع تصرف غيره به دليل عدم صحة الدعوى . وتأسيساً على ما سبق فإني أطلب من فضيلتكم: تثبيت إقراره بأح

Judgment: 4530547483
Date: 1445-06-06
Evidence: ٠٦٥ وتاريخ 5-2-1442 هـ الصادر من دائرتكم الموقّرة والمتضمّن [Person Name] [Person Name] (2893786) مليونين وثمانمائة وثلاثة وتسعون ألف وسبعمائة وستة وثمانون ريال وتم تأييد الحكم من محكمة الاستئناف التجارية بمنطقة الرياض بموجب بالصك المقيد بالرقم ٣٨٢١٩٣١٤ وتاريخ 19-7-1442 هـ وقد تضرر موكلي نظير مماطلة [Person Name] [Person Name] بقيمة وقدرها (٢٠٢.٥٦٥.٢٠) مائتان واثنان ألف وخمسمائة وخمسة وستون ريال وعشرون هللة (مرفق عقد الأتعاب) أيضاً سدد موكلي

Judgment: 4530509459
Date: 1445-05-21
Evidence: تفاقية شراكتها وتخارجها في شركة [Person Name] بدعوى المدعية: بداية ونحن لا نعقب على احكام القضاء الجديرة بالاحترام والتقدير والتي نجلها ونقدرها ولكن اتناول في مسألة العروج علي حكم محكمة الاستئناف أن أصحاب الفضيلة أشاروا الى نص الفقرة 2 من المادة 76 من نظام المرافعات الشرعية ولأن نص الفقرة الثانية من المادة المشار اليها استهلت بعبارة إذا رأت المحكمة ومن ثم فالأمر متروك للمحكمة التي تنظر الدعوى دون معقب. وبالإشارة الى ورقة التخارج المرفقة من ا

Judgment: 4530574150
Date: 1445-04-24
Evidence: ي تمام الساعة 9.45 صباحاً وتم إغلاق الجلسة في تمام الساعة 10:27صباحاً، وبناء عليه أصدرت الدائرة حكمها في ذات الجلسة والقاضي [Person Name]، وتشير الدائرة بأنه قد تم إعادة القضية من محكمة الاستئناف – الدائرة السادسة – وقد جرى تحديد جلسة 19/3/1445ه موعداً لنظرها وفيها حضر (اياس بن إبراهيم بن عبدالعزيز الغصن) بهوية رقم (...) وبالوكالة رقم (451524012) وحضر لحضوره (ناصر بن عبدالله ناصر السهلي) بهوية رقم (..) وبالوكالة رقم (4558634)،وتشير الدائرة ب

Judgment: 4530542249
Date: 1445-04-20
Evidence: ترتب عليه أن طلب الاعتزال يدخل في مضمون طلب العزل، بل قد يكون الأحظ، نظراً لكونه يتأتى على وجه الاختيار لا عن إجبار أو إكراه، وعليه، فإن طلب الاعتزال حق مشروع للمدير، وهو ما قررته محكمة الاستئناف التجارية بمحافظة جدة في حكمها الصادر في الدعوى رقم (439448005) لعام 1443هـ، ولا ينال من ذلك ما دفعت به المدعى عليه[Person Name] ببيع حصصه في الشركة [Person Name]، باعتبار أن المادة (8/1) من نظام الشركات نصت على أنه: يجب أن يكون عقد تأسيس الشركة [Per

### عليا | Total: 235

Judgment: 4530547384
Date: 1445-04-20
Evidence: خطأ في التقرير المحاسبي المقدم للمحكمة، وأنها هي من قدمت الدعم المادي للمدعي[Person Name][Person Name]، وبسؤال الدائرة طرفي الدعوى عما يودان إضافته ذكر وكيل [Person Name] ملاق وأن المحكمة العليا رفضت طلب النقض وتمسك بطلب موكلته، كما اكتفى وكيل [Person Name]، وعليه قررت الدائرة رفع الجلسة للمداولة والنطق بالحكم المستند على التالي من: ⏎  ⏎ الأسباب: ⏎ لما انتهت المدعي[Person Name] المدعى عليه[Person Name] (46.000) ستة وأربعون ألف ريال يمثل أتع

Judgment: 4530515808
Date: 1445-04-12
Evidence:  قرره [Person Name] [Person Name]، فهو مالك له ووكيل [Person Name]، ولما هو متقرر بأن السعي يكون لمن وفق بين البائع والمشتري، لا للأصيل ولا للوكيل، فقد جاء في المبادئ والقرارات من المحكمة العليا (19/ 3/ 3) في 09/ 09/ 1430هـ ما نصه: بائع العقار والوكيل [Person Name]؛ لأن السعي للطرف الثالث الذي فق بين البائع والمشتري ، ولجميع ما تقدم. ⏎  ⏎ نص الحكم: ⏎ فقد حكمت بإلزام [Person Name] [Person Name]ً قدره (325,000) ثلاثمائة وخمسة وعشرون ألف ريالا

Judgment: 4530513777
Date: 1445-04-06
Evidence: على موكلتي أي من هذه الحالات والدعوى حق مشروع للمدعي [Person Name] عدم ثبوت الحق لا يتنبأ به أطراف الخصومة وبالتالي فإن معاقبة المدعي [Person Name] مشروعية الدعوى. فقد جاء في قرار المحكمة العليا رقم ٤.٢.٢ وتاريخ ٠٦.٠١.١٤٣١ العجز عن إثبات الدعوى لا يلزم منه كذب المدعي [Person Name]، وليس مجرد العجز عن إثبات الدعوى موجباً للتعزير، ما لم يثبت الكيدية فيها، كما جاء في قرار المحكمة العليا ١٧.٢.٣ وتاريخ ١٨.١٢.١٤٣٤هـ أن الاستدلال على أن الدعوى كيد

Judgment: 4530437365
Date: 1445-03-18
Evidence:  التوضيح لفضيلتكم أنه تم تبليغ المدعى عليه[Person Name] جائحة كورونا ( مرفق رقم (1) ولعلم فضيلتكم أن التأخير الذي حدث كان يسبب أمر خارج عن إرادة موكلي وهي مدة 3 أيام فقط وحسب قرار المحكمة العليا رقم ( 45 ) تاریخ: 08 / 05 / 1442هـ والذي نص على: تعد جانحة فايروس كورونا من الظروف الطارئة إذا لم يمكن تنفيذ الالتزام أو العقد إلا بخسارة غير معتادة فالتأخير في تسليم الأعمال لم يكن بيد موكلي ولا باختياره فهو شي خارج عن إرادته بسب الجائحة وما ترتب ع

Judgment: 4530407259
Date: 1445-03-12
Evidence: ذ تعييني مديرا للشركة [Person Name] أصل للشركة [Person Name] بذلك، ندفع بعدم جواز نظر هذه الطلبات لسبق الفصل فيها بالقضية رقم (٤۳۹۱۰٦۲۱۱) بحكم نهائي مؤيد من الاستئناف وتم رفضها من المحكمة العليا برفض الدعوى لعدم اتباع المدعي [Person Name]. ندفع بعدم جواز نظر هذه الطلبات لسبق الفصل فيها بالقضية رقم (٤۳۹۱٦۳٦۳۷) والتي صدر فيها حكم نهائي مؤيد من الاستئناف برفض الدعوى المدعي [Person Name]. ثالثاً: الرد على الطلب الرابع، أن المدعي [Person Name] 1

### ابتدائي | Total: 181

Judgment: 4530547483
Date: 1445-06-06
Evidence: اجة القضية لندب خبير محاسبي وذلك لما شاب اوراق المحاسبة بينهما من غموض لا ينجلي إلا بندب خبير لذلك وعليه ندبت خبيرا محاسبيا وقدم الخبير تقريره النهائي بالدعوى بعد فحص البنود وحكمت الدائرة الابتدائية بما انتهى إليه الخبير, ثم في دائرة الاستئناف اعترض [Person Name] [Person Name] المصروفات وبعد اطلاع دائرة الاستئناف على تقرير الخبير تبين لها أن المبالغ التي ذكرها وكيل [Person Name]، قد قام الخبير بالاطلاع عليها وانتهى إلى عدم احتسابها، والدائرة تط

Judgment: 4530509459
Date: 1445-05-21
Evidence: 1/1444هـ والقاضي [Person Name]ً، وفي الموضوع، بإلغاء حكم الدائرة التجارية السادسة عشرة في المحكمة التجارية بجدة المؤرخ في 24-11-1444هــ، في القضية رقم 4471044825 وإعادة القضية إلى الدائرة الابتدائية للفصل فيها؛ لما هو موضح بالأسباب وبإعادتها الى الدائرة مصدرة الحكم بتاريخ 21/01/1445هـ عقدت الدائرة لنظرها جلسة عبر الاتصال المرئي بتاريخ 12/02/1445هـ وفيها حضرت سارة سعود هليل الصليمي -المدونة بياناتها في محضر الجلسة- وحضر لحضورها تركي مسلم مرزوق ا

Judgment: 4530543196
Date: 1445-04-20
Evidence: شروع من عدمه وبما ان وكيل [Person Name] المشروع تمت ترسيته من قبل مالكة المشروع للمدعى عليها فإن الدعوى تكون مقبولة يجب المضي في نظر موضوعها، مما ترى معه دائرة الاستئناف إلغاء حكم الدائرة الابتدائية و إعادة القضية اليها للنظر في الموضوع . وبعد إحالة القضية إلى الدائرة باشرت نظرها على النحو المثبت في محاضر الضبط بجلسة ١١/٤/١٤٤٥هـ المنعقدة عبر الاتصال المرئي حضر وكيل المدعي (...) هوية وطنية رقم (...) وبالوكالة رقم (...) كما حضر وكيل [Person Name]

Judgment: 4530568910
Date: 1445-04-20
Evidence: بقة كان نتيجة لفسخ العقد، وبم أن المدعي[Person Name] في القضية السابقة أثبت تأخر المدعى عليه[Person Name] في تسبيبها للحكم، وبما أن المدعي[Person Name] الحكم في القضية السابقة لدى الدائرة الابتدائية ودائرة الاستئناف، وعقد أتعاب المحاماة، والحوالة البنكية إلى الخبير، وباطلاع الدائرة على صك الحكم رقم 4430218137 الصادر بتاريخ 21-04-1444هـ تبين أن الدائرة أخذت بالنتيجة التي توصل إليها الخبير بأن المدعى عليه[Person Name] وفي السداد وفي توقيع ملاحق ا

Judgment: 4530378462
Date: 1445-04-17
Evidence: ، أو تزويرها، وذلك بعد مرافعة مستكملة إجراءاتها الشرعية والنظامية . ثم تقدمنا للمحكمة الإدارية بالرياض بطلب إلغاء القرار الإداري وقيدت برقم دعوى 7044 لعام 1444هـ وأحيلت الدعوى إلى الدائرة الابتدائية (الخامسة) في المحكمة الإدارية بالرياض أصدرت حكمها في الجلسة الأولى والمنتهي في نتيجته بعدم اختصاص محاكم ديوان المظالم ولائيا بنظر الدعوى . ثم تقدمنا باعتراضنا على الحكم وأحيلت الدعوى لمحكمة الاستئناف الإدارية برقم دعوى 6678 لعام 1444 حيث أصدرت حكمها

Audit completed.
Total judgments: 12477

In [11]:

import pandas as pd
import re

# اختيار الأحكام التي ظهرت فيها مؤشرات درجة التقاضي
candidates = audit_df[
    audit_df["degree_candidate"] != "غير محدد"
].copy()

# عينة متنوعة
sample_ids = candidates.sample(
    min(20, len(candidates)),
    random_state=21
).index

for i, idx in enumerate(sample_ids, 1):
    row = audit_df.loc[idx]

    print("\n" + "=" * 75)
    print(f"JUDGMENT {i}")
    print("Judgment number:", row["judgment_number"])
    print("Case number:", row["case_number"])
    print("Date:", row["judgment_date"])
    print("Court name:", row["court_name"])
    print("Degree indicators:", row["degree_candidate"])
    print("Dispute indicators:", row["dispute_candidate"])

    text = str(row["case_text"])

    print("\n--- BEGINNING OF CASE TEXT ---")
    print(text[:1200])

    print("\n--- END OF CASE TEXT ---")
    print(text[-800:])

# ملخص القيم الأصلية
print("\n" + "=" * 75)
print("ORIGINAL COURT NAME VALUES")
print(audit_df["court_name"].value_counts(dropna=False).head(20))

print("\nORIGINAL CASE TYPE VALUES")
print(audit_df["case_type"].value_counts(dropna=False).head(20))

print("\nTotal inspected:", len(sample_ids))

===========================================================================
JUDGMENT 1
Judgment number: 11070
Case number: 11070
Date: 1443-01-02
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: شراكات

--- BEGINNING OF CASE TEXT ---
الحمد لله والصلاة والسلام على رسول ﷲ أما بعد: ⏎ فلدى الدائرة التجارية الخامسة وبناءً على القضية رقم 11070 لعام 1441 هـ ⏎  ⏎ المقامة من/ (...) هوية وطنية (...) ⏎ ضد/ (...) هوية وطنية (...) ⏎  ⏎ (الوقائع) ⏎ تتلخص وقائع هذه الدعوى وبالقدر اللازم لإصدار هذا الحكم في أنه وردت إلى المحكمة التجارية لائحة دعوى مقدمة من المدعي [Person Name]: "أن موضوع الدعوى مطالبة في أتعاب الترافع في قضيتين تم النظر فيهما وإصدار الأحكام من قبل الدائرة الخامسة في المحكمة التجارية في الرياض، وحيث إن نشوء الحق بدأ في تاريخ 04/11/1441هـ حينما فُسخت وكالة المدعي [Person Name] في الأتعاب للقضيتين: القضية الأولى رقم 11624 لعام 1440هـ حيث إن المبلغ المتفق عليه كما هو واضح في الإقرار المرفق والذي كتبه [Person Name] [Person Name] 27/04/2019م الموافق22/08/1440هـ والمبلغ قدره (100000 ريال سعودي) مائة ألف ريال سعودي وحصر طلبه في [Person Name] [Person Name] الدائرة من أتعاب، أما القضية الثانية فهي برقم 5679 لعام 1440هـ ويطالب [Person Name] [Person Name] (50000 ريال سعودي) خمسون ألف ريال سعودي أو ما تراه الدائرة، وقد اتفقا الطرفان على ذلك إلا أنه لم يكن هناك اتفاق مكتوب نظراً لثقة المدعي [Person Name]". وبعد التأكد من مسألتي الاختصاص والقبول تم قيد القضية واحالتها للدائرة تم النظر فيها على النحو المثبت من خلال الترافع ال

--- END OF CASE TEXT ---
هما في أي جلسة أمام المحكمة، أو قدم مذكرة بدفاعه، عُدَّت الخصومة حضورية، ولو تخلف بعد ذلك " وحيث ثبت للدائرة تبلغ [Person Name] [Person Name]، ولم يقدم إجابته على الدعوى، مما يؤكد صحة الدعوى ويعد ذلك نكولاً عن الإجابة وهو بمنزلة الإقرار الضمني بمضمونها ولا ينال منه حضور وكيل [Person Name] تحرير الدعوى لتقديم الجواب حيث لم يحضر إلا بعد إغلاق باب الترافع كما تم بيانه في محضر الجلسة رغم تبلغ موكله سابقاً مما يظهر معه قصد المماطلة وإطالة أمد التقاضي دون مبرر ولا يمنعه ذلك من تقديم جوابه في اعتراضه على الحكم، ولما تبين للدائرة ثبوت المبلغ محل المطالبة في ذمة [Person Name] [Person Name] شرعي الأمر الذي تنتهي معه الدائرة إلى الحكم الوارد بمنطوقه. ⏎  ⏎ (منطوق الحكم) ⏎ حكمت الدائرة: بإلزام (...) سجل مدني رقم: (...) أن يدفع ل(...) سجل مدني رقم : (...) مبلغاً قدره (150.000) مئة وخمسون ألف ريال. ⏎  ⏎

===========================================================================
JUDGMENT 2
Judgment number: 4430239347
Case number: 4430239347
Date: 1444-02-15
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: شراكات

--- BEGINNING OF CASE TEXT ---
الحمدلله والصلاة والسلام على رسول الله أما بعد: ⏎ فلدى الدائرة التجارية الأولى وبناء على القضية رقم 439429022 لعام 1443هـ ⏎  ⏎ المدعي: ⏎ [Person Name] صالح كعكي ⏎ ياسمين عبدالاله [Person Name] ⏎ زياد عبدالاله [Person Name] ⏎ عبدالرحمن عبدالاله [Person Name] ⏎ عبدالعزيز عبدالاله [Person Name] ⏎ عبير عبدالاله [Person Name] ⏎ فاتن [Person Name] ⏎ سهام [Person Name] ⏎ مياء [Person Name] ⏎ المدعى عليه: ⏎ [Person Name] ⏎  ⏎ الوقائع: ⏎ وجيز وقائع الدعوى يتحصل بلائحة دعوى أودعت لدى هذه المحكمة في 15/10/1443هـ ذكر فيها وكيل [Person Name] [Person Name] [Person Name]ً لشركة [Person Name] الـاثنا عشر مليون دولار التي تم تحويلها من الحساب التابع لشركة [Person Name] الشريك الآخر أحمد محمد صالح كعكي، وإلزام [Person Name] [Person Name] وقدرها ستة مليون دولار.وبعرضها على وكيل [Person Name] لمرور أكثر من 5 سنوات على تاريخ انتهاء التصفية وفقاً لنص المادة (210) من نظام الشركات، فسألته الدائرة هل كان قد صدر قرار بقفل أعمال التصفية؛ فأجاب بأنه كان قد صدر عن الدائرة التجارية الثانية عشر بديوان المظالم قرار بقفل أعمال التصفية عام 1429هـ. مشيراً بأن التصفية هي تصفية اختيارية تمت بموجب قرار الشركاء بدأت بتاريخ 01/02/1427هـ، الموافق 01/03/2006م ولم يتم صدور أمر قضائي بتمديدها، وعليه تكون مدة التصفية قد انتهت

--- END OF CASE TEXT ---
 Name] [Person Name]ُيّن مصفياً للشركة في 01/02/1427هـ، الموافق 01/03/2006م وذلك بموجب قرار الشركاء، وكان المبلغ محل الدعوى إنما تم تحويله في عام 1997م وفق ما ساقته الوقائع؛ تأسيساً عليه فليس من المستساغ محاسبة مصفي الشركة [Person Name]ٍ على تاريخ تعيينه، وهو ما تنتهي معه الدائرة إلى رفض الدعوى. ⏎  ⏎ نص الحكم: ⏎ حكمت الدائرة: برفض الدعوى رقم (439429022) المقامة من لمياء [Person Name] سجل مدني رقم (...) وبلقيس [Person Name] سجل مدني رقم (...) وبثينه [Person Name] سجل مدني رقم (...) وياسمين عبدالاله [Person Name] سجل مدني رقم (...) [Person Name] سجل مدني رقم (...) [Person Name] سجل مدني رقم (...) [Person Name] سجل مدني رقم (...) وعبير عبدالاله [Person Name] سجل مدني رقم (...) وفاتن [Person Name] سجل مدني رقم (...) وسهام [Person Name] سجل مدني رقم (...) ضد [Person Name] سجل مدني رقم (...). ⏎

===========================================================================
JUDGMENT 3
Judgment number: 8432
Case number: 8432
Date: 1442-07-18
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: مقاولات وإنشاءات | مطالبات مالية وديون

--- BEGINNING OF CASE TEXT ---
الحمد لله والصلاة والسلام على رسول ﷲ أما بعد: ⏎ فلدى الدائرة التجارية الاولى وبناءً على القضية رقم ٨٤٣٢ لعام ١٤٤٠ هـ ⏎  ⏎ المقامة من/(...) هوية وطنية (...) ⏎ ضد/مؤسسة (...) للمقاولات لصاحبها (...) غير ذلك (...) ⏎  ⏎  ⏎ (الوقائع) ⏎ تتحصل وقائع هذه القضية حسبما تبين من مطالعة أوراقها المقدمة وذلك بالقدر اللازم لإصدار هذا الحكم بأن وكيل [Person Name] دعوى ذكر فيها ما نصه: (كان بين موكلي والمدعى عليه[Person Name] مخالصة بإنهاء الشراكة وتحمل المدعى عليه[Person Name] لم تلتزم المدعى عليه[Person Name] أحد الدائنين (...) يعود على موكلي برفع قضية تنفيذ ضده كونه كفيل غارم للمدعى عليها بالمتبقي من ثمن (...) اشترتها المدعى عليه[Person Name] مما جعله يضطر لسداد المتبقي من الدين للبائع ورفع هذه الدعوى لمطالبة المدعى عليه[Person Name].) ⏎ وقد تم قيدها قضية بالرقم المشار إليه في صدر الحكم وفي سبيل نظر الدعوى حددت الدائرة عدة جلسات حسب ما هو مثبت في الضبط. وفي جلسة ٣٠/٦/١٤٤٠هـ حضرت وكيل[Person Name] -أمام الدائرة الفرعية- في حين تبين عدم حضور [Person Name] [Person Name] هذه الجلسة عن طريق نظام أبشر ثم سألت الدائرة وكيل[Person Name] لائحة دعوى محرره تضمنت بأن المدعي [Person Name] (٧٠,٠٠٠) ريال بالإضافة إلى المطالبة بأتعاب المحاماة. ثم سألتها الدائرة عن العلاقة التي تربط موكلها بالمدعي [Person Name]

--- END OF CASE TEXT ---
بلغ يخص عقد التقسيط؛ الذي كان محل الشراكة بين طرفي الدعوى فإن الدائرة تنتهي إلى [Person Name] [Person Name] (٧٠,٠٠٠) ريال استنادًا للمخالصة المبرمة بين طرفي الدعوى, وتحكم الدائرة بما جاء في منطوق حكمها أدناه. ⏎ وفيما يخص المطالبة بأتعاب المحاماة فبما أن [Person Name] [Person Name] بسداد ما التزم [Person Name] [Person Name] لأتعاب المحاماة وتقدره بنسبة (٥%) من مبلغ المطالبة الأصلي, وتحكم بموجب ذلك بإلزام [Person Name] [Person Name] (٣٥٠٠) ريال حسب ما جاء في منطوق حكمها أدنها. ⏎  ⏎ (منطوق الحكم) ⏎ لذا حكمت الدائرة بإلزام المدعى عليه/(...) سجل مدني رقم: (...) صاحب مؤسسة (...) للمقاولات سجل تجاري رقم: (...) بأن يدفع للمدعي/(...) سجل مدني رقم: (...) مبلغًا قدره (٧٣.٥٠٠) ثلاثة وسبعون ألفًا وخمسمائة ريال؛ لما هو مبين بالأسباب. وب ﷲ التوفيق وصلى ﷲ على نبينا محمد وعلى آله وصحبه وسلم. ⏎  ⏎  ⏎  ⏎  ⏎

===========================================================================
JUDGMENT 4
Judgment number: 4430241988
Case number: 4430241988
Date: 1444-04-08
Court name: المحكمة التجارية
Degree indicators: استئناف | ابتدائي - مؤشر صريح
Dispute indicators: مطالبات مالية وديون | إيجار تجاري

--- BEGINNING OF CASE TEXT ---
الحمدلله والصلاة والسلام على رسول الله أما بعد: ⏎ فلدى الدائرة التجارية الخامسة وبناء على القضية رقم ٤٣٩٠٥٦١٠٥ لعام ١٤٤٤هـ ⏎  ⏎ المدعي: ⏎ (...) ⏎  ⏎ المدعى عليه: ⏎ شركة (...) للحلويات والمعجنات ⏎  ⏎ الوقائع: ⏎ تتلخص وقائع هذه القضية بالقدر اللازم للحكم فيها أن/ (...)، سعودي الجنسية، بموجب الهوية الوطنية رقم (...) ، بالوكالة رقم (...)، وتاريخ ١٩/٠٧/١٤٤٧ه، عن/ (...)، تقدم بصحيفة دعوى إلكترونية للمحكمة التجارية جاء فيها، (إنه بتاريخ ١٤٣٢/٠٤/١٧ه الموافق ٢٠١١/٠٣/٢٢م اتفق أطراف الدعوى على أن يورد [Person Name] [Person Name] ١٤٣٢/٠٤/١٧ه الموافق ٢٠١١/٠٣/٢٢م بثمن إجمالي قدره (١٠٠٠٩٨٧٥) عشرة ملايين وتسعة آلاف وثمان مئة وخمسة وسبعون ريال سعودي سدد كامل، وقد استلم المدعي [Person Name] ، ومدة العقد (١٠) عشرة سنوات ، علماً أن نشوء الحق كان بتاريخ ١٤٣٢/٠٤/١٧ه الموافق ٢٠١١/٠٣/٢٢م، ونشأ بسبب هذه العلاقة التجارية وقوع خطأ من [Person Name] [Person Name]: (قيام المدعى عليه[Person Name] الامتياز بأسعار اقل من الأسعار المفروضة على الوكيل، وذلك بتاريخ ١٤٣٢/٠٤/١٧ه الموافق ٢٠١١/٠٣/٢٢م، مما تسبب بـ(توفر منتجات المدعى عليه[Person Name] من الأسعار المفروضة على وكيل [Person Name])، والعلاقة السببية بين الخطأ والضرر (قيام المدعى عليه[Person Name] ان تكون محصورة لدى موكلتي) ومقدار التعويض المطلوب (١٠٠٠٩٨٧٥) عشرة

--- END OF CASE TEXT ---
لتزويد فضيلتكم بالمحضر. عاشرا: اما ادعواهم ان سبب الخسائر ناتج عن تأثر الأسواق بجائحة كورونا فغير صحيح، فالخسائر وانخفاض المبيعات من عام ٢٠١٦م الى تاريخ الاغلاق وبداية الجائحة بتاريخ ٢٠١٩م ومع ذلك لم تتأثر المواد الغذائية بشكل خاص وهذا مشاهد عبر طلبات مواقع التوصيل فكانت النسبة الأعلى بالمبيعات، وكما قيل (كلمة حق اريد بها باطل) للتنصل عن مسؤوليتهم بتكبد موكلتي للخسائر قاموا بإلصاقها بجائحة كورونا.... أصحاب الفضيلة: نطلب من مقامكم الكريم التحقق من خطا المدعى عليه[Person Name] كما نوكد على طلباتنا وهي: التعويض عن الاضرار التي لحقت بموكلتي بمبلغ وقدره عشرة ملايين وتسعة الاف وثمانمائة وخمس وسبعون ريالا وخمس وسبعون هللة (١٠,٠٠٩,٨٧٥,٥٧)). وفي جلسة ١٣/٠٩/١٤٤٣ه وبعد تثبيت حضور الطرفين عن بعد، وبعد الاطلاع على الترافع الكتابي بينهما وجهت الدائرة السؤال للمدعي [Person Name] في العقد وكذلك تاريخ المخ

===========================================================================
JUDGMENT 5
Judgment number: 4322
Case number: 4322
Date: 1440-07-01
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: مقاولات وإنشاءات | مطالبات مالية وديون | أوراق تجارية

--- BEGINNING OF CASE TEXT ---
الحمد لله وحده والصلاة والسلام على من لا نبي بعده، وبعد: ⏎ فإنه في يوم الثلاثاء ١٤٤٠/٠٢/٠٧هـ وبمقر المحكمة التجارية بجدة عقدت الدائرة التجارية الثالثة جلستها بتشكيلها التالي: ⏎ القاضي (…) رئيسا ⏎ القاضي (…) عضوا ⏎ القاضي (…) عضوا ⏎ وبحضور (…) أمينا للسر، وذلك للنظر في القضية المشار إليها أعلاه المحالة للدائرة في ١٤٣٨/٠٨/١٣هـ، وفيها بعد المداولة أصدرت الدائرة هذا الحكم. ⏎ (الوقائع) ⏎ تتلخص وقائع الدعوى بالقدر اللازم لإصدار هذا الحكم في أنه بجلسة ٤/٨/١٤٣٣هـ تبين عدم حضور المدعى عليه[Person Name] لا يعرف [Person Name] المدعى عليه[Person Name] بجلسة اليوم (…)، التي تم توقيع العقدين موضوع هذه الدعوى معها، أولهما مؤرخ في ٢/٦/١٤٣٢هـ وموضوعه تصميم أعمال مظلة معدنية، وأعمال تشطيبات بفندق (…) الكائن في حي (…) بمدينة (…)، والعقد الثاني بتاريخ ٢٢/٨/١٤٣٢هـ، وموضوعه أعمال التكييف والكهرباء بذات الفندق، وأكد على أن الدعوى موجهه ضد مؤسسة (…) للمقاولات وأنه تم إبلاغ الحاضرة بالدعوى لعدم معرفة عنوان المدعى عليه، ولكون الحاضرة موظفه لدى المؤسسة، فذكرت (…) الحاضرة بجلسة اليوم بأن [Person Name] [Person Name] وأن [Person Name] [Person Name]، وطلبت إيداع مذكرتها المقدمة بجلسة اليوم والمكونة من صفحة واحدة مرفق بها عدد من المستندات وزودت وكيل [Person Name]، وذكرت أنها كانت مسئولة عن الأعمال موضوع هذه الدعو

--- END OF CASE TEXT ---
 Name] يفتقر إلى بينة قيامها بالأعمال لمالك المشروع من الأساس. ⏎ وأما عن طلب [Person Name] [Person Name] : (٥٠.٠٠٠) ريال، فإنه تبين للدائرة عدم أحقية المدعي[Person Name] عليها لتوكيل [Person Name]، لا سيما وأن المدعي [Person Name] حسبما هو مدون بوقائع الدعوى (حكم هيئة التدقيق رقم ١٢٨/ت/٤ لعام ١٤١٥هـ) ، ومن ثم تقضي الدائرة بإلزام المدعي[Person Name]. ⏎  ⏎  ⏎ (لذلك) ⏎ حكمت الدائرة أولاً: بإخراج (…) هوية وطنية رقم: (…) صاحب مؤسسة (…) لإدارة وتشغيل الفنادق سجل تجاري رقم: (…) من هذه الدعوى. ⏎ ثانياً: رفض دعوى المدعية. ⏎ ثالثاً: إلزام شركة (…) للتجارة والمقاولات المحدودة سجل تجاري رقم: (…) بأنْ تدفع لـ (…) هوية وطنية رقم: (…) صاحب مؤسسة (…) للمقاولات سجل تجاري رقم: (…) مبلغاً وقدره: (٥٠.٠٠٠ ريال) خمسون ألف ريال أتعاب محاماة. ⏎  ⏎ أمين السر ⏎ (…) ⏎ عضو ⏎ (…) ⏎ عضو ⏎ (…) ⏎ رئيس الدائرة ⏎ (…) ⏎  ⏎

===========================================================================
JUDGMENT 6
Judgment number: 2845/1/ق
Case number: 2845/1/ق
Date: 1439-10-27
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: شراكات

--- BEGINNING OF CASE TEXT ---
الحمد لله وحده والصلاة والسلام على من لا نبي بعده، وبعد: ⏎ فإنه في يوم الخميس ٢٨/١٠/١٤٣٩هــ وبمقر المحكمة التجارية بالرياض انعقدت الدائرة الأولى المشكلة من: ⏎  ⏎ القاضي/ (...) رئيساً ⏎ القاضي/ (...) عضواً ⏎ القاضي/ (...) عضواً ⏎ وبحضور/ (...) أميناً للسر، وذلك للنظر في هذه القضية المذكورة أعلاه والمحالة للدائرة مجدداً بتأريخ ٢٣/٦/١٤٣٥هــ. ⏎  ⏎ (الوقائع) ⏎ تتلخص وقائع هذه الدعوى في أنه تقدم إلى هذه المحكمة وكيل المدعي/ (...)، بلائحة دعوى ذكر فيها بأن موكله اتفق مع مورث المدعى عليه[Person Name] الغيار منذ ما يزيد عن ثلاثين عاماً على أن يكون لموكله نسبة (٥٠%) من الأرباح السنوية وكان موكله يتولى إدارة المحل وقد حقق المحل أرباحاً وأصبح يتبع المحل عدد من المستودعات، وحيث توفي مورث المدعى عليه[Person Name] ١٣/٧/١٤٣٠هـ وخلفه أبناؤه، ثم إنه بتأريخ ١٠/٢/١٤٣٣هـ حضر أحد الورثة، وهو/ (...) إلى المحل وقام بتغيير الأقفال ووضع اليد على المحل والمستودعات التابعة له ولم يسلم موكله حقوقه المتفق عليها، وأن مكتب/ (...) محاسبون قانونيون سبق وأن أثبت أن تقييم هذه المحلات مبلغ قدره (١٢,٦٧٥,٤٠١ريالاً) وأنه بناء عليه فإن موكله يملك نصف هذا المبلغ، وقدم عقد اتفاق موقع مع مورث المدعى عليه[Person Name] ١/٧/١٣٩٨هـ وقد جاء فيه: "١- يتم فتح محل باسم الطرف الأول (...) في (...) عدد كيلو (٣) ويسجل باسم الطرف الأول ب

--- END OF CASE TEXT ---
 [Person Name] (محل الدعوى)، وأما قدر نسبته منها، فبما أن العقد نص على وجود شريك ثالث تمثل حصته مع حصة المدعي ٥٠%، وقد حضر وكيل [Person Name] تنازل بنصيبه من الحصة للمدعي، فتكون كامل الحصة البالغة ٥٠% ملك للمدعي، والــ ٥٠% الباقية لمورث المدعى عليهم، حسب ما جاء في العقد. ⏎ ولا ينال مما تقدم دفع المدعى عليه[Person Name] أصدرته الدائرة الثانية في هذه المحكمة، إذ أنه بدراسة ذلك الحكم تبين انفكاك علاقته بالقضية الماثلة؛ لاختلاف موضوع الشراكة، ومحله وزمنه. ⏎  ⏎ (لذلك) ⏎ حكمت الدائرة: بثبوت شراكة المدعي/ (...) (...) الجنسية إقامة رقم (...) في فرع محل (...) ورقم سجل التجاري (...) وتأريخ ٢٣/١١/١٣٩٨هــ، الواقع في (...) بمنطقة (...)؛ اعتباراً من ١/٧/١٣٩٨هـ وحتى تأريخ ١٣/٧/١٤٣٠هــ، وإلزام الطرفين بمقتضى ذلك؛ لما هو موضح بالأسباب، وبالله التوفيق وصلى الله وسلم على نبينا محمد وعلى آله وصحبه وسلم. ⏎  ⏎

===========================================================================
JUDGMENT 7
Judgment number: 4430241900
Case number: 4430241900
Date: 1444-04-07
Court name: المحكمة التجارية
Degree indicators: استئناف | ابتدائي - مؤشر صريح
Dispute indicators: شراكات

--- BEGINNING OF CASE TEXT ---
الحمدلله والصلاة والسلام على رسول الله أما بعد: ⏎ فلدى الدائرة التجارية الثانية وبناء على القضية رقم 439156194 لعام 1444ه ⏎ المدعي: ⏎ شركة [Person Name] المدعى عليه: ⏎ [Person Name] ⏎  ⏎ الوقائع: ⏎ تتحصل وقائع هذه الدعوى بالقدر اللازم لإصدار هذا الحكم بتقدم وكيل المدعية/سيف بن يوسف السيف، ذو الهوية الوطنية رقم (...) بموجب الوكالة رقم (424065224) بصحيفة دعوى يختصم فيها [Person Name] [Person Name]: أولاً/أن [Person Name] [Person Name]ًا لشركة [Person Name]، حتى صدر حكم نهائي بتاريخ 17/08/1442ه من الدائرة التجارية الثانية بمحكمة الاستئناف في المنطقة الشرقية يقضي بعزل [Person Name] [Person Name] عدة من المدعى عليه، ثانيًا/خلال الفترة من عام 2016م وإلى شهر (6) من عام 2021م، [Person Name] الفقرة (د) من المـادة (169) من نظام الشركات، والتي نصت على أن مكافأة مديري الشركة [Person Name] للشركاء، إذ أنه حدد مكافأته كمدير للشركة [Person Name]، وبمبالغ كبيرة جدًا، مما يعني أن جميع الرواتب المستلمة من قبل [Person Name] [Person Name] وجه حق، ثالثًا/بموجب ملف أجور الشركة [Person Name] البنكي واسم صاحب الحساب والمبلغ المحول له كأجر، فإن إجمالي المبالغ المحولة للمدعى عليه بصفته مديرًا للشركة [Person Name] (3.450.000) ثلاثة ملايين وأربعمائة وخمسون ألف ريالاً، مفصلة على النحو الآتي: أولاً/المكافآت عن

--- END OF CASE TEXT ---
 حسب دعوى المدعي[Person Name] التي أشار لها [Person Name] [Person Name]؛ كونها نزاع آخر، وأما ما يتعلق بأتعاب الخبرة وحيث تكبدت المدعي[Person Name] (17.250) ريال، وحيث تبين خسران [Person Name] للدعوى؛ مما تمضي معه الدائرة في [Person Name] [Person Name]، بحسبان ما هو مقرر فقهاً وقضاءً من الاعتداد بمصاريف الدعوى، وإلزام من أحوج خصمه في الشكاية بما تكبده جرّاء ذلك، بموجب ما نصت عليه المادة (128) من نظام المرافعات الشرعية، ⏎  ⏎ نص الحكم: ⏎ حكمت الدائرة: أولاً: بإلزام ناصر بن عبدالله بن فالح الدوسري، هوية وطنية رقم (...) ، بأن يدفع لشركة [Person Name]، مبلغاً وقدره (3.550.000) ريال، ثلاثة ملايين وخمسمائة وخمسون ألف ريال. ثانياً: إلزام ناصر بن عبدالله بن فالح الدوسري، هوية وطنية رقم (...)، بأن يدفع لشركة [Person Name]، مبلغاً وقدره (17.250) ريال، سبعة عشر ألف ومئتان وخمسون ريال، والله الموفق. ⏎

===========================================================================
JUDGMENT 8
Judgment number: 4430656264
Case number: 4430656264
Date: 1444-06-08
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: غير مصنف

--- BEGINNING OF CASE TEXT ---
الحمدلله والصلاة والسلام على رسول الله أما بعد: ⏎ فلدى الدائرة الخامسة وبناء على القضية رقم 439444107 لعام 1443هـ ⏎  ⏎ المدعي: ⏎ شركة [Person Name] (شركة [Person Name]) ⏎ المدعى عليه: ⏎ شركة [Person Name] ⏎  ⏎ الوقائع: ⏎ تتلـخص وقائع هذه الدعوى بالقدر اللازم للفصل فيها أن المدعي [Person Name]. وبعد قيد الدعوى وإحالتها للدائرة، نظرتها الدائرة على النحو المثبت في محاضرها، ففي جلسة 23/ 11 / 1443هـ المنعقدة مرئياً عن بعد؛ حضر المدعي [Person Name] يمثل المدعى عليها، وبسؤال المدعي [Person Name]، عليه أجلت الجلسة. ثم عقدت الدائرة جلسة مرافعة عن بعد في تاريخ 05-01-1444 هـ وفيها: حضر وكيل [Person Name] شكلي نلتمس من عدالة المحكمة إحالة الدعوى الى الدائرة الثالثة التجارية وذلك لسابق وجود دعوى رقم 42822512 وتاريخ 08/10/ 1442هـ مرتبطة بين طرفي هذه الدعوى عن موضوع مؤثرة في الدعوى الماثلة أمامكم الموضوع بموجب عقدي تمويل حررا بتاريخ 05/18/ 2015م وتاريخ 12/19/ 2017 م تم الاتفاق بين المدعي [Person Name]: أولاً بموجب عقد التمويل الأول المحرر في 05/18/ 2015م ومدته خمس سنوات تم الاتفاق بين الطرفين على أن يتم التمويل من قبل المدعى عليه[Person Name] المواد ومن ثم تشغيل المصنع ومشاركة المدعى عليه[Person Name] عدلت عن ذلك وقامت فعلياً بتكليف أسامة احمد أحمد ضبعان باستلام مصنع المدعي [Person Name] المدعى ا

--- END OF CASE TEXT ---
ي أقامتها المدعي[Person Name] في حقيتها ذات الدعوى التي فصل فيها في الحكم الإبتدائي المشار إليه وحكمت كذلك محكمة الإستئناف في الحكم المشار إليه في هذه الأسباب بإلغاء الحكم الإبتدائي المتضمن لذات الطلبات التي يطلبها المدعي [Person Name]، ولما كانت الأحكام النهائية لها الحجية في حسم المنازعات والفصل في الخصومات المقضي فيها، ولا يجوز الطعن فيها بالطرق العادية فضلاً عن إقامة دعاوى جديدة فيها، وإنما يقتصر حق المحكوم عليه بها في الاعتراض غير العادي بالتماس إعادة النظر في تلك الأحكام متى توفرت أسباب تقديم الالتماس ولما كان المدعي [Person Name] هذا الشأن فإن النظر في دعواه الماثلة غير جائز. لذلك فإنّ الدائرة تنتهي إلى الحكم في الدعوى، وتقضي بالنحو الوارد في منطوقه. ⏎  ⏎ نص الحكم: ⏎ حكمت الدائرة بعدم جواز نظر هذه الدعوى؛ لما هو موضّح بالأسباب، وصلى الله وسلم على نبينا محمد وعلى آله وصحبه أجمعين. ⏎

===========================================================================
JUDGMENT 9
Judgment number: 4430224539
Case number: 4430224539
Date: 1444-04-13
Court name: المحكمة التجارية
Degree indicators: استئناف
Dispute indicators: مقاولات وإنشاءات

--- BEGINNING OF CASE TEXT ---
الحمدلله والصلاة والسلام على رسول الله أما بعد: ⏎ فلدى الدائرة التجارية الثالثة وبناء على القضية رقم 439025036 لعام 1443هـ ⏎  ⏎ المدعي: ⏎ شركة (...) ⏎ المدعى عليه: ⏎ شركة (...) ⏎  ⏎ الوقائع: ⏎ تتحصل وقائع هذه القضية بالقدر اللازم لإصدار هذا الحكم في أنه تقدم وكيل [Person Name] المدعى عليه[Person Name] مع المدعى عليه[Person Name] موكلته بالتنازل عن تنفيذ مشروع (...) لبعض المرافق ب(...) بموجب المنافسة رقم (...) للمدعى عليها، وقيمة المشروع حسب المستخلصات المصروفة للمدعى عليها ستون مليون ريال، وقد اتفقت موكلته مع المدعى عليه[Person Name] المشروع بقيمة ثمانية وأربعين مليون ريال، لموكلته منها ستة ملايين ريال، وأي مبالغ تدفع زيادة على ذلك فيكون من نصيب موكلته، وأن موكلته مستحقة لمبلغ قدره ثمانية عشر مليون ريال، سدد منها ستة ملايين ريال من الثمانية وأربعين مليون ريال، وماطلت المدعى عليه[Person Name] المتكررة، وطلب الحكم لموكلته بإلزام المدعى عليه[Person Name] قدره اثنا عشر مليون ريال، وإلزامها بدفع أتعاب المحاماة بمبلغ قدره مليون ومئتي ألف ريال وبعد قيد الدعوى وإحالتها للدائرة باشرت نظرها على النحو المبين في محاضر الضبط، حيث حضرت وكيل[Person Name] (...) بموجب الوكالة رقم (...) كما حضر وكيل [Person Name] (...) بموجب الوكالة رقم (...) وبعد تحقق الدائرة من شروط الدعوى عرضت الصلح على الطرفين ف


In [12]:

import pandas as pd
import re
import os

# ==========================================
# 1. تجهيز البيانات
# ==========================================

data = df_clean.copy()

def normalize(text):
    text = str(text) if pd.notna(text) else ""
    text = text.replace("⏎", "\n")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

for col in ["case_text", "EVENTS", "REASONING", "RULING"]:
    if col not in data.columns:
        data[col] = ""
    data[col] = data[col].apply(normalize)

# ==========================================
# 2. تصنيف درجة التقاضي
# ==========================================

def classify_degree(row):
    text = row["case_text"]
    header = text[:2500]

    explicit_patterns = {
        "عليا": [
            r"الحكم\s+الصادر\s+من\s+المحكمة\s+العليا",
            r"المحكمة\s+العليا",
            r"الدائرة\s+بالمحكمة\s+العليا"
        ],
        "استئناف": [
            r"الحكم\s+الاستئنافي",
            r"الصك\s+الاستئنافي",
            r"محكمة\s+الاستئناف",
            r"الدائرة\s+الاستئنافية",
            r"المحكمة\s+التجارية\s+الاستئنافية"
        ],
        "ابتدائي": [
            r"الحكم\s+الابتدائي",
            r"الصك\s+الابتدائي",
            r"المحكمة\s+الابتدائية",
            r"الدائرة\s+الابتدائية"
        ]
    }

    found = []

    for degree, patterns in explicit_patterns.items():
        if any(re.search(p, header) for p in patterns):
            found.append(degree)

    if len(found) == 1:
        return found[0], "مؤشر صريح في بداية الحكم"

    if len(found) > 1:
        return "متعارض - يحتاج مراجعة", "أكثر من مؤشر في بداية الحكم"

    full_patterns = {
        "عليا": r"المحكمة العليا",
        "استئناف": r"محكمة الاستئناف|الدائرة الاستئنافية|الحكم المستأنف",
        "ابتدائي": r"الحكم الابتدائي|الصك الابتدائي|المحكمة الابتدائية"
    }

    possible = [
        degree for degree, pattern in full_patterns.items()
        if re.search(pattern, text)
    ]

    if possible:
        return "غير محدد", "ذكر درجة أخرى داخل النص - لا يثبت درجة الحكم الحالي"

    return "غير محدد", "لا يوجد مؤشر كافٍ"


degree_results = data.apply(classify_degree, axis=1)
data["degree"] = [x[0] for x in degree_results]
data["degree_evidence"] = [x[1] for x in degree_results]

# ==========================================
# 3. تصنيف نوع النزاع
# ==========================================

dispute_patterns = {
    "توريد": [
        r"عقد التوريد", r"توريد البضائع", r"المواد الموردة",
        r"المورد", r"المشتريات والتوريد"
    ],
    "مقاولات وإنشاءات": [
        r"عقد المقاولة", r"أعمال المقاولات", r"المقاولات",
        r"المشروع الإنشائي", r"تنفيذ المشروع"
    ],
    "شراكات": [
        r"عقد الشراكة", r"الشريك", r"الشركاء",
        r"حصص الشركة", r"تصفية الشركة", r"الشراكة"
    ],
    "مطالبات مالية وديون": [
        r"المطالبة المالية", r"المبلغ المستحق",
        r"المستحقات المالية", r"سداد المبلغ",
        r"الدين المستحق", r"المطالبة بمبلغ"
    ],
    "أوراق تجارية": [
        r"الشيك", r"الكمبيالة", r"السند لأمر",
        r"الأوراق التجارية"
    ],
    "إيجار تجاري": [
        r"عقد الإيجار", r"الأجرة", r"الأجرة المستحقة",
        r"المؤجر", r"المستأجر"
    ],
    "ملكية فكرية": [
        r"الملكية الفكرية", r"العلامة التجارية",
        r"حقوق الملكية", r"حقوق المؤلف", r"براءة الاختراع"
    ],
    "إفلاس": [
        r"الإفلاس", r"إجراء التصفية", r"إعادة التنظيم المالي",
        r"أمين الإفلاس"
    ],
    "نقل وشحن": [
        r"عقد النقل", r"الشحن", r"النقل البحري",
        r"النقل البري", r"بضائع مشحونة"
    ],
    "وكالات تجارية": [
        r"الوكالة التجارية", r"الوكيل التجاري",
        r"عقد الوكالة", r"الوكالات التجارية"
    ]
}

def classify_dispute(row):
    text = row["EVENTS"] + " " + row["REASONING"]
    found = []

    for category, patterns in dispute_patterns.items():
        if any(re.search(p, text) for p in patterns):
            found.append(category)

    return found if found else ["غير مصنف"]


data["dispute_types"] = data.apply(classify_dispute, axis=1)
data["primary_dispute_candidate"] = data["dispute_types"].apply(
    lambda x: x[0] if len(x) == 1 else (
        "متعدد - يحتاج تحديد" if "غير مصنف" not in x else "غير مصنف"
    )
)

# ==========================================
# 4. استخراج نتيجة الحكم
# ==========================================

outcome_patterns = [
    ("عدم جواز نظر الدعوى", r"عدم جواز نظر هذه الدعوى|عدم جواز نظر الدعوى"),
    ("عدم قبول الدعوى", r"عدم قبول الدعوى|عدم قبول هذه الدعوى"),
    ("رفض الدعوى", r"رفض الدعوى|رفض هذه الدعوى"),
    ("إلزام", r"حكمت الدائرة.*?بإلزام|إلزام المدعى عليه|إلزام المدعى عليها"),
    ("ثبوت حق أو شراكة", r"ثبوت شراكة|ثبوت ملكية|ثبوت استحقاق"),
    ("فسخ أو إنهاء", r"فسخ العقد|فسخ الاتفاق|إنهاء العقد"),
    ("حل وتصفية", r"بحل وتصفية|تصفية الشركة"),
    ("تعويض", r"الحكم بالتعويض|إلزام.*?بالتعويض"),
    ("شطب الدعوى", r"شطب الدعوى|قررت الدائرة شطب"),
    ("صلح", r"إثبات الصلح|محضر الصلح|انتهى الطرفان إلى الصلح")
]

def extract_outcome(row):
    text = row["case_text"]
    ruling = row["RULING"]

    # نفضّل الجزء الأخير من الحكم الذي يحتوي منطوقه
    headings = [
        "منطوق الحكم", "نص الحكم", "لذلك", "فلهذه الأسباب",
        "فلهذا", "لهذه الأسباب"
    ]

    positions = [text.rfind(h) for h in headings]
    last_position = max(positions)

    if last_position >= 0:
        relevant = text[last_position:]
    elif len(ruling) >= 30:
        relevant = ruling
    else:
        relevant = text[-1500:]

    found = [
        label for label, pattern in outcome_patterns
        if re.search(pattern, relevant)
    ]

    if found:
        return " | ".join(found), relevant[:700]

    return "غير محدد", relevant[:700]


outcome_results = data.apply(extract_outcome, axis=1)
data["outcome"] = [x[0] for x in outcome_results]
data["outcome_evidence"] = [x[1] for x in outcome_results]

# ==========================================
# 5. استخراج المواد والأنظمة القانونية
# ==========================================

def extract_legal_references(text):
    results = []

    patterns = [
        r"(?:المادة|مادة)\s*(?:رقم\s*)?\(?\s*[\d٠-٩]+\s*\)?",
        r"نظام\s+[ء-ي\s]{2,70}",
        r"اللائحة\s+التنفيذية\s+[ء-ي\s]{2,70}"
    ]

    for pattern in patterns:
        matches = re.findall(pattern, text)
        results.extend(matches)

    cleaned = []
    for item in results:
        item = re.sub(r"\s+", " ", item).strip(" .،؛:")
        if item and item not in cleaned:
            cleaned.append(item)

    return cleaned


data["legal_references"] = data["case_text"].apply(
    extract_legal_references
)

# استخراج سياق كل إشارة قانونية لمراجعتها
def legal_contexts(text):
    contexts = []
    pattern = r"(?:المادة|مادة|نظام|اللائحة التنفيذية)"

    for match in re.finditer(pattern, text):
        start = max(0, match.start() - 100)
        end = min(len(text), match.end() + 160)
        contexts.append(text[start:end])

    return list(dict.fromkeys(contexts))


data["legal_evidence"] = data["case_text"].apply(legal_contexts)

# ==========================================
# 6. إحصائيات شاملة
# ==========================================

print("\n" + "="*65)
print("ESNAD - FINAL DATA AUDIT")
print("="*65)

print("\nDATASET")
print("Total judgments:", len(data))
print("Unique source URLs:", data["details_url"].nunique())

print("\nDEGREE CLASSIFICATION")
print(data["degree"].value_counts(dropna=False).to_string())

print("\nDEGREE EVIDENCE")
print(data["degree_evidence"].value_counts(dropna=False).to_string())

print("\nDISPUTE CLASSIFICATION")
dispute_counts = (
    data["dispute_types"]
    .explode()
    .value_counts()
)
print(dispute_counts.to_string())

print("\nOUTCOME CLASSIFICATION")
print(data["outcome"].value_counts(dropna=False).to_string())

print("\nLEGAL REFERENCES")
print("Judgments with legal references:",
      (data["legal_references"].str.len() > 0).sum())
print("Total extracted references:",
      data["legal_references"].str.len().sum())

# ==========================================
# 7. عينات للمراجعة النهائية
# ==========================================

print("\n" + "="*65)
print("SAMPLE RESULTS")
print("="*65)

sample = data.sample(min(15, len(data)), random_state=42)

for i, (_, row) in enumerate(sample.iterrows(), 1):
    print(f"\n--- SAMPLE {i} ---")
    print("Judgment:", row["judgment_number"])
    print("Degree:", row["degree"])
    print("Degree evidence:", row["degree_evidence"])
    print("Dispute:", row["dispute_types"])
    print("Outcome:", row["outcome"])
    print("Legal references:", row["legal_references"][:10])
    print("Outcome evidence:", row["outcome_evidence"][:350])

# ==========================================
# 8. حفظ المخرجات
# ==========================================

export = data.copy()

for col in ["dispute_types", "legal_references", "legal_evidence"]:
    export[col] = export[col].apply(
        lambda x: " || ".join(x) if isinstance(x, list) else x
    )

csv_path = "/content/esnad_arabiccr_enriched.csv"
export.to_csv(csv_path, index=False, encoding="utf-8-sig")

summary_path = "/content/esnad_final_audit.txt"

with open(summary_path, "w", encoding="utf-8") as f:
    f.write("ESNAD - FINAL AUDIT\n")
    f.write("="*50 + "\n\n")
    f.write(f"Total judgments: {len(data)}\n")
    f.write(f"Unique URLs: {data['details_url'].nunique()}\n\n")

    for title, series in [
        ("DEGREE", data["degree"].value_counts()),
        ("DEGREE EVIDENCE", data["degree_evidence"].value_counts()),
        ("DISPUTES", dispute_counts),
        ("OUTCOMES", data["outcome"].value_counts())
    ]:
        f.write(f"\n{title}\n")
        f.write(series.to_string())
        f.write("\n")

    f.write("\n\nLEGAL REFERENCES\n")
    f.write(
        f"Judgments with references: "
        f"{(data['legal_references'].str.len() > 0).sum()}\n"
    )
    f.write(
        f"Total references: {data['legal_references'].str.len().sum()}\n"
    )

print("\n" + "="*65)
print("FILES SAVED")
print(csv_path)
print(summary_path)
print("="*65)

=================================================================
ESNAD - FINAL DATA AUDIT
=================================================================

DATASET
Total judgments: 12477
Unique source URLs: 12477

DEGREE CLASSIFICATION
degree
غير محدد                 11631
استئناف                    660
متعارض - يحتاج مراجعة       66
ابتدائي                     60
عليا                        60

DEGREE EVIDENCE
degree_evidence
لا يوجد مؤشر كافٍ                                      10695
ذكر درجة أخرى داخل النص - لا يثبت درجة الحكم الحالي      936
مؤشر صريح في بداية الحكم                                 780
أكثر من مؤشر في بداية الحكم                               66

DISPUTE CLASSIFICATION
dispute_types
غير مصنف               4969
شراكات                 3023
مطالبات مالية وديون    2014
أوراق تجارية           1824
مقاولات وإنشاءات       1143
إيجار تجاري             912
توريد                   832
ملكية فكرية             301
إفلاس                   292
نقل وشحن                261
وكالات تجارية           120

OUTCOME CLASSIFICATION
outcome
إلزام                                                         4438
غير محدد                                                      4054
رفض الدعوى                                                    2622
عدم قبول الدعوى                                                909
عدم جواز نظر الدعوى                                            215
فسخ أو إنهاء                                                    90
إلزام | فسخ أو إنهاء                                            39
ثبوت حق أو شراكة                                                38
عدم قبول الدعوى | إلزام                                         14
رفض الدعوى | إلزام                                              14
حل وتصفية                                                       12
إلزام | تعويض                                                    4
عدم قبول الدعوى | رفض الدعوى                                     3
إلزام | ثبوت حق أو شراكة                                         3
صلح                                                              3
رفض الدعوى | ثبوت حق أو شراكة                                    2
رفض الدعوى | صلح                                                 2
إلزام | شطب الدعوى                                               2
إلزام | حل وتصفية                                                2
عدم جواز نظر الدعوى | عدم قبول الدعوى                            2
رفض الدعوى | تعويض                                               1
رفض الدعوى | حل وتصفية                                           1
رفض الدعوى | إلزام | شطب الدعوى                                  1
عدم جواز نظر الدعوى | عدم قبول الدعوى | رفض الدعوى | إلزام       1
عدم قبول الدعوى | رفض الدعوى | حل وتصفية                         1
إلزام | تعويض | شطب الدعوى                                       1
عدم قبول الدعوى | ثبوت حق أو شراكة                               1
عدم جواز نظر الدعوى | إلزام                                      1
عدم قبول الدعوى | رفض الدعوى | فسخ أو إنهاء                      1

LEGAL REFERENCES
Judgments with legal references: 10188
Total extracted references: 49751

=================================================================
SAMPLE RESULTS
=================================================================

--- SAMPLE 1 ---
Judgment: 4530236058
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['مطالبات مالية وديون']
Outcome: إلزام
Legal references: []
Outcome evidence: نص الحكم: حكمت الدائرة بإلزام [Person Name] (...) هوية وطنية رقم (...) صاحب مؤسسة (...) للمقاولات العامة ذات السجل التجاري رقم (...) بأن يدفع للمدعي[Person Name] (...) الصناعية ذات السجل التجاري رقم (...) مبلغا وقدره 493.278 ريال، والله الموفق.

--- SAMPLE 2 ---
Judgment: 1155
Degree: غير محدد
Degree evidence: ذكر درجة أخرى داخل النص - لا يثبت درجة الحكم الحالي
Dispute: ['غير مصنف']
Outcome: رفض الدعوى
Legal references: ['مادة (36)', 'نظام الإطفاء والرش بمبلغ قدره', 'نظام المرافعات الشرعية', 'نظام المحاكم التجارية قد نصت على الآتي']
Outcome evidence: منطوق الحكم) حكمت الدائرة برفض الدعوى. وﷲ الموفق، وصلى ﷲ على نبينا محمد وعلى آله وصحبه أجمعين. عضو [Person Name] عضو [Person Name] رئيس الدائرة [Person Name]

--- SAMPLE 3 ---
Judgment: 4430238822
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['غير مصنف']
Outcome: غير محدد
Legal references: ['المادة (16)', 'نظام المحاكم التجارية']
Outcome evidence: نص الحكم: حكمت الدائرة: بالزام/ [Person Name] رخصة إقامة رقم: (...) بأن يدفع لـ/ اشرف احمد الطيار رخصة إقامة رقم: (...) مبلغ وقدره (67500) سبعة وستون ألفاً وخمسمئة ريال.

--- SAMPLE 4 ---
Judgment: 4430809287
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['مطالبات مالية وديون', 'نقل وشحن']
Outcome: غير محدد
Legal references: ['المادة رقم (٩٠)', 'المادة رقم (٣٠', 'المادة رقم (٢١)', 'نظام المحاكم التجارية فقد جرى سؤال المدعي', 'نظام الشركات الصادر بالمرسوم الملكي رقم م', 'نظام المحاكم التجارية', 'نظام الإثبات', 'اللائحة التنفيذية لنظام المحاكم التجارية فقد جرى سؤال المدعي']
Outcome evidence: نص الحكم: حكمت الدائرة: [Person Name] (...)سجل تجاري رقم (...) أن تدفع لـ شركة (...)(...)الجنسية - سجل تجاري رقم (...) مبلغا قدره (١,٣٣١,٢٥٠) مليون وثلاثمائة وواحد وثلاثون ألفًا ومئتان وخمسون ريالاً فقط؛ لما هو موضح بالأسباب. وبالله التوفيق.

--- SAMPLE 5 ---
Judgment: 4430754413
Degree: غير محدد
Degree evidence: ذكر درجة أخرى داخل النص - لا يثبت درجة الحكم الحالي
Dispute: ['إيجار تجاري']
Outcome: رفض الدعوى
Legal references: ['المادة (110', 'نظام في تبادل المذكرات', 'نظام الإجارة', 'نظام الإيجار مع الوعد بالتملك ويرجو من الدائرة سؤال المدعى عن مصير تلك السي', 'نظام الإيجار المنتهي بالتملك خاضعا', 'نظام الإيجار المنتهي بالتملك وتم سداد مبلغ', 'نظام الإثبات ونصه']
Outcome evidence: نص الحكم: حكمت الدائرة: برفض الدعوى المقامة من شركة (...) للسيارات المحدودة ضد (...) لما هو موضح بالأسباب.

--- SAMPLE 6 ---
Judgment: 783/1/ق
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['غير مصنف']
Outcome: غير محدد
Legal references: ['نظام المحاسبي لموكلته', 'نظام المرافعات الشرعية']
Outcome evidence: لذلك) حكمت الدائرة: [Person Name] (...) للمقاولات سجل تجاري رقم (...) أن تدفع لشركة (...) سجل تجاري رقم (...) مبلغاً قدره (٢,١٥٩,٥٥١) مليونين ومائة وتسعة وخمسون ألفاً وخمسمائة وواحد وخمسون ريالاً. والله الموفق وصلى الله وسلم على نبينا محمد وعلى آله وصحبه أجمعين.

--- SAMPLE 7 ---
Judgment: 2292/1/ق
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['مقاولات وإنشاءات', 'شراكات', 'أوراق تجارية']
Outcome: عدم قبول الدعوى | رفض الدعوى
Legal references: []
Outcome evidence: لذلك) حكمت الدائرة بما يلي: أولا: إلزام (...) سجل مدني رقم (...) بأن يدفع لــ (...) سجل مدني رقم (...) مبلغًا قدره (16.000.000) ستة عشر مليونا ريال. ثانيا: رفض هذه الدعوى في مواجهة (...) سجل مدني رقم (...). ثالثا: عدم قبول هذه الدعوى في مواجهة (...) إقامة رقم (...) وبالله التوفيق، وصلى الله على نبينا محمد وعلى آله وصحبه وسلم. أمين السر (...) عضو (.

--- SAMPLE 8 ---
Judgment: 4430503399
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['إيجار تجاري']
Outcome: إلزام
Legal references: ['المادة (١٢)', 'مادة (١٦)', 'نظام نطلب', 'نظام ونصه', 'نظام ونصها', 'نظام المحاكم التجارية', 'نظام التعاملات الإلكترونية أو نظام التجارة الإلكترونية', 'نظام فأهمته الدائرة لن يتم النظر سوى ما هو مرفق في النظام ونصه إلزام المدعى']
Outcome evidence: نص الحكم: حكمت الدائرة: بإلزام المدعى عليها/مركز(...) السيارات سجل تجاري رقم (...) بأن تدفع للمدعي/(...) هوية وطنية: (...) مبلغا قدره (٢٣٠,٠٠٠) مئتان وثلاثون ألف ريال سعودي لما هو موضح بالأسباب بالله التوفيق.

--- SAMPLE 9 ---
Judgment: 4089
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['شراكات']
Outcome: إلزام
Legal references: ['المادة (35)', 'المادة (128)', 'نظام المرافعات الشرعية الصادر بالمرسوم الملكي رقم', 'نظام المرافعات الشرعية نصت على أن']
Outcome evidence: لذلك) حكمت الدائرة بإلزام (...) هوية رقم (...) صاحب [Person Name] (...) التجارية سجل تجاري رقم (...) بأن يدفع لـ (...) هوية رقم (...) صاحب [Person Name] (...) للتجارة سجل تجاري رقم (...) ما يلي: أولا: مبلغا قدره (281.914) مئتان و واحد وثمانون ألفا وتسعمائة وأربعة عشر ألف ريال، ثانيا: مبلغا قدره (21.000) واحد وعشرون ألف ريال مقابل أتعاب الخبير. أمين

--- SAMPLE 10 ---
Judgment: 4056
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['شراكات']
Outcome: غير محدد
Legal references: ['المادة (9)', 'المادة (11)', 'المادة (10)', 'المادة (50', 'المادة (30)', 'نظام التحكيم السعودي', 'نظام التحكيم عليه فإن رد موكلتي عما سبق يتلخص في الآتي', 'نظام التحكيم والتي نصت على أنه', 'نظام التحكيم', 'نظام الذي يحكم أهليته']
Outcome evidence: منطوق الحكم) حكمت الدائرة بعد جواز النظر بالدعوى؛ لوجود شرط التحكيم؛ لما هو مبين بالاسباب، وبﷲ التوفيق. رئيس الدائرة [Person Name]

--- SAMPLE 11 ---
Judgment: 1354
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['غير مصنف']
Outcome: غير محدد
Legal references: ['مادة (16)', 'المادة رقم (42)', 'نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم', 'نظام المحاكم التجارية']
Outcome evidence: منطوق الحكم) حكمت الدائرة [Person Name] (...) للمقاولات شركة [Person Name]: (...) أن تدفع لشركة (...) للمقاولات شركة [Person Name]: (...) مبلغاً قدره (1.181.922) مليون ومائة وواحد وثمانون ألفاً وتسعمائة واثنان وعشرون ريال. وبالله التوفيق.

--- SAMPLE 12 ---
Judgment: 2766
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['شراكات']
Outcome: غير محدد
Legal references: ['المادة 16', 'نظام المحكمة التجارية']
Outcome evidence: منطوق الحكم) حكمت الدائرة بالزام [Person Name] / بندر صنيتان الحربي سجل مدني رقم: (...) بأن يدفع للمدعي / [Person Name] سجل مدني رقم: (...) مبلغا قدره (35.500.000) خمسه وثلاثون مليون وخمسمائة ألف ريال ، وبﷲ التوفيق. عضو [Person Name] عضو [Person Name] رئيس الدائرة [Person Name]

--- SAMPLE 13 ---
Judgment: 8146
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['غير مصنف']
Outcome: غير محدد
Legal references: ['المادة 57', 'نظام المرافعات الشرعية الصادر بالمرسوم الملكي رقم م']
Outcome evidence: منطوق الحكم) بإلزام (...) هوية وطنية رقم: (...) بــــأن يدفع لـــــ (...) هوية وطنية رقم: (...) مبلغا وقدره 200.000ريال، مئتا ألف ريال . وﷲ الموفق، وصلى ﷲ وسلم على نبينا محمد وعلى آله وصحبه أجمعين. عضو [Person Name] عضو [Person Name] رئيس الدائرة [Person Name]

--- SAMPLE 14 ---
Judgment: 5152
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['غير مصنف']
Outcome: إلزام
Legal references: []
Outcome evidence: لذلك) حكمت الدائرة بإلزام/ شركة (...) (مساهمة مقفلة) -سجل تجاري رقم (...)- بأن تدفع لـ/ مؤسسة (...) للمقاولات -سجل تجاري رقم (...)- مبلغا وقدره (٣٦٣.٧٢٠) ثلاثمائة وثلاثة وستون ألفا وسبعمائة وعشرون ريالا، يضاف عليها قيمة أتعاب الخبير وقدرها (١٠.٠٠٠) ويضاف إليها قيمة أتعاب الترافع وقدرها (٢٠.٠٠٠) عشرون ألف ريال؛ وذلك لما هو موضح بالأسباب.

--- SAMPLE 15 ---
Judgment: 6422
Degree: غير محدد
Degree evidence: لا يوجد مؤشر كافٍ
Dispute: ['شراكات']
Outcome: إلزام
Legal references: ['نظام الشركات في مادته الثالثة والسبعين بعد المئة', 'نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم', 'نظام الشركات']
Outcome evidence: منطوق الحكم) حكمت الدائرة: بإلزام (...) سجل مدني رقم (...) بصفته مدير شركة (...) للمقاولات العامة والتجارة المحدودة سجل تجاري رقم (...) بتمكين ورثة (...) الشركاء في الشركة [Person Name] المتعلقة بفرع الشركة [Person Name] (...). وﷲ الموفق، وصلى ﷲ على نبينا محمد وعلى آله وصحبه وسلم،،، عضو [Person Name] عضو [Person Name] رئيس الدائرة [Person Name]

=================================================================
FILES SAVED
/content/esnad_arabiccr_enriched.csv
/content/esnad_final_audit.txt
=================================================================

In [13]:

import re
import json
import pandas as pd
import numpy as np
from collections import Counter

# ============================================================
# ESNAD - IMPROVED OUTCOME + LEGAL REFERENCES EXTRACTION
# Requires: df_clean
# Does NOT rebuild embeddings or FAISS
# ============================================================

if "df_clean" not in globals():
    raise NameError("لم أجد df_clean. شغّلي الخلية في جلسة Colab التي تحتوي على بيانات ArabiCCR.")

data = df_clean.copy()

required = ["case_text", "EVENTS", "REASONING", "RULING"]
missing = [c for c in required if c not in data.columns]
if missing:
    raise ValueError(f"أعمدة ناقصة في البيانات: {missing}")

# ----------------------------
# 1. Arabic text normalization
# ----------------------------

def normalize_ar(text):
    if text is None or (isinstance(text, float) and pd.isna(text)):
        return ""

    text = str(text)
    text = re.sub(r"[\u064B-\u065F\u0670\u0640]", "", text)
    text = re.sub(r"[أإآٱ]", "ا", text)
    text = text.replace("ى", "ي")
    text = text.replace("ؤ", "و").replace("ئ", "ي")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def western_digits(text):
    table = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")
    return text.translate(table)


# ---------------------------------
# 2. Extract the operative ruling
# ---------------------------------

RULING_HEADINGS = [
    r"منطوق الحكم",
    r"نص الحكم",
    r"لذلك\s*حكمت",
    r"لهذه الأسباب",
    r"لهذه الاسباب",
    r"حكمت الدائرة",
    r"حكمت المحكمة",
    r"قررت الدائرة",
    r"قضت الدائرة",
]

HEADING_RE = re.compile(
    "|".join(RULING_HEADINGS),
    flags=re.IGNORECASE
)

def get_ruling_candidate(row):
    ruling_col = normalize_ar(row.get("RULING", ""))
    case_text = normalize_ar(row.get("case_text", ""))

    candidates = []

    # RULING is a dedicated source column, but may contain
    # incomplete or noisy text. Keep it as one candidate.
    if ruling_col:
        candidates.append(("RULING", ruling_col[-5000:]))

    # Find the last explicit ruling heading in the full judgment.
    matches = list(HEADING_RE.finditer(case_text))
    if matches:
        last_match = matches[-1]
        segment = case_text[last_match.start():last_match.start() + 3500]
        candidates.append(("case_text_last_heading", segment))

    # If no heading exists, inspect only the end of the judgment.
    if not candidates and case_text:
        candidates.append(("case_text_end", case_text[-2500:]))

    # Prefer the candidate with the clearest operative language.
    operative_terms = [
        "حكمت", "قضت", "بالزام", "الزام", "رفض الدعوي",
        "رفض الدعوى", "عدم قبول", "عدم جواز", "عدم اختصاص",
        "اثبات الصلح", "فسخ", "شطب"
    ]

    ranked = []
    for source, candidate in candidates:
        score = sum(term in candidate for term in operative_terms)
        ranked.append((score, source, candidate))

    if not ranked:
        return "", "لا يوجد نص للحكم"

    ranked.sort(key=lambda x: x[0], reverse=True)
    score, source, candidate = ranked[0]

    if score == 0:
        return candidate, "نص مرشح دون مؤشرات حكم واضحة"

    return candidate, source


# ---------------------------------
# 3. Multi-label outcome extraction
# ---------------------------------

OUTCOME_PATTERNS = {
    "إلزام": [
        r"بالزام",
        r"الزام\s+(?:المدعى|المدعي عليه|المدعي عليها)",
        r"حكمت.{0,40}بالزام",
        r"قضت.{0,40}بالزام",
        r"الزام.{0,100}(?:بان|بأن)\s+(?:يدفع|تدفع|يسدد|تسدد)",
        r"الزام.{0,100}(?:بتمكين|بتسليم|بإخلاء|باخلاء)",
    ],
    "رفض الدعوى": [
        r"رفض الدعوي",
        r"رفض الدعوى",
        r"برفض الدعوي",
        r"برفض الدعوى",
        r"رد الدعوي",
        r"رد الدعوى",
        r"رفض طلب",
        r"برفض طلب",
    ],
    "عدم قبول الدعوى": [
        r"عدم قبول الدعوي",
        r"عدم قبول الدعوى",
        r"بعدم قبول الدعوي",
        r"بعدم قبول الدعوى",
        r"عدم قبول الطلب",
        r"بعدم قبول الطلب",
    ],
    "عدم جواز نظر الدعوى": [
        r"عدم جواز نظر الدعوي",
        r"عدم جواز نظر الدعوى",
        r"بعدم جواز نظر الدعوي",
        r"بعدم جواز نظر الدعوى",
    ],
    "عدم الاختصاص": [
        r"عدم الاختصاص",
        r"بعدم اختصاص",
        r"عدم اختصاص الدائرة",
        r"عدم اختصاص المحكمة",
    ],
    "فسخ أو إنهاء": [
        r"فسخ العقد",
        r"فسخ الاتفاق",
        r"انهاء العقد",
        r"إنهاء العقد",
        r"بفسخ",
        r"بانهاء",
    ],
    "صلح": [
        r"اثبات الصلح",
        r"إثبات الصلح",
        r"اثبات اتفاق الصلح",
        r"الصلح المبرم",
        r"تصالح الطرفان",
        r"اتفاق الطرفين على الصلح",
    ],
    "شطب الدعوى": [
        r"شطب الدعوي",
        r"شطب الدعوى",
        r"بشطب الدعوي",
        r"بشطب الدعوى",
    ],
    "ثبوت حق أو شراكة": [
        r"ثبوت الشراكه",
        r"ثبوت الشراكة",
        r"ثبوت حق المدعي",
        r"ثبوت استحقاق",
        r"اثبات الشراكه",
        r"اثبات الشراكة",
    ],
    "حل وتصفية": [
        r"حل الشركة",
        r"حل الشركه",
        r"تصفية الشركة",
        r"تصفية الشركه",
        r"حل وتصفية",
    ],
}

def extract_outcomes(text):
    text = normalize_ar(text)
    found = []

    for label, patterns in OUTCOME_PATTERNS.items():
        for pattern in patterns:
            if re.search(pattern, text):
                found.append(label)
                break

    # Avoid counting acceptance as an outcome unless explicitly stated.
    # "عدم قبول الدعوى" is already handled separately.
    return found


def outcome_evidence(text, outcomes, window=220):
    text = normalize_ar(text)
    evidence = {}

    for label in outcomes:
        patterns = OUTCOME_PATTERNS[label]
        snippets = []

        for pattern in patterns:
            for match in re.finditer(pattern, text):
                start = max(0, match.start() - 90)
                end = min(len(text), match.end() + 130)
                snippets.append(text[start:end])

        # Keep up to two short examples for each outcome.
        evidence[label] = snippets[:2]

    return evidence


ruling_results = data.apply(get_ruling_candidate, axis=1)
data["ruling_candidate"] = [x[0] for x in ruling_results]
data["ruling_source"] = [x[1] for x in ruling_results]

data["outcomes_list"] = data["ruling_candidate"].apply(extract_outcomes)
data["outcome_improved"] = data["outcomes_list"].apply(
    lambda x: " | ".join(x) if x else "غير محدد"
)
data["outcome_evidence_improved"] = data.apply(
    lambda row: json.dumps(
        outcome_evidence(row["ruling_candidate"], row["outcomes_list"]),
        ensure_ascii=False
    ),
    axis=1
)

# ---------------------------------
# 4. Legal system name extraction
# ---------------------------------

# Controlled list: only recognize system names explicitly listed here.
# Expand this list later after reviewing the actual dataset.
LEGAL_SYSTEMS = [
    "نظام المحاكم التجارية",
    "اللائحة التنفيذية لنظام المحاكم التجارية",
    "نظام الشركات",
    "نظام الإثبات",
    "نظام الاثبات",
    "نظام التحكيم",
    "نظام الإفلاس",
    "نظام الافلاس",
    "نظام المعاملات المدنية",
    "نظام المرافعات الشرعية",
    "نظام التنفيذ",
    "نظام الأوراق التجارية",
    "نظام الاوراق التجارية",
    "نظام المنافسة",
    "نظام الامتياز التجاري",
    "نظام الوكالات التجارية",
    "نظام العلامات التجارية",
    "نظام حماية حقوق المؤلف",
    "نظام براءات الاختراع",
    "نظام التجارة الإلكترونية",
    "نظام التعاملات الإلكترونية",
    "نظام السجل التجاري",
    "نظام الأسماء التجارية",
    "نظام الاستثمار",
    "نظام العمل",
    "نظام الرهن التجاري",
    "نظام الملكية الفكرية",
    "نظام مكافحة الغش التجاري",
    "نظام مكافحة التستر",
    "نظام ضريبة القيمة المضافة",
]

# Normalize list but retain display form.
LEGAL_SYSTEMS_NORMALIZED = {
    normalize_ar(name): name for name in LEGAL_SYSTEMS
}

def extract_legal_systems(text):
    normalized = normalize_ar(text)
    found = []

    # Longer names first to avoid partial matching.
    names = sorted(
        LEGAL_SYSTEMS_NORMALIZED.keys(),
        key=len,
        reverse=True
    )

    for normalized_name in names:
        if normalized_name in normalized:
            display_name = LEGAL_SYSTEMS_NORMALIZED[normalized_name]
            if display_name not in found:
                found.append(display_name)

    return found


# ---------------------------------
# 5. Legal article number extraction
# ---------------------------------

ARTICLE_PATTERN = re.compile(
    r"(?:المادة|مادة)\s*(?:رقم\s*)?"
    r"[\(\[]?\s*([0-9٠-٩]{1,3})\s*[\)\]]?"
    r"(?:\s*(?:مكرر|المكررة))?",
    flags=re.IGNORECASE
)

def extract_articles(text):
    normalized = normalize_ar(text)
    normalized = western_digits(normalized)

    found = []
    for match in ARTICLE_PATTERN.finditer(normalized):
        number = match.group(1)
        label = f"المادة {number}"
        if label not in found:
            found.append(label)

    return found


# ---------------------------------
# 6. Evidence snippets for references
# ---------------------------------

def get_reference_evidence(text, terms, max_per_term=2):
    text = normalize_ar(text)
    output = {}

    for term in terms:
        snippets = []
        search_term = normalize_ar(term)

        start_pos = 0
        while len(snippets) < max_per_term:
            pos = text.find(search_term, start_pos)
            if pos == -1:
                break

            start = max(0, pos - 100)
            end = min(len(text), pos + len(search_term) + 140)
            snippets.append(text[start:end])
            start_pos = pos + len(search_term)

        output[term] = snippets

    return output


# Use reasoning + full judgment for legal references.
def legal_source_text(row):
    parts = [
        normalize_ar(row.get("REASONING", "")),
        normalize_ar(row.get("case_text", "")),
    ]
    return "\n".join(part for part in parts if part)


data["legal_source_text"] = data.apply(legal_source_text, axis=1)

data["legal_systems"] = data["legal_source_text"].apply(
    extract_legal_systems
)
data["legal_articles"] = data["legal_source_text"].apply(
    extract_articles
)

data["legal_systems_evidence"] = data.apply(
    lambda row: json.dumps(
        get_reference_evidence(
            row["legal_source_text"],
            row["legal_systems"]
        ),
        ensure_ascii=False
    ),
    axis=1
)

data["legal_articles_evidence"] = data.apply(
    lambda row: json.dumps(
        get_reference_evidence(
            row["legal_source_text"],
            row["legal_articles"]
        ),
        ensure_ascii=False
    ),
    axis=1
)

# ---------------------------------
# 7. Summary report
# ---------------------------------

print("=" * 65)
print("ESNAD - IMPROVED OUTCOME & LEGAL REFERENCES AUDIT")
print("=" * 65)

print("\nOUTCOME DISTRIBUTION")
print(data["outcome_improved"].value_counts().to_string())

print("\nOUTCOME COVERAGE")
outcome_found = (data["outcome_improved"] != "غير محدد").sum()
print(f"Judgments with extracted outcome: {outcome_found:,}")
print(f"Judgments without clear outcome: {len(data)-outcome_found:,}")
print(f"Coverage: {outcome_found/len(data)*100:.2f}%")

multi_outcome = data["outcomes_list"].apply(len).gt(1).sum()
print(f"Judgments with multiple outcomes: {multi_outcome:,}")

print("\nLEGAL SYSTEMS")
system_counts = Counter(
    system
    for systems in data["legal_systems"]
    for system in systems
)
for name, count in system_counts.most_common():
    print(f"{name}: {count:,}")

print("\nLEGAL ARTICLES")
article_counts = Counter(
    article
    for articles in data["legal_articles"]
    for article in articles
)
print(f"Unique article labels: {len(article_counts):,}")
print(f"Total article mentions: {sum(article_counts.values()):,}")
for name, count in article_counts.most_common(25):
    print(f"{name}: {count:,}")

systems_covered = data["legal_systems"].apply(bool).sum()
articles_covered = data["legal_articles"].apply(bool).sum()

print("\nLEGAL REFERENCE COVERAGE")
print(f"Judgments with recognized legal systems: {systems_covered:,}")
print(f"Judgments with article numbers: {articles_covered:,}")

# ---------------------------------
# 8. Print review samples
# ---------------------------------

print("\n" + "=" * 65)
print("SAMPLES: MULTIPLE OUTCOMES")
print("=" * 65)

multi_samples = data[data["outcomes_list"].apply(len).gt(1)].head(8)

for _, row in multi_samples.iterrows():
    print("\nJudgment:", row.get("judgment_number"))
    print("Outcomes:", row["outcomes_list"])
    print("Source:", row["ruling_source"])
    print("Evidence:", row["outcome_evidence_improved"][:1000])

print("\n" + "=" * 65)
print("SAMPLES: LEGAL REFERENCES")
print("=" * 65)

legal_samples = data[
    data["legal_systems"].apply(bool)
    | data["legal_articles"].apply(bool)
].head(10)

for _, row in legal_samples.iterrows():
    print("\nJudgment:", row.get("judgment_number"))
    print("Systems:", row["legal_systems"])
    print("Articles:", row["legal_articles"])
    print("System evidence:", row["legal_systems_evidence"][:700])
    print("Article evidence:", row["legal_articles_evidence"][:700])

# ---------------------------------
# 9. Save improved dataset
# ---------------------------------

# Convert list/dict columns to JSON strings for reliable CSV storage.
export = data.copy()

for col in [
    "outcomes_list",
    "legal_systems",
    "legal_articles",
]:
    export[col] = export[col].apply(
        lambda x: json.dumps(x, ensure_ascii=False)
    )

output_csv = "/content/esnad_arabiccr_improved.csv"
output_report = "/content/esnad_improved_extraction_report.txt"

export.to_csv(output_csv, index=False, encoding="utf-8-sig")

with open(output_report, "w", encoding="utf-8") as f:
    f.write("ESNAD IMPROVED EXTRACTION AUDIT\n")
    f.write("=" * 60 + "\n\n")
    f.write("OUTCOME DISTRIBUTION\n")
    f.write(data["outcome_improved"].value_counts().to_string())
    f.write("\n\nLEGAL SYSTEMS\n")
    f.write(pd.Series(dict(system_counts)).to_string())
    f.write("\n\nLEGAL ARTICLES - TOP 50\n")
    f.write(pd.Series(dict(article_counts)).sort_values(
        ascending=False
    ).head(50).to_string())
    f.write("\n\nMULTI-OUTCOME SAMPLES\n")
    for _, row in multi_samples.iterrows():
        f.write(f"\nJudgment: {row.get('judgment_number')}\n")
        f.write(f"Outcomes: {row['outcomes_list']}\n")
        f.write(f"Evidence: {row['outcome_evidence_improved']}\n")

print("\n" + "=" * 65)
print("FILES SAVED")
print(output_csv)
print(output_report)
print("=" * 65)

=================================================================
ESNAD - IMPROVED OUTCOME & LEGAL REFERENCES AUDIT
=================================================================

OUTCOME DISTRIBUTION
outcome_improved
إلزام                                                         5398
غير محدد                                                      3930
رفض الدعوى                                                    1634
عدم الاختصاص                                                   598
عدم قبول الدعوى                                                432
عدم جواز نظر الدعوى                                            118
إلزام | فسخ أو إنهاء                                            99
إلزام | رفض الدعوى                                              75
فسخ أو إنهاء                                                    67
إلزام | عدم قبول الدعوى                                         30
حل وتصفية                                                       18
إلزام | عدم الاختصاص                                             9
رفض الدعوى | فسخ أو إنهاء                                        9
ثبوت حق أو شراكة                                                 8
رفض الدعوى | عدم قبول الدعوى                                     7
إلزام | رفض الدعوى | فسخ أو إنهاء                                5
عدم قبول الدعوى | عدم الاختصاص                                   3
إلزام | حل وتصفية                                                3
إلزام | ثبوت حق أو شراكة                                         3
رفض الدعوى | ثبوت حق أو شراكة                                    3
رفض الدعوى | عدم الاختصاص                                        3
صلح                                                              3
رفض الدعوى | عدم قبول الدعوى | فسخ أو إنهاء                      2
إلزام | رفض الدعوى | عدم قبول الدعوى                             2
رفض الدعوى | صلح                                                 2
إلزام | عدم جواز نظر الدعوى                                      2
عدم قبول الدعوى | عدم جواز نظر الدعوى                            2
إلزام | شطب الدعوى                                               2
عدم قبول الدعوى | عدم جواز نظر الدعوى | عدم الاختصاص             1
إلزام | رفض الدعوى | عدم قبول الدعوى | عدم جواز نظر الدعوى       1
إلزام | رفض الدعوى | شطب الدعوى                                  1
رفض الدعوى | فسخ أو إنهاء | حل وتصفية                            1
إلزام | رفض الدعوى | عدم قبول الدعوى | عدم الاختصاص              1
عدم جواز نظر الدعوى | عدم الاختصاص                               1
عدم قبول الدعوى | ثبوت حق أو شراكة                               1
إلزام | عدم قبول الدعوى | عدم الاختصاص                           1
عدم جواز نظر الدعوى | شطب الدعوى                                 1
رفض الدعوى | عدم الاختصاص | حل وتصفية                            1

OUTCOME COVERAGE
Judgments with extracted outcome: 8,547
Judgments without clear outcome: 3,930
Coverage: 68.50%
Judgments with multiple outcomes: 271

LEGAL SYSTEMS
نظام المرافعات الشرعية: 4,659
نظام المحاكم التجارية: 4,506
اللائحة التنفيذية لنظام المحاكم التجارية: 1,638
نظام الشركات: 1,202
نظام الاثبات: 1,000
نظام الافلاس: 187
نظام التحكيم: 140
نظام التنفيذ: 129
نظام العلامات التجارية: 86
نظام الأسماء التجارية: 80
نظام الاوراق التجارية: 72
نظام حماية حقوق المؤلف: 68
نظام العمل: 61
نظام السجل التجاري: 50
نظام الوكالات التجارية: 24
نظام الاستثمار: 19
نظام براءات الاختراع: 14
نظام التعاملات الإلكترونية: 12
نظام الامتياز التجاري: 10
نظام مكافحة التستر: 8
نظام مكافحة الغش التجاري: 8
نظام المعاملات المدنية: 6
نظام ضريبة القيمة المضافة: 5
نظام المنافسة: 4
نظام التجارة الإلكترونية: 1
نظام الملكية الفكرية: 1

LEGAL ARTICLES
Unique article labels: 275
Total article mentions: 14,746
المادة 16: 1,771
المادة 35: 810
المادة 90: 703
المادة 57: 641
المادة 76: 453
المادة 36: 398
المادة 30: 377
المادة 1: 357
المادة 17: 311
المادة 2: 275
المادة 164: 262
المادة 443: 248
المادة 3: 247
المادة 200: 224
المادة 26: 217
المادة 29: 215
المادة 527: 189
المادة 31: 185
المادة 58: 179
المادة 128: 179
المادة 19: 169
المادة 11: 160
المادة 20: 154
المادة 42: 140
المادة 139: 135

LEGAL REFERENCE COVERAGE
Judgments with recognized legal systems: 8,792
Judgments with article numbers: 7,302

=================================================================
SAMPLES: MULTIPLE OUTCOMES
=================================================================

Judgment: 4530547328
Outcomes: ['إلزام', 'رفض الدعوى']
Source: RULING
Evidence: {"إلزام": ["نص الحكم: ⏎ حكمت الدايرة بالزام المدعي عليها/موسسة [Person Name] للمقاولات سجل تجاري رقم (...) لصاحبها([Person Name] هوية وطنية رقم: (...)) بان يدفع للمدعية/موسس", "نص الحكم: ⏎ حكمت الدايرة بالزام المدعي عليها/موسسة [Person Name] للمقاولات سجل تجاري رقم (...) لصاحبها([Person Name] هوية وطنية رقم: (...)) بان يدفع للمدعية/موسسة مكارم البد"], "رفض الدعوى": ["...)) مبلغا قدره (٢,٩٠٢,٤٣٦.٠٠) مليونان وتسع مية واثنان الفا واربع مية وستة وثلاثون ريال ورفض طلب اتعاب المحاماة وبالله التوفيق."]}

Judgment: 4530547384
Outcomes: ['إلزام', 'رفض الدعوى']
Source: RULING
Evidence: {"إلزام": ["نص الحكم: ⏎ حكمت الدايرة بما يلي: اولا: الزام اماني راشد سعيد الشامسي الهوية الوطنية رقم: (...) بان تدفع لنجلاء سعد محمد ال سليمان الهوية الوطنية: (...) مبلغا مقداره (46.000) ستة واربعون الف ريال. ⏎ ثانيا: رفض طلب المدعي[Person Name]،"], "رفض الدعوى": ["محمد ال سليمان الهوية الوطنية: (...) مبلغا مقداره (46.000) ستة واربعون الف ريال. ⏎ ثانيا: رفض طلب المدعي[Person Name]، والله الموفق."]}

Judgment: 4530545584
Outcomes: ['إلزام', 'رفض الدعوى']
Source: RULING
Evidence: {"إلزام": ["نص الحكم: ⏎ حكمت الدايرة غيابيا: اولا- الزام المدعي عليه/ (...)، سجل مدني رقم: (...)، بان يدفع للمدعية/ شركة (...) للسيارات المحدودة، سجل تجاري رقم: (...)، مبلغا قدره: (125.677) مية وخمس", "نص الحكم: ⏎ حكمت الدايرة غيابيا: اولا- الزام المدعي عليه/ (...)، سجل مدني رقم: (...)، بان يدفع للمدعية/ شركة (...) للسيارات المحدودة، سجل تجاري رقم: (...)، مبلغا قدره: (125.677) مية وخمسة وعشرون الفا وستماية وسبعة وسبعون ريا"], "رفض الدعوى": ["قم: (...)، مبلغا قدره: (125.677) مية وخمسة وعشرون الفا وستماية وسبعة وسبعون ريالا. ثانيا- رفض طلب المدعي[Person Name]."]}

Judgment: 4530535365
Outcomes: ['إلزام', 'رفض الدعوى']
Source: RULING
Evidence: {"إلزام": ["نص الحكم: ⏎ فلكل ما تقدم، عليه حكمت المحكمة بالاتي: الزام المدعي عليه[Person Name] سجل رقم (...) بان تدفع للمدعي[Person Name] (...) مبلغ قدره: (312,133) ثلاثماية واثنا عشر الف وماية وثلاثة وثلاثون ري", "نص الحكم: ⏎ فلكل ما تقدم، عليه حكمت المحكمة بالاتي: الزام المدعي عليه[Person Name] سجل رقم (...) بان تدفع للمدعي[Person Name] (...) مبلغ قدره: (312,133) ثلاثماية واثنا عشر الف وماية وثلاثة وثلاثون ريال، ورد ما زاد عليه . ثانيا : رفض طل"], "رفض الدعوى": ["ره: (312,133) ثلاثماية واثنا عشر الف وماية وثلاثة وثلاثون ريال، ورد ما زاد عليه . ثانيا : رفض طلب المدعي[Person Name]. والله الموفق."]}

Judgment: 4570088841
Outcomes: ['إلزام', 'فسخ أو إنهاء']
Source: RULING
Evidence: {"إلزام": ["لي: اولا: فسخ العقد المبرم بين طرفي الدعوي بتاريخ ١٣/٠٢/١٤٤٣ه الموافق ٢٠/٠٩/٢٠٢١م. ثانيا: الزام المدعي عليها/موسسة (...) سجل تجاري رقم (...) بان تدفع للمدعي/(...) مبلغا قدره (٣٧,٠٠٧) سبعة وثلاثون الفا وسبعة ريالات. ثالثا:: الزام المدعي ع", "م (...) بان تدفع للمدعي/(...) مبلغا قدره (٣٧,٠٠٧) سبعة وثلاثون الفا وسبعة ريالات. ثالثا:: الزام المدعي عليها/موسسة (...) سجل تجاري رقم (...) بان تدفع للمدعي/(...) مبلغا قدره (١٣,٨٠٠) ثلاثة عشر الفا وثمانماية ريال لقاء اتعاب الخبرة، والله"], "فسخ أو إنهاء": ["نص الحكم: ⏎ حكمت الدايرة بما يلي: اولا: فسخ العقد المبرم بين طرفي الدعوي بتاريخ ١٣/٠٢/١٤٤٣ه الموافق ٢٠/٠٩/٢٠٢١م. ثانيا: الزام المدعي عليها/موسسة (...) سجل تجاري رقم (...) بان تدفع"]}

Judgment: 4530578830
Outcomes: ['إلزام', 'فسخ أو إنهاء']
Source: RULING
Evidence: {"إلزام": ["نص الحكم: ⏎ حكمت الدايرة بفسخ العقد المبرم بين الاطراف فيما تبقي منه، وبالزام المدعي عليه[Person Name] (١٣٥,٨٢٥.٠٠) ماية وخمسة وثلاثون الفا وثمان مية وخمسة وعشرون ريال سعودي، والله الموفق.", "نص الحكم: ⏎ حكمت الدايرة بفسخ العقد المبرم بين الاطراف فيما تبقي منه، وبالزام المدعي عليه[Person Name] (١٣٥,٨٢٥.٠٠) ماية وخمسة وثلاثون الفا وثمان مية وخمسة وعشرون ريال سعودي، والله الموفق."], "فسخ أو إنهاء": ["نص الحكم: ⏎ حكمت الدايرة بفسخ العقد المبرم بين الاطراف فيما تبقي منه، وبالزام المدعي عليه[Person Name] (١٣٥,٨٢٥.٠٠) ماية وخمسة وثلاثون الفا وثمان مية وخمسة وعشرون ري", "نص الحكم: ⏎ حكمت الدايرة بفسخ العقد المبرم بين الاطراف فيما تبقي منه، وبالزام المدعي عليه[Person Name] (١٣٥,٨٢٥.٠٠) ماية وخمسة وثلاثون الفا وثمان مية وخمسة وعش"]}

Judgment: 4530513777
Outcomes: ['إلزام', 'رفض الدعوى']
Source: RULING
Evidence: {"إلزام": ["ن الدايرة التجارية السابعة في القضية رقم: ١٩٦٨ لعام ١٤٤١، بتاريخ: ١٤٤١٠٦٢٤ه، وحصل علي حكم بالزامه بدفع مبلغ: ٩٢,٧٤٠ بدون وجهه حق هذا بخلاف القرار التنفيذي الذي ثبت تزويره الحكم رقم: ٤٣٢١٤٦٦٨٩ بتاريخ: ١٤٤٣٠٩١٨ه، الصادر من دايرة", "لمدعي عليه[Person Name] عن تلك الاضرار. بناء عليه ارجو من فضيلتكم: ولكل ما سبق ارجو الحكم بالزام المدعي عليه[Person Name] المبالغ الذي ادعي بمطالبته في دعواه ضد موكلي بالباطل بمبلغ وقدره ٦٢١,٥٠٠ ريال ، وبناء عليه تم رفع الجلسة"], "رفض الدعوى": ["٤٥٧ بتاريخ: ١٤٤٤٠٥١٣ه، حيث انه بتاريخ: ١٤٤٤٠٥١٣ه، قضت الدايرة التجارية الحادية عشر حكمها برفض الدعوي لما هو مبين بالاسباب في صك الحكم رقم: ٤٤٣٠٣٤٦٦٥٨، وتم تايد الحكم من محكمة الاستيناف بموجب صك الحكم الصادر من الدايرة الاستينافية ", "me] اقر بصحة دعوي موكلي في المطالبة بالتعويض. اولا: وفقا لصك الحكم الصادر ضده برفض دعواه برفض الدعوي لما هو مبين بالاسباب في صك الحكم رقم: ٤٤٣٠٣٤٦٦٥٨ وتم تايد الحكم من محكمة الاستيناف بموجب صك الحكم الصادر من الدايرة الاستينافية ا"]}

Judgment: 4530493307
Outcomes: ['إلزام', 'فسخ أو إنهاء']
Source: RULING
Evidence: {"إلزام": ["نص الحكم: ⏎ حكمت الدايرة اولا: فسخ العقد المبرم بين الطرفين. ⏎ ثانيا: الزام [Person Name] هوية وطنية رقم (...) بان يدفع لهيا [Person Name] راوه هوية وطنية رقم (...) مبلغ وقدره (126.171) مية وستة وعشرون الف ومية وواحد وسبعون ريال. ⏎ ثالثا: الزام [Per", "وطنية رقم (...) مبلغ وقدره (126.171) مية وستة وعشرون الف ومية وواحد وسبعون ريال. ⏎ ثالثا: الزام [Person Name] هوية وطنية رقم (...) بان يدفع لهيا [Person Name] راوه هوية وطنية رقم (...) مبلغ وقدره (15.000) خمسة عشرة الف ريال تمثل اتعاب التقاضي."], "فسخ أو إنهاء": ["نص الحكم: ⏎ حكمت الدايرة اولا: فسخ العقد المبرم بين الطرفين. ⏎ ثانيا: الزام [Person Name] هوية وطنية رقم (...) بان يدفع لهيا [Person Name] راوه هوية وطنية رقم (...) مبلغ "]}

=================================================================
SAMPLES: LEGAL REFERENCES
=================================================================

Judgment: 4630531487
Systems: ['اللائحة التنفيذية لنظام المحاكم التجارية', 'نظام المحاكم التجارية', 'نظام الاثبات']
Articles: ['المادة 16', 'المادة 94', 'المادة 90']
System evidence: {"اللائحة التنفيذية لنظام المحاكم التجارية": ["[Person Name] هذه الجلسة بمهمة تبليغ رقم ( ١١٥٩٦١١٤٤ )، وقد تحققت الدايرة بما ورد في المادة (٩٠) من اللايحة التنفيذية لنظام المحاكم التجارية وعن صحة التوزيع الداخلي ووقوع الدعوي في ولاية اختصاصها القضايي بناء علي المادة (١٦) من نظام المحاكم التجارية وقبولها شكلا وتحقق شروط قبول، "], "نظام المحاكم التجارية": ["قامة بين تاجرين في عقد تجاري; عليه تكون المحكمة التجارية مختصة بنظر النزاع استنادا للمادة (١٦/١) من نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم (م/٩٣) وتاريخ ١٥/٠٨/١٤٤١ه، اما عن الموضوع ولما كانت المدعي[Person Name] طلب الحكم بالزام المدعي عليه[Person Name", "لجلسة بمهمة تبليغ رقم ( ١١٥٩٦١١٤٤ )، وقد تحققت الدايرة بما ورد في المادة (٩٠)
Article evidence: {"المادة 16": [], "المادة 94": [], "المادة 90": []}

Judgment: 4530025921
Systems: ['اللائحة التنفيذية لنظام المحاكم التجارية', 'نظام المحاكم التجارية']
Articles: ['المادة 16', 'المادة 30']
System evidence: {"اللائحة التنفيذية لنظام المحاكم التجارية": ["الدعوي. وبتاريخ 16/ 7/ 1444ه افتتحت الدايرة في هذه الدعوي الجلسة التحضيرية اعمالا للمادة التسعين من اللايحة التنفيذية لنظام المحاكم التجارية، وفيها حضرت وكيل[Person Name]، فيما تبين عدم حضور من يمثل المدعي عليه[Person Name]، وبسوال وكيل[Person Name] ما ورد في صحيفة الدعوي ومرفقات"], "نظام المحاكم التجارية": ["لي مستتر...وله بينة، ولو شاهدا ويمينا فيما يقبل منه فيه سمعت وحكم بها) ; وبناء علي المادة (٣٠/١) من نظام المحاكم التجارية التي تنص علي انه: اذا تبلغ [Person Name] [Person Name]، او حضر اي منهما في اي جلسة امام المحكمة، او قدم مذكرة بدفاعه، عدت الخصومة حضورية، و", " 7/ 1444ه افتتحت الدايرة في هذه الدعوي الجلسة التحضيرية اعمالا للمادة التسعين
Article evidence: {"المادة 16": [], "المادة 30": []}

Judgment: 4470472699
Systems: ['اللائحة التنفيذية لنظام المحاكم التجارية', 'نظام المحاكم التجارية', 'نظام الاثبات']
Articles: ['المادة 16', 'المادة 11', 'المادة 90']
System evidence: {"اللائحة التنفيذية لنظام المحاكم التجارية": ["وبما ان مبلغ المطالبة لا يزيد عن مليون ريال، فان الدايرة مختصة نوعيا وفقا للمادة (11) الفقرة (1) من اللايحة التنفيذية لنظام المحاكم التجارية الصادرة بقرار وزير العدل رقم (8344) وتاريخ 26/10/1441ه، والتي نصت علي ان تولف دواير ابتدايية في المحكمة من قاض واحد: (لنظر الدعاوي المنصوص ", "23033)، والمرخص له بمزاولة مهنة المحاماة بالترخيص رقم: (421074)، وبناء علي ما ورد في المادة (90) من اللايحة التنفيذية لنظام المحاكم التجارية؛ فقد افهمت الدايرة الاطراف ان هذه الدعوي تقع في ولاية اختصاصها القضايي بناء علي المادة (16) من نظام المحاكم التجارية، كما رات الدايرة ان هذ"], "نظام المحاكم التجارية": ["ين بسبب اعمالهم التجارية، تعلق به اختصاص المحاكم التجارية
Article evidence: {"المادة 16": [], "المادة 11": [], "المادة 90": []}

Judgment: 4530571198
Systems: ['اللائحة التنفيذية لنظام المحاكم التجارية', 'نظام المحاكم التجارية']
Articles: ['المادة 90', 'المادة 16', 'المادة 19', 'المادة 71']
System evidence: {"اللائحة التنفيذية لنظام المحاكم التجارية": ["5931885) والوكالة رقم (45919959) والوكالة رقم (442451210)، ولتحقق الدايرة بما ورد في المادة (90) من اللايحة التنفيذية لنظام المحاكم التجارية، فقد افهمت الدايرة الاطراف ان هذه الدعوي تقع في ولاية اختصاصها القضايي بناء علي المادة (16) من نظام المحاكم التجارية، كما رات الدايرة ان هذ"], "نظام المحاكم التجارية": ["صص في شركة نظامية، مما تختص علي اثره المحكمة التجارية بنظر هذه الدعوي استنادا للمادة السادسة عشر من نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم (م/93) وتاريخ 15/08/1441ه، وبما ان وكيل [Person Name] الزام المدعي عليه[Person Name] ما تم جرده بعقد التنازل وال", "قم (45919959) والوكالة رقم (442451210)، ولتحقق الدايرة بما ورد في المادة (90)
Article evidence: {"المادة 90": [], "المادة 16": [], "المادة 19": [], "المادة 71": []}

Judgment: 4530540868
Systems: ['اللائحة التنفيذية لنظام المحاكم التجارية', 'نظام المحاكم التجارية']
Articles: ['المادة 16']
System evidence: {"اللائحة التنفيذية لنظام المحاكم التجارية": ["عد العدالة، والعرف المتبع، والمنفعة العايدة، والجهد المبذول; واستنادا لما نصت عليه المادة: (164) من اللايحة التنفيذية لنظام المحاكم التجارية الصادرة بقرار وزير العدل رقم: (8344) في 26/10/1441ه; والمتضمنة علي انه: تراعي المحكمة في تقدير التعويض الاتي: ا-جسامة الضرر. ب-مقدار المبلغ", "عد العدالة، والعرف المتبع، والمنفعة العايدة، والجهد المبذول؛ واستنادا لما نصت عليه المادة: (164) من اللايحة التنفيذية لنظام المحاكم التجارية الصادرة بقرار وزير العدل رقم: (8344) في 26/10/1441ه؛ والمتضمنة علي انه: تراعي المحكمة في تقدير التعويض الاتي: ا-جسامة الضرر. ب-مقدار المبلغ"], "نظام المحاكم التجارية": ["المتبع، والمنفعة العايدة، والجهد المبذول; واستنادا لما نصت
Article evidence: {"المادة 16": []}

Judgment: 4530547483
Systems: ['نظام المرافعات الشرعية', 'نظام المحاكم التجارية']
Articles: ['المادة 90']
System evidence: {"نظام المرافعات الشرعية": ["بطلان الدفع الموضوعي المقدم من وكيل [Person Name] ان دفعه في غير محله استنادا لنص المادة الخمسون من نظام المرافعات الشرعية والتي تنص علي (يجب علي الوكيل [Person Name] يودع صورة مصدقة من وثيقة وكالته لدي الكاتب المختص، وللمحكمة ان ترخص للوكيل [Person Name] موعد ت", "بطلان الدفع الموضوعي المقدم من وكيل [Person Name] ان دفعه في غير محله استنادا لنص المادة الخمسون من نظام المرافعات الشرعية والتي تنص علي (يجب علي الوكيل [Person Name] يودع صورة مصدقة من وثيقة وكالته لدي الكاتب المختص، وللمحكمة ان ترخص للوكيل [Person Name] موعد ت"], "نظام المحاكم التجارية": ["ج بموجب وكالة رقم (451070946). ⏎ وفي سبيل تحقق الدايرة من المسايل الاولية وفقا للمادة (90) من لايحة نظام المحاكم
Article evidence: {"المادة 90": []}

Judgment: 4530547774
Systems: ['نظام المحاكم التجارية', 'نظام الاثبات']
Articles: ['المادة 16']
System evidence: {"نظام المحاكم التجارية": [" اعمال المقاولة بين التجار فان الاختصاص بنظرها منعقدا للمحكمة التجارية وفقا لما ورد بالمادة (١٦) من نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم (م/٩٣) بتاريخ ١٥/٠٨/١٤٤١ه، وحيث ان المدعي [Person Name] التعويض عن الاخلال باعمال مقاولة تنفيذ ديكورات، وحيث ان ", " اعمال المقاولة بين التجار فان الاختصاص بنظرها منعقدا للمحكمة التجارية وفقا لما ورد بالمادة (١٦) من نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم (م/٩٣) بتاريخ ١٥/٠٨/١٤٤١ه، وحيث ان المدعي [Person Name] التعويض عن الاخلال باعمال مقاولة تنفيذ ديكورات، وحيث ان "], "نظام الاثبات": ["rson Name]، كما انه انكر وجود تقصير منه في التنفيذ او المدة، وبناء علي المادة العاشرة بعد الماية من نظام الاثبات: (للمحكمة –
Article evidence: {"المادة 16": []}

Judgment: 4530541904
Systems: ['اللائحة التنفيذية لنظام المحاكم التجارية', 'نظام المحاكم التجارية', 'نظام الاثبات']
Articles: ['المادة 17', 'المادة 90']
System evidence: {"اللائحة التنفيذية لنظام المحاكم التجارية": ["on Name] الجلسة، رغم تبلغها بموعد الجلسة ووصول الرابط لها، ولتحقق الدايرة بما ورد في المادة (90) من اللايحة التنفيذية لنظام المحاكم التجارية وعن صحة التوزيع الداخلي فقد سالت الدايرة المدعي وكالة: هل سبق رفع هذه القضية في هذه المحكمة او اي محكمة اخري لذات الاطراف وذات النزاع فاجاب"], "نظام المحاكم التجارية": ["م تبلغها بموعد الجلسة ووصول الرابط لها، ولتحقق الدايرة بما ورد في المادة (90) من اللايحة التنفيذية لنظام المحاكم التجارية وعن صحة التوزيع الداخلي فقد سالت الدايرة المدعي وكالة: هل سبق رفع هذه القضية في هذه المحكمة او اي محكمة اخري لذات الاطراف وذات النزاع فاجاب"], "نظام الاثبات": ["نه من المقرر ان اليمين تشرع في جانب اقوي المتداعيين، وذلك ب
Article evidence: {"المادة 17": [], "المادة 90": []}

Judgment: 4530519309
Systems: ['نظام المحاكم التجارية', 'نظام الاثبات']
Articles: ['المادة 1', 'المادة 94']
System evidence: {"نظام المحاكم التجارية": ["ت التجارية، وعليه تختص المحاكم التجارية بنظر هذه الدعوي استنادا للفقرة (١) من المادة السادسة عشر من نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم (م/٩٣) في ١٥/٨/١٤٤١ه لكون النزاع بين تاجرين بسبب عمل تجاري اصلي، ومن حيث الموضوع فبما ان المدعي [Person Name] بع", "ت التجارية، وعليه تختص المحاكم التجارية بنظر هذه الدعوي استنادا للفقرة (١) من المادة السادسة عشر من نظام المحاكم التجارية الصادر بالمرسوم الملكي رقم (م/٩٣) في ١٥/٨/١٤٤١ه لكون النزاع بين تاجرين بسبب عمل تجاري اصلي، ومن حيث الموضوع فبما ان المدعي [Person Name] بع"], "نظام الاثبات": ["وي، وبما ان الاصل المعتبر ان البينة علي من ادعي واليمين علي من انكر وفقا لما جاء في المادة (١/٣) من نظام الاثبات، وحيث اطلعت
Article evidence: {"المادة 1": [], "المادة 94": []}

Judgment: 4530509459
Systems: ['نظام المرافعات الشرعية', 'نظام المحاكم التجارية', 'نظام الاثبات']
Articles: ['المادة 76', 'المادة 26', 'المادة 3', 'المادة 16', 'المادة 48', 'المادة 93']
System evidence: {"نظام المرافعات الشرعية": ["اول في مسالة العروج علي حكم محكمة الاستيناف ان اصحاب الفضيلة اشاروا الي نص الفقرة 2 من المادة 76 من نظام المرافعات الشرعية ولان نص الفقرة الثانية من المادة المشار اليها استهلت بعبارة اذا رات المحكمة ومن ثم فالامر متروك للمحكمة التي تنظر الدعوي دون معقب. وبالاشار", " بنص المادة (93) من نظام المحكمة التجارية قد نصت علي ((فيما لم يرد فيه نص خاص في النظام، تطبق احكام نظام المرافعات الشرعية علي الدعاوي التي تختص بنظرها المحكمة بما لا يخالف طبيعة الدعوي التجارية.))، ولما كان نظام المحكمة التجارية قد خلا من بيان الصفة والمصلحة ال"], "نظام المحاكم التجارية": ["علي الوقايع سالفة البيان، ولما كان الدعوي الماثلة امام الدايرة مما تندرج تحت مضمون المادة (16/4) من نظام المحاكم

In [14]:
# ============================================================
# ESNAD - REFINED OUTCOME & LEGAL REFERENCE AUDIT
# يعتمد على df_clean الموجود مسبقًا
# لا يعيد بناء Embeddings أو FAISS
# ============================================================

import pandas as pd
import re
import json
from collections import Counter

assert "df_clean" in globals(), "لم أجد df_clean. شغّلي خلايا تجهيز البيانات أولًا."

df_audit = df_clean.copy().reset_index(drop=True)

# ------------------------------------------------------------
# 1) Arabic text normalization
# ------------------------------------------------------------

def norm_ar(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = text.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")
    text = text.replace("ى", "ي").replace("ة", "ه")
    text = text.replace("ؤ", "و").replace("ئ", "ي")
    text = re.sub(r"[ًٌٍَُِّْـ]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def to_western_digits(text):
    trans = str.maketrans("٠١٢٣٤٥٦٧٨٩", "0123456789")
    return text.translate(trans)

# ------------------------------------------------------------
# 2) Refined outcome extraction
#    Only inspect text following explicit judicial ruling anchors
# ------------------------------------------------------------

OUTCOME_PATTERNS = {
    "إلزام": [
        r"بالزام", r"الزام المدعي", r"الزام المدعي عليه",
        r"الزام المدعي عليها", r"بان يدفع", r"بان تدفع",
        r"بان يؤدي", r"بان تؤدي", r"الزام الطرف"
    ],
    "رفض الدعوى أو الطلب": [
        r"رفض الدعوي", r"رفض طلب", r"رفض الدعوى"
    ],
    "عدم قبول الدعوى": [
        r"عدم قبول الدعوي", r"بعدم قبول الدعوي"
    ],
    "عدم جواز نظر الدعوى": [
        r"عدم جواز نظر الدعوي", r"بعدم جواز نظر الدعوي"
    ],
    "عدم الاختصاص": [
        r"عدم الاختصاص", r"عدم اختصاص المحكمه",
        r"عدم اختصاص الدائره", r"عدم اختصاص الدائرة"
    ],
    "فسخ أو إنهاء": [
        r"فسخ العقد", r"فسخ الاتفاق", r"انهاء العقد",
        r"انهاء الاتفاق"
    ],
    "صلح": [
        r"اثبات الصلح", r"اعتماد الصلح", r"الصلح بين الطرفين"
    ],
    "شطب الدعوى": [
        r"شطب الدعوي", r"شطب القضية"
    ],
    "حل وتصفية": [
        r"حل الشركه", r"تصفية الشركه", r"حل وتصفية"
    ],
    "ثبوت حق أو شراكة": [
        r"ثبوت الشراكه", r"ثبوت حق", r"اثبات الشراكه"
    ]
}

RULING_ANCHORS = [
    "حكمت الدايره",
    "حكمت المحكمه",
    "قضت الدايره",
    "قضت المحكمه",
    "لذلك حكمت",
    "فلهذه الاسباب حكمت",
    "عليه حكمت المحكمه",
    "عليه حكمت الدايره"
]

def get_ruling_windows(text):
    text = norm_ar(text)
    windows = []

    for anchor in RULING_ANCHORS:
        start = 0
        while True:
            pos = text.find(anchor, start)
            if pos == -1:
                break

            # استبعاد بعض الإشارات التي تبدو سردًا لحكم سابق
            before = text[max(0, pos-180):pos]
            historical_markers = [
                "سبق ان صدر", "صدر حكم", "حصل علي حكم",
                "الحكم السابق", "الحكم الصادر", "بموجب حكم"
            ]

            if not any(x in before for x in historical_markers):
                windows.append(text[pos:pos+1800])

            start = pos + len(anchor)

    # إزالة النوافذ المتكررة والمتداخلة
    unique = []
    for w in windows:
        if not any(w[:250] == old[:250] for old in unique):
            unique.append(w)

    return unique

def classify_refined_outcome(ruling_text):
    windows = get_ruling_windows(ruling_text)
    found = {}
    for label, patterns in OUTCOME_PATTERNS.items():
        for window in windows:
            matched = [p for p in patterns if re.search(p, window)]
            if matched:
                found[label] = window[:650]
                break

    labels = list(found.keys())

    if not labels:
        status = "غير محدد"
    elif len(labels) == 1:
        status = labels[0]
    else:
        status = " | ".join(labels)

    return status, labels, found, len(windows)

outcome_results = df_audit["RULING"].apply(classify_refined_outcome)

df_audit["outcome_refined"] = outcome_results.apply(lambda x: x[0])
df_audit["outcomes_refined_list"] = outcome_results.apply(
    lambda x: json.dumps(x[1], ensure_ascii=False)
)
df_audit["outcome_refined_evidence"] = outcome_results.apply(
    lambda x: json.dumps(x[2], ensure_ascii=False)
)
df_audit["ruling_anchor_count"] = outcome_results.apply(lambda x: x[3])

# ------------------------------------------------------------
# 3) Legal systems: controlled names and aliases
# ------------------------------------------------------------

LEGAL_SYSTEMS = {
    "نظام المحاكم التجارية": [
        "نظام المحاكم التجارية"
    ],
    "اللائحة التنفيذية لنظام المحاكم التجارية": [
        "اللائحة التنفيذية لنظام المحاكم التجارية",
        "لايحة نظام المحاكم التجارية",
        "اللائحة التنفيذية للمحاكم التجارية"
    ],
    "نظام المرافعات الشرعية": [
        "نظام المرافعات الشرعية"
    ],
    "نظام الشركات": [
        "نظام الشركات"
    ],
    "نظام الإثبات": [
        "نظام الاثبات"
    ],
    "نظام الإفلاس": [
        "نظام الافلاس"
    ],
    "نظام التحكيم": [
        "نظام التحكيم"
    ],
    "نظام التنفيذ": [
        "نظام التنفيذ"
    ],
    "نظام المعاملات المدنية": [
        "نظام المعاملات المدنية"
    ],
    "نظام الأوراق التجارية": [
        "نظام الاوراق التجارية"
    ],
    "نظام العلامات التجارية": [
        "نظام العلامات التجارية"
    ],
    "نظام الأسماء التجارية": [
        "نظام الاسماء التجارية"
    ],
    "نظام حماية حقوق المؤلف": [
        "نظام حماية حقوق المؤلف"
    ],
    "نظام براءات الاختراع": [
        "نظام براءات الاختراع"
    ],
    "نظام الوكالات التجارية": [
        "نظام الوكالات التجارية"
    ],
    "نظام الامتياز التجاري": [
        "نظام الامتياز التجاري"
    ],
    "نظام العمل": [
        "نظام العمل"
    ],
    "نظام السجل التجاري": [
        "نظام السجل التجاري"
    ],
    "نظام الاستثمار": [
        "نظام الاستثمار"
    ],
    "نظام التعاملات الإلكترونية": [
        "نظام التعاملات الالكترونية"
    ],
    "نظام التجارة الإلكترونية": [
        "نظام التجارة الالكترونية"
    ],
    "نظام مكافحة التستر": [
        "نظام مكافحة التستر"
    ],
    "نظام مكافحة الغش التجاري": [
        "نظام مكافحة الغش التجاري"
    ],
    "نظام المنافسة": [
        "نظام المنافسة"
    ],
    "نظام ضريبة القيمة المضافة": [
        "نظام ضريبة القيمة المضافة"
    ],
    "نظام الملكية الفكرية": [
        "نظام الملكية الفكرية"
    ]
}

SYSTEM_PATTERNS = {}

for system, aliases in LEGAL_SYSTEMS.items():
    SYSTEM_PATTERNS[system] = [
        norm_ar(alias) for alias in aliases
    ]

# ------------------------------------------------------------
# 4) Article extraction and contextual system association
# ------------------------------------------------------------

ARTICLE_REGEX = re.compile(
    r"الماده\s*[:：]?\s*"
    r"(?:رقم\s*)?"
    r"[\(（]?\s*([0-9٠-٩]{1,4})\s*[\)）]?"
    r"(?:\s*/\s*([0-9٠-٩]{1,3}))?"
)

def find_system_mentions(text):
    text = norm_ar(text)
    mentions = []

    for system, aliases in SYSTEM_PATTERNS.items():
        for alias in aliases:
            start = 0
            while True:
                pos = text.find(alias, start)
                if pos == -1:
                    break

                mentions.append({
                    "system": system,
                    "start": pos,
                    "end": pos + len(alias)
                })
                start = pos + len(alias)

    return mentions

def extract_references_from_text(text, source_name):
    text = norm_ar(text)
    if not text:
        return [], []

    systems = find_system_mentions(text)
    articles = []

    for match in ARTICLE_REGEX.finditer(text):
        number = to_western_digits(match.group(1))
        sub_number = match.group(2)

        article_label = f"المادة {number}"
        if sub_number:
            article_label += f"/{to_western_digits(sub_number)}"

        start = match.start()
        end = match.end()

        # سياق المادة قبلها وبعدها
        left = max(0, start - 300)
        right = min(len(text), end + 300)
        context = text[left:right]

        # اختيار أقرب نظام مذكور ضمن السياق
        nearby_systems = []
        for system_mention in systems:
            distance = min(
                abs(system_mention["start"] - start),
                abs(system_mention["end"] - end)
            )
            if distance <= 300:
                nearby_systems.append((distance, system_mention["system"]))

        nearby_systems.sort(key=lambda x: x[0])

        linked_system = nearby_systems[0][1] if nearby_systems else None

        articles.append({
            "article": article_label,
            "system": linked_system,
            "source": source_name,
            "context": context
        })

    system_records = []
    for mention in systems:
        left = max(0, mention["start"] - 220)
        right = min(len(text), mention["end"] + 220)

        system_records.append({
            "system": mention["system"],
            "source": source_name,
            "context": text[left:right]
        })

    return system_records, articles

# ------------------------------------------------------------
# 5) Extract references separately by text field
# ------------------------------------------------------------

all_system_records = []
all_article_records = []
per_judgment_systems = []
per_judgment_articles = []

for idx, row in df_audit.iterrows():
    judgment_id = str(row.get("judgment_number", idx))

    judgment_systems = []
    judgment_articles = []

    # أسباب الحكم هي المصدر الأهم للاستدلال النظامي.
    # الوقائع والمنطوق تحفظ منفصلة ولا تدمج معها.
    for col, source_name in [
        ("REASONING", "أسباب الحكم"),
        ("RULING", "المنطوق/حقل RULING"),
        ("EVENTS", "وقائع القضية")
    ]:
        if col not in df_audit.columns:
            continue

        sys_records, art_records = extract_references_from_text(
            row[col], source_name
        )

        for item in sys_records:
            item["judgment_number"] = judgment_id
            all_system_records.append(item)
            judgment_systems.append(item)

        for item in art_records:
            item["judgment_number"] = judgment_id
            all_article_records.append(item)
            judgment_articles.append(item)

    per_judgment_systems.append(sorted(set(
        x["system"] for x in judgment_systems
    )))

    per_judgment_articles.append(judgment_articles)

df_audit["legal_systems_refined"] = [
    json.dumps(x, ensure_ascii=False) for x in per_judgment_systems
]

df_audit["legal_articles_refined"] = [
    json.dumps(x, ensure_ascii=False) for x in per_judgment_articles
]

# ------------------------------------------------------------
# 6) Build reference tables
# ------------------------------------------------------------

systems_df = pd.DataFrame(all_system_records)
articles_df = pd.DataFrame(all_article_records)

if not systems_df.empty:
    systems_summary = (
        systems_df.groupby("system")
        .agg(
            mentions=("system", "size"),
            judgments=("judgment_number", "nunique")
        )
        .sort_values("judgments", ascending=False)
    )
else:
    systems_summary = pd.DataFrame()

if not articles_df.empty:
    articles_summary = (
        articles_df.groupby(["article", "system"], dropna=False)
        .agg(
            mentions=("article", "size"),
            judgments=("judgment_number", "nunique")
        )
        .reset_index()
        .sort_values(["judgments", "mentions"], ascending=False)
    )
else:
    articles_summary = pd.DataFrame()

# ------------------------------------------------------------
# 7) Print audit report
# ------------------------------------------------------------

print("=" * 65)
print("ESNAD - REFINED OUTCOME & LEGAL REFERENCES AUDIT")
print("=" * 65)

print("\nOUTCOME DISTRIBUTION")
print(df_audit["outcome_refined"].value_counts().to_string())

identified = (df_audit["outcome_refined"] != "غير محدد").sum()
multiple = df_audit["outcomes_refined_list"].apply(
    lambda x: len(json.loads(x)) > 1
).sum()

print("\nOUTCOME COVERAGE")
print("Total judgments:", len(df_audit))
print("Judgments with anchored outcome:", identified)
print("Judgments without anchored outcome:", len(df_audit) - identified)
print("Coverage:", round(identified / len(df_audit) * 100, 2), "%")
print("Judgments with multiple outcomes:", multiple)
print("Judgments with no explicit ruling anchor:",
      (df_audit["ruling_anchor_count"] == 0).sum())

print("\nLEGAL SYSTEMS")
if not systems_summary.empty:
    print(systems_summary.to_string())
else:
    print("No systems extracted.")

print("\nARTICLE REFERENCES BY SYSTEM")
if not articles_summary.empty:
    print(articles_summary.head(35).to_string(index=False))
else:
    print("No article references extracted.")

print("\nREFERENCE LINKING")
if not articles_df.empty:
    linked = articles_df["system"].notna().sum()
    unlinked = articles_df["system"].isna().sum()
    print("Total article mentions:", len(articles_df))
    print("Articles linked to a nearby system:", linked)
    print("Articles without a nearby system:", unlinked)
    print("Linking rate:", round(linked / len(articles_df) * 100, 2), "%")

print("\nSAMPLES: ARTICLE REFERENCES WITH CONTEXT")
if not articles_df.empty:
    sample_articles = articles_df.sample(
        min(12, len(articles_df)), random_state=42
    )
    for _, item in sample_articles.iterrows():
        print("\nJudgment:", item["judgment_number"])
        print("Article:", item["article"])
        print("System:", item["system"])
        print("Source:", item["source"])
        print("Context:", item["context"][:450])

print("\nSAMPLES: REFINED OUTCOMES")
sample_outcomes = df_audit[
    df_audit["outcome_refined"] != "غير محدد"
].sample(
    min(12, identified), random_state=42
)

for _, row in sample_outcomes.iterrows():
    print("\nJudgment:", row.get("judgment_number"))
    print("Outcome:", row["outcome_refined"])
    print("Anchor count:", row["ruling_anchor_count"])
    print("Evidence:", row["outcome_refined_evidence"][:900])

# ------------------------------------------------------------
# 8) Save outputs
# ------------------------------------------------------------

df_audit.to_csv(
    "/content/esnad_arabiccr_refined_audit.csv",
    index=False,
    encoding="utf-8-sig"
)

if not systems_df.empty:
    systems_df.to_csv(
        "/content/esnad_legal_system_mentions.csv",
        index=False,
        encoding="utf-8-sig"
    )

if not articles_df.empty:
    articles_df.to_csv(
        "/content/esnad_legal_article_references.csv",
        index=False,
        encoding="utf-8-sig"
    )

print("\n" + "=" * 65)
print("FILES SAVED")
print("/content/esnad_arabiccr_refined_audit.csv")
print("/content/esnad_legal_system_mentions.csv")
print("/content/esnad_legal_article_references.csv")
print("=" * 65)

=================================================================
ESNAD - REFINED OUTCOME & LEGAL REFERENCES AUDIT
=================================================================

OUTCOME DISTRIBUTION
outcome_refined
إلزام                                                   5731
غير محدد                                                4405
رفض الدعوى أو الطلب                                     1398
عدم قبول الدعوى                                          346
عدم الاختصاص                                             235
عدم جواز نظر الدعوى                                      114
إلزام | فسخ أو إنهاء                                      83
إلزام | رفض الدعوى أو الطلب                               63
فسخ أو إنهاء                                              31
إلزام | عدم قبول الدعوى                                   28
إلزام | عدم الاختصاص                                       7
رفض الدعوى أو الطلب | فسخ أو إنهاء                         6
ثبوت حق أو شراكة                                           5
إلزام | رفض الدعوى أو الطلب | فسخ أو إنهاء                 4
صلح                                                        3
رفض الدعوى أو الطلب | ثبوت حق أو شراكة                     3
رفض الدعوى أو الطلب | عدم الاختصاص                         3
رفض الدعوى أو الطلب | صلح                                  2
إلزام | عدم جواز نظر الدعوى                                2
عدم قبول الدعوى | عدم جواز نظر الدعوى                      2
رفض الدعوى أو الطلب | عدم قبول الدعوى                      2
عدم قبول الدعوى | فسخ أو إنهاء                             1
شطب الدعوى                                                 1
إلزام | ثبوت حق أو شراكة                                   1
رفض الدعوى أو الطلب | عدم قبول الدعوى | فسخ أو إنهاء       1

OUTCOME COVERAGE
Total judgments: 12477
Judgments with anchored outcome: 8072
Judgments without anchored outcome: 4405
Coverage: 64.7 %
Judgments with multiple outcomes: 208
Judgments with no explicit ruling anchor: 1472

LEGAL SYSTEMS
                                          mentions  judgments
system
نظام المحاكم التجارية                         8393       4138
نظام المرافعات الشرعية                        7390       4016
اللائحة التنفيذية لنظام المحاكم التجارية      2222       1670
نظام الشركات                                  3289       1110
نظام الإثبات                                  1645        979
نظام الإفلاس                                   472        179
نظام التحكيم                                   250        134
نظام التنفيذ                                   185        125
نظام العلامات التجارية                         211         85
نظام الأسماء التجارية                          143         74
نظام الأوراق التجارية                           99         69
نظام حماية حقوق المؤلف                         143         67
نظام العمل                                      94         59
نظام السجل التجاري                              52         50
نظام الوكالات التجارية                          57         23
نظام الاستثمار                                  23         16
نظام براءات الاختراع                            29         14
نظام التعاملات الإلكترونية                      13         12
نظام الامتياز التجاري                           42         10
نظام مكافحة التستر                              14          8
نظام مكافحة الغش التجاري                        11          7
نظام المعاملات المدنية                          12          6
نظام ضريبة القيمة المضافة                        5          4
نظام المنافسة                                   17          4
نظام التجارة الإلكترونية                         1          1
نظام الملكية الفكرية                             1          1

ARTICLE REFERENCES BY SYSTEM
    article                                   system  mentions  judgments
  المادة 16                    نظام المحاكم التجارية      1429       1213
  المادة 35                   نظام المرافعات الشرعية       644        599
  المادة 90 اللائحة التنفيذية لنظام المحاكم التجارية       545        509
  المادة 57                   نظام المرافعات الشرعية       319        295
  المادة 76                   نظام المرافعات الشرعية       341        290
 المادة 164 اللائحة التنفيذية لنظام المحاكم التجارية       257        239
  المادة 30                    نظام المحاكم التجارية       214        199
 المادة 200                   نظام المرافعات الشرعية       307        191
 المادة 527                                      NaN       181        179
 المادة 443                                      NaN       185        176
  المادة 29                             نظام الإثبات       174        157
 المادة 128                   نظام المرافعات الشرعية       164        141
   المادة 1                                      NaN       164        133
  المادة 16                                      NaN       149        131
  المادة 26                                      NaN       135        116
 المادة 139                   نظام المرافعات الشرعية       119        109
المادة 57/2                   نظام المرافعات الشرعية       103         97
  المادة 31                   نظام المرافعات الشرعية       101         97
  المادة 58                    نظام المحاكم التجارية       100         95
   المادة 3                                      NaN       142         87
  المادة 19                    نظام المحاكم التجارية       106         83
  المادة 42                    نظام المحاكم التجارية        88         81
   المادة 2                                      NaN       110         77
   المادة 4                                      NaN       111         76
  المادة 66                   نظام المرافعات الشرعية        80         72
   المادة 6                                      NaN       116         71
  المادة 17                    نظام المحاكم التجارية        78         70
  المادة 20                    نظام المحاكم التجارية        83         67
المادة 30/1                    نظام المحاكم التجارية        69         62
 المادة 133 اللائحة التنفيذية لنظام المحاكم التجارية        64         60
  المادة 36                   نظام المرافعات الشرعية        63         58
  المادة 11                                      NaN        85         53
المادة 57/1                   نظام المرافعات الشرعية        55         53
   المادة 5                                      NaN        67         51
  المادة 25                    نظام المحاكم التجارية        51         50

REFERENCE LINKING
Total article mentions: 14920
Articles linked to a nearby system: 11441
Articles without a nearby system: 3479
Linking rate: 76.68 %

SAMPLES: ARTICLE REFERENCES WITH CONTEXT

Judgment: 285/8/ق
Article: المادة 443
System: None
Source: أسباب الحكم
Context: تقديمه فذكروا انهم يكتفون بما سبق، وبناء عليه قررت الدايره رفع الجلسه للمداوله واصدار الحكم. ⏎ (الاسباب) ⏎ لما كان المدعي [Person Name] عقد بيع حصه الشريكه المدعي عليها، وبما ان الدعوي تعد من دعاوي النزاع بين الشركاء وهي شركه [Person Name]، فهي تعد من المنازعات التي تقع بين الشركاء المنصوص عليها في الماده (443) من نظام المحكمه التجاريه، وديوان المظالم مختص بنظر المنازعات الناشيه عنها والفصل فيها حسب نص قراري مجلس الوزراء رقم (241) لعام 1407 ه، كم

Judgment: 4432
Article: المادة 200
System: نظام المرافعات الشرعية
Source: أسباب الحكم
Context: مدينه الرياض والتي يطالب فيها المدعي [Person Name]. ثالثا: العدول عن القرار محل الالتماس والحكم برد دعوي المدعي. هذا ما لزم بيانه والتاكيد عليه" وبالاطلاع عليه تبين عدم وجود اي مرفقات في الطلب ولم يحضر وكيل [Person Name] وعليه قررت الدايره رفع الجلسه للمداوله واصدار الحكم. ⏎ ⏎ (الاسباب) ⏎ ولما كانت الماده (200) من نظام المرافعات الشرعيه الصادر بالمرسوم الملكي رقم (م/1) وتاريخ 22/1/1435ه قد نصت علي قبول التماس اعاده النظر في حكم الدايره بما يلي: (

Judgment: 4430912843
Article: المادة 164
System: اللائحة التنفيذية لنظام المحاكم التجارية
Source: أسباب الحكم
Context: ترافع; وقد استقرت مبادي الشريعه الاسلاميه بمنع الضرر ورفعه، واما من ناحيه مقدار الاتعاب المطالب بها، ولما كان [Person Name] [Person Name]ا عن المعتاد، وبما ان تقدير ذلك مناط بالدايره، بعيدا عما يطلبه الاطراف، بحسب قواعد العداله، والعرف المتبع، والمنفعه العايده، والجهد المبذول; واستنادا لما نصت عليه الماده: (١٦٤) من اللايحه التنفيذيه لنظام المحاكم التجاريه الصادره بقرار وزير العدل رقم: (٨٣٤٤) في ٢٦/١٠/١٤٤١ه; علي انه:" يجب علي المحكمه ان تضمن حكمها

Judgment: 934
Article: المادة 16
System: نظام المحاكم التجارية
Source: أسباب الحكم
Context: ولما كان وكيل [Person Name] بالزام المدعي عليه[Person Name] (1.044.000) مليون واربعه واربعين الف ريال، مقابل تنفيذ اعمال مقاولات للمدعي عليها; لذلك فان هذه المنازعه تندرج تحت نص الماده (16) من نظام المحاكم التجاريه الصادر بالمرسوم الملكي رقم (م / 93) وتاريخ 15 / 8 / 1441ه; وبناء عليه فان المحكمه التجاريه مختصه بنظر هذه القضيه. وبما ان وكيل [Person Name] دعوي المدعيه، و ذكر ان المدعي[Person Name] ايه مبالغ، وليس بينهما اي اتفاق ولم تقم المدعي[Pers

Judgment: 5128/4/ق
Article: المادة 443
System: None
Source: أسباب الحكم
Context: بما ان النزاع الحاصل بين الطرفين ناشي عن التعامل التجاري بينهما، وبما ان هذا النزاع يندرج تحت ما نص عليه نظام المحكمه التجاريه الصادر بالمرسوم الملكي رقم (٣٢) وتاريخ ١٥/١/١٣٥٠ه، في الماده (٤٤٣) فقره (ب) لذا فان الاختصاص بنظر هذه القضيه ينعقد للدايره وفقا لذلك. واما عن الموضوع، فلما كان المدعي [Person Name] حسب العقد الموقع بينهما، وبما ان الاتفاق بين الطرفين قد نص علي ان قيمه الايجار هو ١٨٠٠٠ريال شهريا، وبما ان المدعي [Person Name] لمده شهرين حسب

Judgment: 4431078652
Article: المادة 76
System: نظام المرافعات الشرعية
Source: أسباب الحكم
Context: يال، واجمل وكيل [Person Name] الاختصاص النوعي وبما ان الاختصاص في مجال القضاء من المسايل الاوليه التي يتعين علي الدايره بحثها والفصل فيها ابتداء قبل التطرق لموضوع النزاع، حتي لو لم يدفع به احد الخصوم; لتعلق ذلك بالولايه القضاييه، اذ لا يجوز الفصل في نزاع خارج عن اختصاصها، بناء علي الفقره رقم (1) من الماده (76) من نظام المرافعات الشرعيه والتي نصت علي: (الدفع بعدم اختصاص المحكمه لانتفاء ولايتها او بسبب نوع الدعوي او قيمتها، او الدفع بعدم قبول الدعو

Judgment: 4430883495
Article: المادة 200
System: None
Source: أسباب الحكم
Context: /2018م ولو كان لدي الملتمسه حسب زعمها وجود رجيع او ان التعامل بينهما كان علي التصريف لما ناقضت نفسها في الورقه الصادره منها والتي اقرت بها بتاريخ 29/5/2019م بصحه الدين وبصحه الرصيد دون اي ملاحظه ودون اي ذكر لما تزعمه الان. صاحب الفضيله: ولان الامر كذلك، ولان ما قدمته الملتمسه لا ينطبق علي ما تضمنته الماده 200 من نظام المرافعات، ولان ما قدمته الملتمسه تنكره موكلتي جمله وتفصيلا، ولان موكلتي قد قدمت ما يدحض ويسقط مزاعم الملتمسه مما تم ايراده اعلاه،

Judgment: 4430879784
Article: المادة 19
System: نظام براءات الاختراع
Source: أسباب الحكم
Context: وديه للملكيه الفكريه لموضوع من موضوعات الحمايه، تجسدت في شهاده النموذج الصناعي للمدعي[Person Name] (SA 8400) بتاريخ 1442/02/10ه. وحيث ارسي نظام براءات الاختراع والتصميمات التخطيطيه للدارات المتكامله والاصناف النباتيه والنماذج الصناعيه الصادر بالمرسوم الملكي رقم (م/27) بتاريخ 29 / 5 / 1425ه، من خلال الماده (19/د) الحمايه للنموذج الصناعي، ونص علي ان: "مده حمايه شهاده النموذج الصناعي عشر سنوات من تاريخ ايداع الطلب" ⏎ وباطلاع الدايره علي الادله الالك

Judgment: 4430670783
Article: المادة 164
System: اللائحة التنفيذية لنظام المحاكم التجارية
Source: أسباب الحكم
Context: يه استحقاق المدعي[Person Name]، والدايره في طور تحديد ما تستحقه المدعي[Person Name] انها عقدت فيها خمس جلسات، ولم يقدم فيها محامي المدعي [Person Name]، مما تذهب معه الدايره مناسبه تحميل [Person Name] مبلغا وقدره (10.000) ريال; وذلك بما للدايره سلطه تقديريه في تقدير اتعاب التقاضي، بحسبان ما نصت عليه الماده (١٦٤) من اللايحه التنفيذيه لنظام المحاكم التجاريه، لا سيما وان المدعي[Person Name] الاتعاب المطالب بها.

Judgment: 4430242921
Article: المادة 76
System: نظام المرافعات الشرعية
Source: وقائع القضية
Context: وتسعه عشر الف وثلاثمايه وستون ريال لشركه [Person Name] سجل تجاري رقم (...) فهذا غير صحيح جمله وتفصيلا ، والصحيح ان الدعوي مقامه من شركه (.....) سجل تجاري رقم (...) ضد موكلتي شركه (....) (...) والمقيده في المحكمه التجاريه بالرياض برقم (....) وتاريخ 28/01/1442ه (مرفق1) .واستنادا علي الفقره رقم (1) من الماده (76) من نظام المرافعات الشرعيه ونص الحاجه منها: (1-الدفع بعدم اختصاص المحكمه لانتفاء ولايتها او بسبب نوع الدعوي او قيمتها، او الدفع بعدم قبول ا

Judgment: 177/د/ تج/7
Article: المادة 2
System: None
Source: أسباب الحكم
Context: حيث ان وكيل [Person Name] عليها ان تدفع لموكلته مبلغا قدره (9,110,000) تسعه ملايين ومايه وعشره الاف ريال، عباره عن قيمه حديد مورد للمدعي عليها. ⏎ وحيث ان العلاقه بين طرفي الدعوي علاقه عقد توريد فهي من اختصاص الديوان حسب نص الماده (2/ب) من نظام المحكمه التجاريه ونصها: "يعتبر من الاعمال التجاريه كل ما هو ات: ب- كل مقاوله او تعهد بتوريد اشياء ... الخ" ا. ه. ⏎ وحيث انه لم يحضر من يمثل المدعي عليه[Person Name] بهذه القضيه وموعد نظرها حسبما هو ثابت بال

Judgment: 1231
Article: المادة 6
System: نظام المحاكم التجارية
Source: أسباب الحكم
Context: فبناء علي ما تقدم من الدعوي والاجابه وبما ان الخلاف بين الطرفين يتعلق بنزاع يتعلق بعقد انشاء ومقاوله بين الشركتين وبما ان الخلاف من ضمن الاختصاص النوعي للدايره استنادا الي الماده ٦ من نظام المحاكم التجاريه ومن حيث الموضوع وبما ان المدعي[Person Name] ان [Person Name] [Person Name] قد اقامت بخصوص مستحقاتها الدعوي السابقه المقيده برقم (٢٣٢٠) عام ١٤٤٠ه لدي المحكمه التجاريه بجده وحكم بموجبها بمبلغ وقدره (٩,٣٥١.٧٠١) ريال، كما ان المتبقي من المحكوم به ع

SAMPLES: REFINED OUTCOMES

Judgment: 1496
Outcome: رفض الدعوى أو الطلب
Anchor count: 1
Evidence: {"رفض الدعوى أو الطلب": "حكمت الدايره: برفض الدعوي المقامه من المدعي/ (...) رقم الهويه: (...) ضد شركه (...) سجل تجاري رقم (...) وشركه (...) سجل تجاري رقم (...)."}

Judgment: 246
Outcome: إلزام
Anchor count: 2
Evidence: {"إلزام": "حكمت الدايره حضوريا: بالزام المدعي عليه[Person Name] (...) للمقاولات المحدوده سجل تجاري رقم (...) بان تدفع للمدعي[Person Name] (...) لتاجير المعدات سجل تجاري رقم (...) المبالغ المحدده ادناه: ⏎ اولا: مبلغا قدره (333,103,85) ثلاثمايه وثلاثه وثلاثون الفا ومايه وثلاثه ريال وخمسه وثمانون هلله. ⏎ ثانيا: مبلغا قدره (33,000) ثلاثه وثلاثون الف ريال والتي تمثل اتعاب التقاضي، لما هو مبين بالاسباب، وبالله التوفيق. ⏎ ⏎ عضو ⏎ القاضي [Person Name] ⏎ القاضي [Person Name] ⏎ رييس الدايره ⏎ القاضي [Person Name]"}

Judgment: 2547
Outcome: إلزام
Anchor count: 3
Evidence: {"إلزام": "حكمت الدايره:فلهذه الاسباب حكمت الدايره بالزام المدعي عليها/ شركه (...) للتجاره والمقاولات، بان تدفع للمدعي/ (...) مبلغ قدره (٩٧.٦٧٥) سبعه وتسعون الفا وستمايه وخمسه وسبعون ريالا، والله الموفق , وصلي الله وسلم علي نبينا [Person Name] وعلي اله وصحبه اجمعين . ⏎ امين السر ⏎ (...) ⏎ رييس الدايره ⏎ (...)"}

Judgment: 64/1/ق
Outcome: إلزام
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره: بالزام المدعي عليه[Person Name] (...) للمقاولات المحدوده - بان تدفع للمدعي (...) سجل مدني رقم (...) صاحب موسسه (...) التجاريه سجل تجاري رقم (...) مبلغا قدره (189.409) مايه وتسعه وثمانون الفا واربعمايه وتسعه ريالات وذلك لما هو موضح بالاسباب، وبالله التوفيق وصلي الله وسلم علي نبينا محمد وعلي اله وصحبه وسلم."}

Judgment: 26
Outcome: رفض الدعوى أو الطلب
Anchor count: 1
Evidence: {"رفض الدعوى أو الطلب": "حكمت الدايره: برفض الدعوي لما هو موضح بالاسباب. وبﷲ التوفيق، وصلي ﷲ علي نبينا [Person Name] وعلي اله وصحبه وسلم ,,, ⏎ ⏎ عضو ⏎ [Person Name] ⏎ عضو ⏎ [Person Name] ⏎ رييس الدايره ⏎ [Person Name]"}

Judgment: 4430656902
Outcome: إلزام
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره بالزام المدعي عليه[Person Name] (...) ذات السجل التجاري رقم: (...) بان تدفع للمدعي[Person Name] (...) للخدمات الصناعيه ذات السجل التجاري رقم: (...) مبلغا وقدره ٣٠٧.٧٥٥ريال ثلاثمايه وسبعه الاف وسبعمايه وخمسه وخمسون ريال، شامل اتعاب المحاماه وذلك لما هو موضح بالاسباب والمدعي عليه[Person Name] مده لا تتجاوز ثلاثين يوما من تاريخ تسليم الحكم وفي حال عدم تقديمها خلال المده المتاحه فسيكتسب الحكم الصفه القطعيه وبالله التوفيق وصلي الله وسلم علي نبينا محمد وعلي اله وصحبه اجمعين."}

Judgment: 4430497246
Outcome: إلزام
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره: بالزام/ [Person Name]، يحمل هويه وطنيه رقمها: (...) بان يدفع ل/ رافت [Person Name]، يحمل هويه وطنيه رقمها: (...) مبلغا قدره: اربعمايه وعشرون الف (420,000) ريال، لما هو موضح بالاسباب، والله ولي التوفيق."}

Judgment: 4430220450
Outcome: رفض الدعوى أو الطلب
Anchor count: 1
Evidence: {"رفض الدعوى أو الطلب": "حكمت الدايره برفض الدعوي رقم ٤٣٩٣٢٩٣٧٢ والمقامه من/ (...) هويه وطنيه رقم (...) ضد /شركه (...) التجاريه سجل تجاري رقم (...)."}

Judgment: 9549/3/ق
Outcome: إلزام | رفض الدعوى أو الطلب | فسخ أو إنهاء
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره بالاتي: اولا: رفض الدعوي المقامه من (...) لفسخ العقد المبرم بتاريخ 16/11/2015م. ثانيا: الزام (...) بان يدفع لشركه مجموعه (...) للتجاره والصناعه مبلغا قدره (2,493,187,66) مليونين واربعمايه وثلاثه وتسعون الفا ومايه وسبعه وثمانون ريالا وسته وستون هلله، وباعلان منطوق الحكم علي وكيل [Person Name] (...) للتجاره والصناعه قرر القناعه وقرر وكيل/ (...) عدم القناعه، والله الموفق. ⏎ ⏎ امين الدايره ⏎ احمد بن محمد العتيبي ⏎ القاضي ⏎ [Person Name] بن سلمان المعثم ⏎ رييس الدايره ⏎ [Person Name]", "رفض الدعوى أو الطلب": "حكمت الدايره بالاتي: اولا: رفض الدعوي المقامه من (...) لفسخ العقد المبرم بتاريخ 16/11/2015م. ثانيا: الزام (...) بان يدفع لشركه مجموعه (...) للتجاره والصناعه مبلغا قدره (2,493,187,66) مليونين واربعمايه وثلاثه وتسعون الفا ومايه وسبعه وثمانون ريالا وسته وستون هلله، وباعلان منطوق الحكم علي وكيل [Person Name] (...) للتجاره والصناعه قرر القناعه وقرر وكيل/ (...) عدم القن

Judgment: 3525
Outcome: إلزام
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره: [Person Name] (...) سجل تجاري رقم : (...) بان تدفع ل (...) اقامه رقم : (...) (...) الجنسيه مبلغ قدره (١.٢٥٠.٨٣٤) مليون وميتان وخمسون الفا وثمانميه واربعه وثلاثون ريالا , وبﷲ التوفيق وصلي ﷲ علي نبينا [Person Name] واله وسلم ."}

Judgment: (1148/ 3/ق
Outcome: إلزام
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره: بالزام المدعي عليه/ شركه (...) للمقاولات- سجل تجاري رقم (...) بان يدفع للمدعيه/ الشركه (...) للصناعات الحديديه- سجل تجاري رقم (...) مبلغا قدره (10,334,529,52) عشره ملايين وثلاثمايه واربعه وثلاثون الفا وخمسمايه وتسعه وعشرون ريالا واثنان وخمسون هلله. والله الموفق، وصلي الله علي نبينا [Person Name] وعلي اله وصحبه وسلم. ⏎ ⏎ ⏎ امين السر ⏎ [Person Name] ⏎ عضو ⏎ [Person Name] ⏎ عضو ⏎ [Person Name] ⏎ رييس الدايره ⏎ [Person Name]"}

Judgment: 7617
Outcome: إلزام
Anchor count: 1
Evidence: {"إلزام": "حكمت الدايره بما يلي: اولا/ الزام شركه (...) المحدوده سجل تجاري رقم: (...) بان تدفع (...) سجل مدني رقم: (...) صاحبه موسسه (...) سجل تجاري رقم: (...) مبلغا قدره 663.300 ستمايه وثلاثه وستون الفا وثلاثمايه ريال. ثانيا/ الزام شركه (...) المحدوده سجل تجاري رقم: (...) بان تدفع (...) سجل مدني رقم: (...) صاحبه موسسه (...) سجل تجاري رقم: (...) مبلغا قدره 50.000 خمسون الف ريال تمثل اتعاب المحاماه. ⏎ ⏎ عضو ⏎ (...) ⏎ عضو ⏎ (...) ⏎ رييس الدايره ⏎ (...)"}

=================================================================
FILES SAVED
/content/esnad_arabiccr_refined_audit.csv
/content/esnad_legal_system_mentions.csv
/content/esnad_legal_article_references.csv
=================================================================

In [15]:
# ============================================================
# ESNAD - LEGAL CONTEXT & OUTCOME PRECISION V2
# لا يعيد بناء embeddings أو FAISS
# ============================================================

import pandas as pd
import re
import json

# ------------------------------------------------------------
# 1) Prepare source
# ------------------------------------------------------------

source_df = df_clean.copy().reset_index(drop=True)

def normalize_ar(text):
    if pd.isna(text):
        return ""
    text = str(text)
    text = text.translate(str.maketrans(
        "٠١٢٣٤٥٦٧٨٩", "0123456789"
    ))
    text = text.replace("أ", "ا").replace("إ", "ا").replace("آ", "ا")
    text = text.replace("ى", "ي").replace("ة", "ه")
    text = text.replace("ؤ", "و").replace("ئ", "ي")
    text = re.sub(r"[ًٌٍَُِّْـ]", "", text)
    return text

# ------------------------------------------------------------
# 2) Correct outcome: distinguish requested rescission
#    from rescission actually ordered by the court
# ------------------------------------------------------------

def refine_rescission_label(outcome_json, evidence_json):
    labels = json.loads(outcome_json)
    evidence = json.loads(evidence_json)

    if "فسخ أو إنهاء" not in labels:
        return labels, evidence

    text = evidence.get("فسخ أو إنهاء", "")
    text = normalize_ar(text)

    # Split operative ruling into clauses
    clauses = re.split(
        r"\s+(?=(?:اولا|ثانيا|ثالثا|رابعا|خامسا)\s*[:：/\-])"
        r"|[؛;.!؟]",
        text
    )

    positive_rescission = False

    for clause in clauses:
        clause = clause.strip()

        if not re.search(
            r"(?:فسخ العقد|فسخ الاتفاق|انهاء العقد|انهاء الاتفاق)",
            clause
        ):
            continue

        negative_context = re.search(
            r"(?:رفض|عدم قبول|عدم اجابة|رد)\s*"
            r"(?:الدعوي|الدعوى|طلب|طلبات)",
            clause
        )

        if not negative_context:
            positive_rescission = True
            break

    if not positive_rescission:
        labels = [x for x in labels if x != "فسخ أو إنهاء"]
        evidence.pop("فسخ أو إنهاء", None)

    return labels, evidence

# Reuse the previous anchored outcome extraction
assert "classify_refined_outcome" in globals(), (
    "شغّلي خلية التدقيق السابقة أولًا."
)

outcome_rows = []

for _, row in source_df.iterrows():
    status, labels, evidence, anchor_count = (
        classify_refined_outcome(row.get("RULING", ""))
    )

    labels, evidence = refine_rescission_label(
        json.dumps(labels, ensure_ascii=False),
        json.dumps(evidence, ensure_ascii=False)
    )

    final_status = " | ".join(labels) if labels else "غير محدد"

    outcome_rows.append({
        "outcome_v2": final_status,
        "outcomes_v2_list": json.dumps(labels, ensure_ascii=False),
        "outcome_v2_evidence": json.dumps(evidence, ensure_ascii=False),
        "ruling_anchor_count": anchor_count
    })

outcomes_v2_df = pd.DataFrame(outcome_rows)
source_df = pd.concat([source_df, outcomes_v2_df], axis=1)

# ------------------------------------------------------------
# 3) Legal systems: distinguish old and current commercial law
# ------------------------------------------------------------

SYSTEM_ALIASES = {
    "نظام المحاكم التجارية": [
        "نظام المحاكم التجارية"
    ],

    "نظام المحكمة التجارية القديم": [
        "نظام المحكمة التجارية",
        "نظام المحكمه التجاريه"
    ],

    "اللائحة التنفيذية لنظام المحاكم التجارية": [
        "اللائحة التنفيذية لنظام المحاكم التجارية",
        "لايحة نظام المحاكم التجارية",
        "اللائحة التنفيذية للمحاكم التجارية"
    ],

    "نظام المرافعات الشرعية": [
        "نظام المرافعات الشرعية"
    ],

    "نظام الشركات": [
        "نظام الشركات"
    ],

    "نظام الإثبات": [
        "نظام الاثبات"
    ],

    "نظام الإفلاس": [
        "نظام الافلاس"
    ],

    "نظام التحكيم": [
        "نظام التحكيم"
    ],

    "نظام التنفيذ": [
        "نظام التنفيذ"
    ],

    "نظام المعاملات المدنية": [
        "نظام المعاملات المدنية"
    ],

    "نظام الأوراق التجارية": [
        "نظام الاوراق التجارية"
    ],

    "نظام العلامات التجارية": [
        "نظام العلامات التجارية"
    ],

    "نظام الأسماء التجارية": [
        "نظام الاسماء التجارية"
    ],

    "نظام حماية حقوق المؤلف": [
        "نظام حماية حقوق المؤلف"
    ],

    "نظام براءات الاختراع": [
        "نظام براءات الاختراع والتصميمات التخطيطية للدارات المتكاملة والاصناف النباتية والنماذج الصناعية",
        "نظام براءات الاختراع"
    ],

    "نظام الوكالات التجارية": [
        "نظام الوكالات التجارية"
    ],

    "نظام الامتياز التجاري": [
        "نظام الامتياز التجاري"
    ],

    "نظام العمل": [
        "نظام العمل"
    ],

    "نظام السجل التجاري": [
        "نظام السجل التجاري"
    ],

    "نظام الاستثمار": [
        "نظام الاستثمار"
    ],

    "نظام التعاملات الإلكترونية": [
        "نظام التعاملات الالكترونية"
    ],

    "نظام التجارة الإلكترونية": [
        "نظام التجارة الالكترونية"
    ],

    "نظام مكافحة التستر": [
        "نظام مكافحة التستر"
    ],

    "نظام مكافحة الغش التجاري": [
        "نظام مكافحة الغش التجاري"
    ],

    "نظام المنافسة": [
        "نظام المنافسة"
    ],

    "نظام ضريبة القيمة المضافة": [
        "نظام ضريبة القيمة المضافة"
    ],

    "نظام الملكية الفكرية": [
        "نظام الملكية الفكرية"
    ]
}

NORMALIZED_ALIASES = {
    system: [normalize_ar(alias) for alias in aliases]
    for system, aliases in SYSTEM_ALIASES.items()
}

# ------------------------------------------------------------
# 4) Split text into local legal contexts
# ------------------------------------------------------------

def split_legal_segments(text):
    text = normalize_ar(text)

    # Keep segments reasonably local.
    segments = re.split(
        r"[\n\r⏎؛;.!؟]+",
        text
    )

    # Very long segments may contain multiple legal references.
    final_segments = []

    for segment in segments:
        segment = segment.strip()
        if not segment:
            continue

        if len(segment) <= 900:
            final_segments.append(segment)
        else:
            for start in range(0, len(segment), 650):
                part = segment[start:start+800].strip()
                if part:
                    final_segments.append(part)

    return final_segments

ARTICLE_PATTERN_V2 = re.compile(
    r"الماده\s*[:：]?\s*"
    r"(?:رقم\s*)?"
    r"[\(（]?\s*([0-9]{1,4})\s*[\)）]?"
    r"(?:\s*/\s*([0-9]{1,3}))?"
)

def systems_in_segment(segment):
    found = []

    for system, aliases in NORMALIZED_ALIASES.items():
        for alias in aliases:
            if alias and alias in segment:
                found.append(system)
                break

    # Avoid treating the old singular law as the current plural law.
    if "نظام المحكمة التجارية القديم" in found:
        found = [
            x for x in found
            if x != "نظام المحاكم التجارية"
        ]

    return list(dict.fromkeys(found))

# ------------------------------------------------------------
# 5) Extract references with same-segment association
# ------------------------------------------------------------

system_records_v2 = []
article_records_v2 = []

for _, row in source_df.iterrows():
    judgment_id = str(row.get("judgment_number", ""))

    for col, source_name in [
        ("REASONING", "أسباب الحكم"),
        ("RULING", "المنطوق/حقل RULING"),
        ("EVENTS", "وقائع القضية")
    ]:
        raw_text = row.get(col, "")
        if pd.isna(raw_text):
            continue

        segments = split_legal_segments(raw_text)

        for segment in segments:
            mentioned_systems = systems_in_segment(segment)

            for system in mentioned_systems:
                system_records_v2.append({
                    "judgment_number": judgment_id,
                    "system": system,
                    "source": source_name,
                    "context": segment[:900]
                })

            for match in ARTICLE_PATTERN_V2.finditer(segment):
                number = match.group(1)
                sub_number = match.group(2)

                article = f"المادة {number}"
                if sub_number:
                    article += f"/{sub_number}"

                # Associate only if the system is mentioned
                # in the same local segment.
                linked_system = (
                    mentioned_systems[0]
                    if len(mentioned_systems) == 1
                    else None
                )

                article_records_v2.append({
                    "judgment_number": judgment_id,
                    "article": article,
                    "system": linked_system,
                    "source": source_name,
                    "systems_in_same_segment": json.dumps(
                        mentioned_systems, ensure_ascii=False
                    ),
                    "context": segment[:900]
                })

systems_v2_df = pd.DataFrame(system_records_v2)
articles_v2_df = pd.DataFrame(article_records_v2)

# ------------------------------------------------------------
# 6) Summaries
# ------------------------------------------------------------

print("=" * 65)
print("ESNAD - PRECISION AUDIT V2")
print("=" * 65)

print("\nOUTCOME DISTRIBUTION")
print(source_df["outcome_v2"].value_counts().to_string())

identified_v2 = (
    source_df["outcome_v2"] != "غير محدد"
).sum()

multiple_v2 = source_df["outcomes_v2_list"].apply(
    lambda x: len(json.loads(x)) > 1
).sum()

print("\nOUTCOME COVERAGE")
print("Identified:", identified_v2)
print("Unidentified:", len(source_df) - identified_v2)
print("Coverage:", round(identified_v2 / len(source_df) * 100, 2), "%")
print("Multiple outcomes:", multiple_v2)

print("\nLEGAL SYSTEMS")
if not systems_v2_df.empty:
    systems_summary_v2 = (
        systems_v2_df.groupby("system")
        .agg(
            mentions=("system", "size"),
            judgments=("judgment_number", "nunique")
        )
        .sort_values("judgments", ascending=False)
    )
    print(systems_summary_v2.to_string())
else:
    print("No systems found.")

print("\nARTICLE REFERENCES BY SYSTEM")
if not articles_v2_df.empty:
    articles_summary_v2 = (
        articles_v2_df.groupby(
            ["article", "system"], dropna=False
        )
        .agg(
            mentions=("article", "size"),
            judgments=("judgment_number", "nunique")
        )
        .reset_index()
        .sort_values(
            ["judgments", "mentions"],
            ascending=False
        )
    )
    print(articles_summary_v2.head(40).to_string(index=False))
else:
    print("No articles found.")

print("\nLINKING QUALITY")
if not articles_v2_df.empty:
    linked_count = articles_v2_df["system"].notna().sum()
    total_count = len(articles_v2_df)

    print("Article mentions:", total_count)
    print("Linked in same segment:", linked_count)
    print("Unlinked or ambiguous:", total_count - linked_count)
    print(
        "Same-segment linking rate:",
        round(linked_count / total_count * 100, 2),
        "%"
    )

# ------------------------------------------------------------
# 7) Important unmatched article samples
# ------------------------------------------------------------

print("\nUNLINKED ARTICLE SAMPLES")
if not articles_v2_df.empty:
    unmatched = articles_v2_df[
        articles_v2_df["system"].isna()
    ]

    if len(unmatched):
        sample = unmatched.sample(
            min(15, len(unmatched)),
            random_state=21
        )

        for _, item in sample.iterrows():
            print("\nJudgment:", item["judgment_number"])
            print("Article:", item["article"])
            print("Source:", item["source"])
            print(
                "Systems in segment:",
                item["systems_in_same_segment"]
            )
            print("Context:", item["context"][:650])

# ------------------------------------------------------------
# 8) Check known examples
# ------------------------------------------------------------

print("\nKNOWN CASE CHECK: 9549/3/ق")
known = source_df[
    source_df["judgment_number"].astype(str).str.contains(
        "9549", na=False
    )
]

if not known.empty:
    for _, row in known.head(3).iterrows():
        print("Outcome V2:", row["outcome_v2"])
        print("Evidence:", row["outcome_v2_evidence"][:1000])
else:
    print("Judgment not found by this number.")

print("\nOLD COMMERCIAL LAW CHECK")
if not articles_v2_df.empty:
    old_law = articles_v2_df[
        articles_v2_df["article"].eq("المادة 443")
    ]
    print("Article 443 mentions:", len(old_law))
    print(
        old_law["system"].value_counts(dropna=False).to_string()
    )

# ------------------------------------------------------------
# 9) Save
# ------------------------------------------------------------

source_df.to_csv(
    "/content/esnad_arabiccr_precision_v2.csv",
    index=False,
    encoding="utf-8-sig"
)

systems_v2_df.to_csv(
    "/content/esnad_legal_systems_v2.csv",
    index=False,
    encoding="utf-8-sig"
)

articles_v2_df.to_csv(
    "/content/esnad_legal_articles_v2.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nFILES SAVED")
print("/content/esnad_arabiccr_precision_v2.csv")
print("/content/esnad_legal_systems_v2.csv")
print("/content/esnad_legal_articles_v2.csv")
print("=" * 65)

=================================================================
ESNAD - PRECISION AUDIT V2
=================================================================

OUTCOME DISTRIBUTION
outcome_v2
إلزام                                         5732
غير محدد                                      4405
رفض الدعوى أو الطلب                           1400
عدم قبول الدعوى                                347
عدم الاختصاص                                   235
عدم جواز نظر الدعوى                            114
إلزام | فسخ أو إنهاء                            82
إلزام | رفض الدعوى أو الطلب                     63
فسخ أو إنهاء                                    31
إلزام | عدم قبول الدعوى                         28
إلزام | عدم الاختصاص                             7
ثبوت حق أو شراكة                                 5
إلزام | رفض الدعوى أو الطلب | فسخ أو إنهاء       4
رفض الدعوى أو الطلب | فسخ أو إنهاء               4
صلح                                              3
رفض الدعوى أو الطلب | ثبوت حق أو شراكة           3
رفض الدعوى أو الطلب | عدم الاختصاص               3
رفض الدعوى أو الطلب | عدم قبول الدعوى            3
إلزام | عدم جواز نظر الدعوى                      2
رفض الدعوى أو الطلب | صلح                        2
عدم قبول الدعوى | عدم جواز نظر الدعوى            2
شطب الدعوى                                       1
إلزام | ثبوت حق أو شراكة                         1

OUTCOME COVERAGE
Identified: 8072
Unidentified: 4405
Coverage: 64.7 %
Multiple outcomes: 204

LEGAL SYSTEMS
                                          mentions  judgments
system
نظام المحاكم التجارية                         7550       4115
نظام المرافعات الشرعية                        7105       4016
اللائحة التنفيذية لنظام المحاكم التجارية      2225       1670
نظام المحكمة التجارية القديم                  1724       1344
نظام الشركات                                  2962       1110
نظام الإثبات                                  1590        979
نظام الإفلاس                                   402        179
نظام التحكيم                                   228        134
نظام التنفيذ                                   178        125
نظام العلامات التجارية                         202         85
نظام الأسماء التجارية                          144         74
نظام الأوراق التجارية                           94         69
نظام حماية حقوق المؤلف                         142         67
نظام العمل                                      85         59
نظام السجل التجاري                              53         50
نظام الوكالات التجارية                          49         23
نظام الاستثمار                                  23         16
نظام براءات الاختراع                            31         14
نظام التعاملات الإلكترونية                      13         12
نظام الامتياز التجاري                           36         10
نظام مكافحة التستر                              12          8
نظام مكافحة الغش التجاري                        11          7
نظام المعاملات المدنية                          11          6
نظام ضريبة القيمة المضافة                        5          4
نظام المنافسة                                   14          4
نظام التجارة الإلكترونية                         1          1
نظام الملكية الفكرية                             1          1

ARTICLE REFERENCES BY SYSTEM
    article                       system  mentions  judgments
  المادة 16        نظام المحاكم التجارية       989        899
  المادة 90                          NaN       555        516
  المادة 35       نظام المرافعات الشرعية       482        445
  المادة 16                          NaN       496        426
  المادة 57       نظام المرافعات الشرعية       312        282
 المادة 164                          NaN       282        247
  المادة 76       نظام المرافعات الشرعية       283        232
 المادة 200       نظام المرافعات الشرعية       289        180
  المادة 30        نظام المحاكم التجارية       195        177
  المادة 35                          NaN       186        177
 المادة 443 نظام المحكمة التجارية القديم       180        170
 المادة 527 نظام المحكمة التجارية القديم       168        161
  المادة 29                 نظام الإثبات       156        140
 المادة 128       نظام المرافعات الشرعية       156        132
   المادة 1                          NaN       168        130
  المادة 26                          NaN       151        125
  المادة 76                          NaN       132        117
  المادة 16 نظام المحكمة التجارية القديم       122        117
   المادة 2                          NaN       151        108
   المادة 3                          NaN       166        100
المادة 57/2       نظام المرافعات الشرعية       105         95
 المادة 139       نظام المرافعات الشرعية       107         92
  المادة 58        نظام المحاكم التجارية        92         86
   المادة 4                          NaN       119         79
  المادة 42        نظام المحاكم التجارية        82         73
   المادة 6                          NaN       120         72
  المادة 31       نظام المرافعات الشرعية        76         72
  المادة 11                          NaN       107         69
  المادة 17        نظام المحاكم التجارية        71         68
 المادة 133                          NaN        70         66
 المادة 200                          NaN        82         65
  المادة 66       نظام المرافعات الشرعية        70         62
  المادة 36       نظام المرافعات الشرعية        65         59
  المادة 13                          NaN        75         58
  المادة 19        نظام المحاكم التجارية        74         57
   المادة 8                          NaN        86         55
  المادة 31                          NaN        66         54
  المادة 10                          NaN        64         53
  المادة 58                          NaN        61         53
   المادة 5                          NaN        71         52

LINKING QUALITY
Article mentions: 15321
Linked in same segment: 9218
Unlinked or ambiguous: 6103
Same-segment linking rate: 60.17 %

UNLINKED ARTICLE SAMPLES

Judgment: 1936/3/ق/
Article: المادة 500
Source: وقائع القضية
Systems in segment: ["نظام المحكمة التجارية القديم", "نظام المرافعات الشرعية"]
Context: تاسيسا علي ما تقدم، واذ افاد وكيل [Person Name]، واضاف بان موكلته لا تنكر مطالبه المدعي[Person Name] هذه المصالحه بالرفض من وكيل المدعيه، الامر الذي يتعين معه البت في النزاع، وحيث لم تطعن المدعي عليه[Person Name]، مما يضفي موافقتها علي ما تضمنه، وفق الماده (51/1) من اللايحه التنفيذيه لنظام المرافعات، الامر الذي تعتد معه الدايره بصحتها بحسبان ما نصت عليه الماده (500) من نظام المحكمه التجاريه، وانسجمت معها في ذلك الماده (139) من نظام المرافعات الشرعيه

Judgment: 4430823798
Article: المادة 2
Source: أسباب الحكم
Systems in segment: []
Context: وحيث ان وكيل [Person Name] بدفع مبلغ قدره اربعه واربعون مليون وثلاثمايه وخمسه واربعون الف وسبعمايه واربعه وخمسون (44,345,754) ريال، يمثل مستحقات موكلته مقابل قيامها بابرام عقد قرض تمويل مع المدعي عليه[Person Name] 18-2-2012م وذلك بحسب دعوي المدعيه، والثابت ان المدعي عليه[Person Name] يه المدعي[Person Name]، غير انها تدفع بان هذا العقد انما هو عقد مشاركه وليس عقد تمويل، وان الدايره وبدراستها للقضيه وبدراستها لدفوع الطرفين تبين لها ان هذا المبلغ الذي دفعته المدعي[Person Name] شراكه بين الطرفين، وان هذا العقد هو عقد شراكه وليس عقد تمويل، ويتبين ذلك من خلال بنود العقد، حيث نص العقد في الفقره الرابعه من البند الثاني علي انه: يجري العميل جميع المدف

Judgment: 3414
Article: المادة 768
Source: أسباب الحكم
Systems in segment: []
Context: وقد جاء في مجله الاحكام العدليه في الماده (768): "الامانه لا تكون مضمونه: يعني اذا هلكت، او ضاعت بلا صنع الامين، ولا تقصير منه

Judgment: 4430141552
Article: المادة 90
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: وجري فيها التحقق مما ورد في الماده (90) من اللايحه التنفيذيه لنظام المحاكم التجاريه

Judgment: 1726
Article: المادة 16
Source: أسباب الحكم
Systems in segment: ["نظام المحاكم التجارية", "نظام المرافعات الشرعية"]
Context: 000) ريالا، كما هو مبين في وقايع الدعوي، وحيث ان النظر في الاختصاص يعد من المسايل الاوليه التي ينبغي النظر فيها قبل الشروع في بحث موضوع الدعوي والفصل فيه وذلك استنادا للماده(30/1) من نظام المرافعات الشرعيه ولايحته التنفيذيه الصادر بالمرسوم الملكي رقم (م/1) تاريخ 22/1/1435ه وحيث ان الاصل ان الدعوي تقام علي [Person Name] [Person Name] عليه في حدود اختصاصها وفقا لنص الماده (16) من نظام المحاكم التجاريه، حيث نصت الماده علي انه: (

Judgment: 4745
Article: المادة 16
Source: أسباب الحكم
Systems in segment: []
Context: ) قد اشترت البضاعه من السوق ثم قامت ببيعها، والدليل اذا تطرق اليه الاحتمال بطل به الاستدلال، كما انه يقوي جانب المدعي عليه[Person Name] مذكراتها ما فتات وحتي اخر مذكره لها في المطالبه بتطبيق الماده (16) من العقد والتي نصت علي انه: "في حاله وجود نزاع بين الطرفين فانه لا يجوز تسجيل عقد توزيع لموزع جديد في منطقه الوكاله عن ذات المنتجات او الخدمات الا بعد صدور حكم او قرار نهايي من الجهه التي تنظر النزاع بين الطرفين"، وهذا يقتضي ان المدعي عليه[Person Name]ا جديدا ولولا ذلك لطالبت المدعي[Person Name]، ولما كان جانب المدعي عليه[Person Name] علي المدعي[Person Name]، وبما انه يلزم من عدم الشرط العدم

Judgment: 9161/1/ق
Article: المادة 35
Source: أسباب الحكم
Systems in segment: ["نظام المحكمة التجارية القديم", "نظام المرافعات الشرعية"]
Context: ) وشركاه للمقاولات بسداد المتبقي في ذمتها مبلغا قدره (538000 ريال) خمسميه وثمانيه وثلاثون الف ريالا امتنعت عن سدادها بدون سبب، وذلك نظير ابرام موكلته مع المدعي عليه[Person Name] المدعي عليه[Person Name] عليها لم تقم بسداد ما في ذمتها لموكلته وختم صحيفه الدعوي بطلب الزام المدعي عليه[Person Name]ا قدره (538000 ريال) خمسميه وثمانيه وثلاثون الف ريالا والمتبقي لموكلته في ذمه المدعي عليه[Person Name]، عليه فان هذه القضيه تكون مشموله بالماده (35) في فقرته (ا) و(ب) من نظام المرافعات الشرعيه الصادر بالمرسوم الملكي رقم (م/1) وتاريخ 22/1/1435ه اذ ان اطرافها تجار وهذا ما يوافق الماده الاولي من نظام المحكمه التجاريه الصادر عام 1350ه وحسب ما بينه التعميم ر

Judgment: 4430586609
Article: المادة 51
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: )، والله الموفق، وصلي الله وسلم علي نبينا محمد وعلي اله وصحبه اجمعين)، وقد اسست الدايره حكمها علي ما يلي: "لما كان من اللازم قبل الولوج في موضوع الدعوي التحقق من صحه قيدها وما يجب ان تتضمنه من بيانات وفق النظام، وحيث نصت الماده (51) من اللايحه التنفيذيه لنظام المحاكم التجاريه الصادره بقرار معالي وزير العدل رقم (8344) وتاريخ 26/10/1441ه علي انه: (يجب ان يكون رفع جميع الدعاوي التي تختص بنظرها المحكمه وجميع طلبات الاستيناف من محام

Judgment: 4430947968
Article: المادة 29
Source: أسباب الحكم
Systems in segment: ["نظام المحاكم التجارية", "نظام الإثبات"]
Context: اضاعه الحقوق واهدارها، وحيث نصت الفقره الاولي الماده(30) من نظام المحاكم التجاريه علي: اذا تبلغ [Person Name] [Person Name]، او حضر اي منهما في اي جلسه امام المحكمه، او قدم مذكره بدفاعه، عدت الخصومه حضوريه، ولو تخلف بعد ذلك فالنظام جعل السير في الدعوي في حق المدعي عليه[Person Name]، والحكم عليها حكما حضوريا، وحيث ان الفقره الاولي من الماده (29) من نظام الاثبات، نصت علي: يعد المحرر العادي صادرا ممن وقعه وحجه عليه

Judgment: 4430224164
Article: المادة 71
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: وفي 27/ 12/ 1443ه قدم وكيل [Person Name]: اولا: بخصوص الدفع الشكلي المقدم من وكيل [Person Name]، نوضح لفضيلتكم ان الماده (71) من اللايحه التنفيذيه لنظام المحاكم التجاريه الفقره (2) نصت علي: (يعد في حكم الاخطار تقديم ما يثبت اللجوء الي التسويه الوديه او المصالحه او الوساطه قبل قيد الدعوي)، ونرفق لفضيلتكم ما يثبت اللجوء للمصالحه وتعذرها بتاريخ 25/ 08/ 1443ه

Judgment: 4470941091
Article: المادة 90
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: ثانيا: الزام الشركه [Person Name][Person Name] للمطالبه بالثابت بذمتها مبلغ وقدره:(249،550) فقط مايتان وتسعه واربعون الف وخمسمايه وخمسون ريال لا غير، وتحميلها كافه المصروفات والتكاليف القضاييه المفروضه علي الدعوي ، وقدمت وكيل[Person Name] والمرفقه مع صحيفه الدعوي، ثم قيدت القضيه بالرقم المشار اليه اعلاه واحيلت الي هذه الدايره وباشرت نظرها حسب ما هو مثبت في محاضرها حيث عقد لها جلسه بتاريخ 11 / 10 / 1444 ه، وفيها افتتحت هذه الجلسه التحضيريه المنعقده عبر الاتصال المريي وحضرت وكيل[Person Name] (444573154) كما حضر وكيل [Person Name] (443685186)، ولاستيفاء ما ورد في الماده رقم (90) من اللايحه التنفيذيه لنظام المحاكم التجاريه فقد جري سوال وكيل[Perso

Judgment: 187
Article: المادة 133
Source: أسباب الحكم
Systems in segment: ["نظام المحكمة التجارية القديم", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: يه من الاحتمالات، لاسيما مثل هذه العقود الكبيره، ولقوله صلي ﷲ عليه وسلم " لو يعطي الناس بدعواهم لادعي الناس دماء رجال واموالهم ولكن اليمين علي المدعي عليه"، ولان السمسره هي (من يتوسط بين البايع والمشتري لاتمام البيع باجره) كما نصت عليها الماده رقم (30) من نظام المحكمه التجاريه الصادر بالمرسوم الملكي رقم (2) وتاريخ 15 / 01 / 1390ه، وحيث ان اليمين لا توجه الي الشخصيه الاعتباريه، استنادا الي الماده رقم (133) من لايحه نظام المحاكم التجاريه المشار اليها اعلاه، فان الدايره تنتهي الي ما يرد في منطوقها ادناه

Judgment: 4430852521
Article: المادة 244
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: ففي جلسه 1444/01/06ه،التحضيريه والمنعقده عن بعد بطريق الاتصال المريي حضر من يمثل المدعي[Person Name] (435580937) كما حضرت من تمثل المدعي عليه[Person Name] (41259372)وبعد تحقق الدايره من المسايل الاوليه وفقا للماده (90) والماده (244) من اللايحه التنفيذيه لنظام المحاكم التجاريه، ثم عرضت الدايره الصلح علي الطرفين وانتهاء الدعوي وديا فقررا قبول الصلح وموافاه الدايره بذلك في الجلسه القادمه، وبسوال الدايره ممثل المدعي[Person Name] في ملف الدعوي، وبسواله عن بيناته واسانيده التي يستند عليها في دعواه ذكر انه يستند علي كشف حساب بالاعمال المنفذه وفواتير ماليه خاصه بالمشروع والمراسلات عبر البريد الالكتروني، وبعرض ذلك علي من تمثل المدعي عليه[Person Name]

Judgment: 4430249349
Article: المادة 16
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: حيث عقد لها جلسه في 10/02/1444ه، فيها حضر المدعي [Person Name] المدعي عليه[Person Name] حسب افاده نظام التبليغات الالكتروني، وطلب المدعي [Person Name] في الماده 90 من اللايحه التنفيذيه لنظام المحاكم التجاريه فقد افهمت الدايره ان هذه الدعوي تقع في ولايه اختصاصها القضايي بناء علي الماده 16 من نظام المحاكم التجاريه كما رات الدايره ان هذه الدعوي مقبوله شكلا وتحققت فيها شروط قبول الدعوي ثم ذكر المدعي [Person Name] بانه تعذر الوصول الي صلح حسب تقرير المصالحه المرفق ثم سالت الدايره المدعي [Person Name] قايلا بان دعواه وطلبه علي وفق صحيفه الدعوي الالكترونيه وبسواله عن بينته وادلته التي يستند اليها في طلبه فاجاب قايلا بان بينه علي الدعوي هي عقد البيع

Judgment: 4570078839
Article: المادة 90
Source: وقائع القضية
Systems in segment: ["نظام المحاكم التجارية", "اللائحة التنفيذية لنظام المحاكم التجارية"]
Context: وفي جلسه 5/2/1445ه والمنعقده عن بعد عبر الاتصال المريي تشير الدايره الي انها افتتحت هذه الجلسه التحضيريه حضر فيها المدعي [Person Name] بياناتهم في اعلي نسخه الضبط وبناء علي ما ورد في الماده 90 من اللايحه التنفيذيه لنظام المحاكم التجاريه فقد افهمتهم الدايره ان هذه الدعوي تقع في ولايه اختصاصها القضايي بناء علي الماده 16 من نظام المحاكم التجاريه وبسوال المدعي [Person Name] الدعوي وبطلب الجواب من وكيل [Person Name] للرد فافهمته الدايره بارفاق الرد عن طريق النظام قبل موعد الجلسه القادمه باسبوع ففهم ذلك واستعد به وعليه رفعت الجلسه وبالله التوفيق

KNOWN CASE CHECK: 9549/3/ق
Outcome V2: رفض الدعوى أو الطلب
Evidence: {"رفض الدعوى أو الطلب": "حكمت الدايره برفض الدعوي ; لما هو موضح بالاسباب ، وبالله التوفيق."}
Outcome V2: إلزام | رفض الدعوى أو الطلب | فسخ أو إنهاء
Evidence: {"إلزام": "حكمت الدايره بالاتي: اولا: رفض الدعوي المقامه من (...) لفسخ العقد المبرم بتاريخ 16/11/2015م. ثانيا: الزام (...) بان يدفع لشركه مجموعه (...) للتجاره والصناعه مبلغا قدره (2,493,187,66) مليونين واربعمايه وثلاثه وتسعون الفا ومايه وسبعه وثمانون ريالا وسته وستون هلله، وباعلان منطوق الحكم علي وكيل [Person Name] (...) للتجاره والصناعه قرر القناعه وقرر وكيل/ (...) عدم القناعه، والله الموفق. ⏎ ⏎ امين الدايره ⏎ احمد بن محمد العتيبي ⏎ القاضي ⏎ [Person Name] بن سلمان المعثم ⏎ رييس الدايره ⏎ [Person Name]", "رفض الدعوى أو الطلب": "حكمت الدايره بالاتي: اولا: رفض الدعوي المقامه من (...) لفسخ العقد المبرم بتاريخ 16/11/2015م. ثانيا: الزام (...) بان يدفع لشركه مجموعه (...) للتجاره والصناعه مبلغا قدره (2,493,187,66) مليونين واربعمايه وثلاثه وتسعون الفا ومايه وسبعه وثمانون ريالا وسته وستون هلله، وباعلان منطوق الحكم علي وكيل [Person Name] (...) للتجاره والصناعه قرر القناعه وقرر وكيل/ (...) عدم القناعه، والله الموفق. ⏎ ⏎ امين الدايره ⏎ احمد بن محمد العتيبي ⏎ القاضي ⏎ [Person Name] بن سلمان المعثم

OLD COMMERCIAL LAW CHECK
Article 443 mentions: 231
system
نظام المحكمة التجارية القديم    180
None                             49
نظام الشركات                      1
نظام المحاكم التجارية             1

FILES SAVED
/content/esnad_arabiccr_precision_v2.csv
/content/esnad_legal_systems_v2.csv
/content/esnad_legal_articles_v2.csv
=================================================================

In [18]:
# ============================================================
# ESNAD - PRECISION AUDIT V3
# Compare ruling sources + strict legal-reference linking
# Requires: df_clean
# Does NOT rebuild embeddings or FAISS
# ============================================================

import pandas as pd
import re
import json
from collections import Counter

assert "df_clean" in globals(), "df_clean غير موجودة. شغّلي تجهيز البيانات أولًا."

df_v3 = df_clean.copy().reset_index(drop=True)

# ------------------------------------------------------------
# 1) Normalization
# ------------------------------------------------------------

def norm(text):
    if text is None:
        return ""

    text = str(text)

    translation_table = str.maketrans({
        "أ": "ا",
        "إ": "ا",
        "آ": "ا",
        "ى": "ي",
        "ة": "ه",
        "ؤ": "و",
        "ئ": "ي",
        "٠": "0",
        "١": "1",
        "٢": "2",
        "٣": "3",
        "٤": "4",
        "٥": "5",
        "٦": "6",
        "٧": "7",
        "٨": "8",
        "٩": "9"
    })

    text = text.translate(translation_table)

    text = re.sub(r"\s+", " ", text)
    return text.strip()

# ------------------------------------------------------------
# 2) Outcome patterns
# ------------------------------------------------------------

OUTCOME_PATTERNS = {
    "إلزام": [
        r"\bبالزام\b",
        r"\bالزام المدعي عليه\b",
        r"\bالزام المدعي عليها\b",
        r"\bبان يدفع\b",
        r"\bبان تدفع\b",
        r"\bبان يؤدي\b",
        r"\bبان تؤدي\b"
    ],
    "رفض الدعوى أو الطلب": [
        r"رفض الدعوي",
        r"رفض طلب",
        r"رد الدعوي",
        r"رد طلب"
    ],
    "عدم قبول الدعوى": [
        r"عدم قبول الدعوي",
        r"بعدم قبول الدعوي"
    ],
    "عدم جواز نظر الدعوى": [
        r"عدم جواز نظر الدعوي",
        r"بعدم جواز نظر الدعوي"
    ],
    "عدم الاختصاص": [
        r"عدم الاختصاص",
        r"عدم اختصاص المحكمه",
        r"عدم اختصاص الدايره"
    ],
    "فسخ أو إنهاء": [
        r"فسخ العقد",
        r"فسخ الاتفاق",
        r"انهاء العقد",
        r"انهاء الاتفاق"
    ],
    "صلح": [
        r"اثبات الصلح",
        r"اعتماد الصلح",
        r"انتهاء الدعوي صلحا",
        r"انتهاء الدعوي صلح"
    ],
    "شطب الدعوى": [
        r"شطب الدعوي",
        r"شطب القضيه"
    ],
    "حل وتصفية": [
        r"حل الشركه",
        r"تصفية الشركه",
        r"حل وتصفية"
    ],
    "ثبوت حق أو شراكة": [
        r"ثبوت الشراكه",
        r"ثبوت حق",
        r"اثبات الشراكه"
    ]
}

OUTCOME_REGEX = {
    label: [re.compile(p) for p in patterns]
    for label, patterns in OUTCOME_PATTERNS.items()
}

RULING_ANCHORS = [
    "حكمت الدايره",
    "حكمت المحكمه",
    "قضت الدايره",
    "قضت المحكمه",
    "لذلك حكمت",
    "فلهذه الاسباب حكمت",
    "عليه حكمت المحكمه",
    "عليه حكمت الدايره",
    "حكمت الدائره"
]

HISTORICAL_CONTEXT = [
    "سبق ان صدر",
    "صدر حكم سابق",
    "الحكم السابق",
    "الحكم الصادر",
    "حصل علي حكم",
    "بموجب الحكم",
    "بموجب صك الحكم",
    "قضي سابقا",
    "قضت المحكمه سابقا"
]

def extract_ruling_windows(text, max_chars=2200):
    text = norm(text)
    windows = []

    for anchor in RULING_ANCHORS:
        start = 0
        while True:
            pos = text.find(anchor, start)
            if pos < 0:
                break

            before = text[max(0, pos-220):pos]

            if not any(marker in before for marker in HISTORICAL_CONTEXT):
                windows.append({
                    "start": pos,
                    "text": text[pos:pos+max_chars]
                })

            start = pos + len(anchor)

    # Remove nearly identical windows
    unique = []
    seen = set()

    for item in windows:
        signature = item["text"][:350]
        if signature not in seen:
            seen.add(signature)
            unique.append(item)

    return unique

def classify_windows(windows):
    evidence = {}

    for label, patterns in OUTCOME_REGEX.items():
        matches = []

        for window in windows:
            content = window["text"]

            if any(pattern.search(content) for pattern in patterns):
                matches.append(content[:800])

        if matches:
            evidence[label] = matches[:3]

    labels = list(evidence.keys())
    return labels, evidence

def analyze_outcome_source(text):
    windows = extract_ruling_windows(text)
    labels, evidence = classify_windows(windows)

    return {
        "labels": labels,
        "evidence": evidence,
        "anchor_count": len(windows)
    }

# Analyze RULING and full case_text separately
ruling_analysis = []
case_analysis = []

for _, row in df_v3.iterrows():
    ruling_analysis.append(
        analyze_outcome_source(row.get("RULING", ""))
    )
    case_analysis.append(
        analyze_outcome_source(row.get("case_text", ""))
    )

df_v3["outcomes_from_ruling"] = [
    json.dumps(x["labels"], ensure_ascii=False)
    for x in ruling_analysis
]

df_v3["outcomes_from_case_text"] = [
    json.dumps(x["labels"], ensure_ascii=False)
    for x in case_analysis
]

df_v3["ruling_anchor_count_v3"] = [
    x["anchor_count"] for x in ruling_analysis
]

df_v3["case_anchor_count_v3"] = [
    x["anchor_count"] for x in case_analysis
]

def merge_outcomes(a, b):
    # Preserve source-level differences for audit.
    merged = list(dict.fromkeys(a["labels"] + b["labels"]))
    return merged

merged_outcomes = [
    merge_outcomes(a, b)
    for a, b in zip(ruling_analysis, case_analysis)
]

df_v3["outcomes_v3_list"] = [
    json.dumps(x, ensure_ascii=False)
    for x in merged_outcomes
]

df_v3["outcome_v3"] = [
    " | ".join(x) if x else "غير محدد"
    for x in merged_outcomes
]

df_v3["outcome_source_disagreement"] = [
    set(a["labels"]) != set(b["labels"])
    for a, b in zip(ruling_analysis, case_analysis)
]

# ------------------------------------------------------------
# 3) Legal source dictionary
#    Singular old name is kept separate from current plural name.
# ------------------------------------------------------------

LEGAL_ALIASES = {
    "نظام المحاكم التجارية": [
        "نظام المحاكم التجارية"
    ],
    "نظام المحكمة التجارية القديم": [
        "نظام المحكمة التجارية"
    ],
    "اللائحة التنفيذية لنظام المحاكم التجارية": [
        "اللائحة التنفيذية لنظام المحاكم التجارية",
        "لايحة نظام المحاكم التجارية",
        "اللائحة التنفيذية للمحاكم التجارية"
    ],
    "نظام المرافعات الشرعية": [
        "نظام المرافعات الشرعية"
    ],
    "نظام الشركات": [
        "نظام الشركات"
    ],
    "نظام الإثبات": [
        "نظام الاثبات"
    ],
    "نظام الإفلاس": [
        "نظام الافلاس"
    ],
    "نظام التحكيم": [
        "نظام التحكيم"
    ],
    "نظام التنفيذ": [
        "نظام التنفيذ"
    ],
    "نظام المعاملات المدنية": [
        "نظام المعاملات المدنية"
    ],
    "نظام الأوراق التجارية": [
        "نظام الاوراق التجارية"
    ],
    "نظام العلامات التجارية": [
        "نظام العلامات التجارية"
    ],
    "نظام الأسماء التجارية": [
        "نظام الاسماء التجارية"
    ],
    "نظام حماية حقوق المؤلف": [
        "نظام حماية حقوق المؤلف"
    ],
    "نظام براءات الاختراع": [
        "نظام براءات الاختراع والتصميمات التخطيطية للدارات المتكاملة والاصناف النباتية والنماذج الصناعية",
        "نظام براءات الاختراع"
    ],
    "نظام الوكالات التجارية": [
        "نظام الوكالات التجارية"
    ],
    "نظام الامتياز التجاري": [
        "نظام الامتياز التجاري"
    ],
    "نظام العمل": [
        "نظام العمل"
    ],
    "نظام السجل التجاري": [
        "نظام السجل التجاري"
    ],
    "نظام الاستثمار": [
        "نظام الاستثمار"
    ],
    "نظام التعاملات الإلكترونية": [
        "نظام التعاملات الالكترونية"
    ],
    "نظام التجارة الإلكترونية": [
        "نظام التجارة الالكترونية"
    ],
    "نظام مكافحة التستر": [
        "نظام مكافحة التستر"
    ],
    "نظام مكافحة الغش التجاري": [
        "نظام مكافحة الغش التجاري"
    ],
    "نظام المنافسة": [
        "نظام المنافسة"
    ],
    "نظام ضريبة القيمة المضافة": [
        "نظام ضريبة القيمة المضافة"
    ],
    "نظام الملكية الفكرية": [
        "نظام الملكية الفكرية"
    ],
    "مجلة الأحكام العدلية": [
        "مجلة الاحكام العدلية"
    ]
}

# Compile aliases, longest first
ALIAS_LOOKUP = []

for canonical, aliases in LEGAL_ALIASES.items():
    for alias in aliases:
        ALIAS_LOOKUP.append((norm(alias), canonical))

ALIAS_LOOKUP.sort(key=lambda x: len(x[0]), reverse=True)

# ------------------------------------------------------------
# 4) Detect legal source mentions with exact spans
# ------------------------------------------------------------

def find_legal_sources(text):
    text = norm(text)
    found = []

    for alias, canonical in ALIAS_LOOKUP:
        start = 0

        while True:
            pos = text.find(alias, start)
            if pos < 0:
                break

            found.append({
                "canonical": canonical,
                "alias": alias,
                "start": pos,
                "end": pos + len(alias)
            })

            start = pos + len(alias)

    # Remove duplicate/overlapping alias hits
    found.sort(key=lambda x: (x["start"], -(x["end"]-x["start"])))

    clean = []
    for item in found:
        overlaps = any(
            item["start"] < old["end"] and item["end"] > old["start"]
            for old in clean
        )
        if not overlaps:
            clean.append(item)

    return clean

# ------------------------------------------------------------
# 5) Article extraction
#    Supports: المادة 16، المادة (16)، المادة 57/2
# ------------------------------------------------------------

ARTICLE_RE = re.compile(
    r"الماده\s*"
    r"(?:رقم\s*)?"
    r"[\(（]?\s*([0-9]{1,4})\s*[\)）]?"
    r"(?:\s*/\s*([0-9]{1,3}))?"
)

def split_segments(text):
    # Split into sentence-like segments, retaining useful context.
    parts = re.split(r"(?<=[؛;.!؟])\s+|[\n\r]+", text)
    return [p.strip() for p in parts if p.strip()]

def extract_legal_references(text, source_name, judgment_id):
    text = norm(text)
    if not text:
        return [], []

    system_mentions = find_legal_sources(text)
    article_records = []
    system_records = []

    for mention in system_mentions:
        system_records.append({
            "judgment_number": judgment_id,
            "system": mention["canonical"],
            "source": source_name,
            "context": text[max(0, mention["start"]-180):
                            min(len(text), mention["end"]+180)]
        })

    segments = split_segments(text)

    for match in ARTICLE_RE.finditer(text):
        number = match.group(1)
        subsection = match.group(2)

        article = f"المادة {number}"
        if subsection:
            article += f"/{subsection}"

        pos = match.start()

        # Find the segment containing the article.
        segment = next(
            (s for s in segments if s in text[max(0, pos-100):pos+500]),
            ""
        )

        # Use a local context around the article.
        local_start = max(0, pos-240)
        local_end = min(len(text), match.end()+300)
        context = text[local_start:local_end]

        # Only link when the source name is in the same local context.
        nearby = []

        for system in system_mentions:
            distance = min(
                abs(system["start"] - match.start()),
                abs(system["end"] - match.end())
            )

            if distance <= 240:
                nearby.append((distance, system["canonical"]))

        nearby.sort(key=lambda x: x[0])

        linked_system = None
        linking_reason = "لا يوجد اسم نظام قريب بما يكفي"

        if nearby:
            closest_distance = nearby[0][0]
            closest_systems = list(dict.fromkeys(
                system for distance, system in nearby
                if distance == closest_distance
            ))

            if len(closest_systems) == 1:
                linked_system = closest_systems[0]
                linking_reason = "اسم النظام الأقرب في السياق"
            else:
                linking_reason = "أكثر من نظام بالمسافة نفسها"

        # Flag known non-system references separately.
        if "مجلة الاحكام العدلية" in context:
            if linked_system is None:
                linked_system = "مجلة الأحكام العدلية"
                linking_reason = "مرجع صريح لمجلة الأحكام العدلية"

        article_records.append({
            "judgment_number": judgment_id,
            "article": article,
            "system": linked_system,
            "source": source_name,
            "linking_reason": linking_reason,
            "context": context
        })

    return system_records, article_records

# ------------------------------------------------------------
# 6) Extract from separate dataset fields
# ------------------------------------------------------------

all_systems = []
all_articles = []

for _, row in df_v3.iterrows():
    judgment_id = str(row.get("judgment_number", ""))

    for col, source_name in [
        ("REASONING", "أسباب الحكم"),
        ("RULING", "حقل RULING"),
        ("EVENTS", "وقائع القضية"),
        ("case_text", "النص الكامل")
    ]:
        sys_records, article_records = extract_legal_references(
            row.get(col, ""),
            source_name,
            judgment_id
        )

        all_systems.extend(sys_records)
        all_articles.extend(article_records)

systems_v3 = pd.DataFrame(all_systems)
articles_v3 = pd.DataFrame(all_articles)

# ------------------------------------------------------------
# 7) Summaries
# ------------------------------------------------------------

if not systems_v3.empty:
    systems_summary_v3 = (
        systems_v3.groupby("system")
        .agg(
            mentions=("system", "size"),
            judgments=("judgment_number", "nunique")
        )
        .sort_values("judgments", ascending=False)
    )
else:
    systems_summary_v3 = pd.DataFrame()

if not articles_v3.empty:
    articles_summary_v3 = (
        articles_v3.groupby(["article", "system"], dropna=False)
        .agg(
            mentions=("article", "size"),
            judgments=("judgment_number", "nunique")
        )
        .reset_index()
        .sort_values(["judgments", "mentions"], ascending=False)
    )

    linked_count = articles_v3["system"].notna().sum()
    unlinked_count = articles_v3["system"].isna().sum()
else:
    articles_summary_v3 = pd.DataFrame()
    linked_count = 0
    unlinked_count = 0

# ------------------------------------------------------------
# 8) Outcome audit report
# ------------------------------------------------------------

print("=" * 65)
print("ESNAD - PRECISION AUDIT V3")
print("=" * 65)

print("\nOUTCOME DISTRIBUTION")
print(df_v3["outcome_v3"].value_counts().to_string())

identified = (df_v3["outcome_v3"] != "غير محدد").sum()
multiple = sum(len(x) > 1 for x in merged_outcomes)
disagreements = df_v3["outcome_source_disagreement"].sum()

print("\nOUTCOME COVERAGE")
print("Total judgments:", len(df_v3))
print("Identified:", identified)
print("Unidentified:", len(df_v3)-identified)
print("Coverage:", round(identified/len(df_v3)*100, 2), "%")
print("Multiple outcomes:", multiple)
print("RULING vs case_text disagreements:", disagreements)

print("\nSOURCE COMPARISON")
print("RULING identified:",
      sum(bool(x["labels"]) for x in ruling_analysis))
print("case_text identified:",
      sum(bool(x["labels"]) for x in case_analysis))

print("\nDISAGREEMENT SAMPLES")
disagreement_rows = df_v3[
    df_v3["outcome_source_disagreement"]
].head(15)

for _, row in disagreement_rows.iterrows():
    print("\nJudgment:", row.get("judgment_number"))
    print("RULING:", row["outcomes_from_ruling"])
    print("case_text:", row["outcomes_from_case_text"])
    print("Merged:", row["outcomes_v3_list"])

# ------------------------------------------------------------
# 9) Legal reference audit report
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("LEGAL SYSTEMS")
print("=" * 65)

if not systems_summary_v3.empty:
    print(systems_summary_v3.to_string())
else:
    print("No legal systems found.")

print("\n" + "=" * 65)
print("ARTICLE REFERENCES BY SYSTEM")
print("=" * 65)

if not articles_summary_v3.empty:
    print(articles_summary_v3.head(50).to_string(index=False))

print("\nLINKING QUALITY")
print("Article mentions:", len(articles_v3))
print("Linked:", linked_count)
print("Unlinked:", unlinked_count)

if len(articles_v3):
    print("Linking rate:",
          round(linked_count/len(articles_v3)*100, 2), "%")

# ------------------------------------------------------------
# 10) Important known-case checks
# ------------------------------------------------------------

print("\n" + "=" * 65)
print("KNOWN CASE CHECKS")
print("=" * 65)

for case_id in ["9549/3/ق", "285/8/ق", "5128/4/ق"]:
    matches = df_v3[
        df_v3["judgment_number"].astype(str) == case_id
    ]

    if not matches.empty:
        row = matches.iloc[0]
        print("\nJudgment:", case_id)
        print("RULING outcomes:", row["outcomes_from_ruling"])
        print("case_text outcomes:", row["outcomes_from_case_text"])
        print("Merged:", row["outcomes_v3_list"])

if not articles_v3.empty:
    for case_id in ["285/8/ق", "5128/4/ق", "3414"]:
        sample = articles_v3[
            articles_v3["judgment_number"] == case_id
        ]

        if not sample.empty:
            print("\nLegal references for:", case_id)
            print(sample[[
                "article", "system", "source", "linking_reason"
            ]].head(12).to_string(index=False))

# ------------------------------------------------------------
# 11) Export
# ------------------------------------------------------------

df_v3.to_csv(
    "/content/esnad_arabiccr_precision_v3.csv",
    index=False,
    encoding="utf-8-sig"
)

systems_v3.to_csv(
    "/content/esnad_legal_systems_v3.csv",
    index=False,
    encoding="utf-8-sig"
)

articles_v3.to_csv(
    "/content/esnad_legal_articles_v3.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\n" + "=" * 65)
print("FILES SAVED")
print("/content/esnad_arabiccr_precision_v3.csv")
print("/content/esnad_legal_systems_v3.csv")
print("/content/esnad_legal_articles_v3.csv")
print("=" * 65)

=================================================================
ESNAD - PRECISION AUDIT V3
=================================================================

OUTCOME DISTRIBUTION
outcome_v3
إلزام                                                                                                5598
غير محدد                                                                                             4301
رفض الدعوى أو الطلب                                                                                  1373
عدم قبول الدعوى                                                                                       351
عدم الاختصاص                                                                                          248
عدم جواز نظر الدعوى                                                                                   118
إلزام | رفض الدعوى أو الطلب                                                                            94
إلزام | فسخ أو إنهاء                                                                                   78
فسخ أو إنهاء                                                                                           51
إلزام | عدم قبول الدعوى                                                                                51
إلزام | عدم الاختصاص                                                                                   28
رفض الدعوى أو الطلب | إلزام                                                                            21
رفض الدعوى أو الطلب | عدم الاختصاص                                                                     17
رفض الدعوى أو الطلب | عدم قبول الدعوى                                                                  13
ثبوت حق أو شراكة                                                                                       11
رفض الدعوى أو الطلب | فسخ أو إنهاء                                                                      7
صلح                                                                                                     7
إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى                                                           6
رفض الدعوى أو الطلب | إلزام | عدم قبول الدعوى                                                           6
إلزام | رفض الدعوى أو الطلب | فسخ أو إنهاء                                                              5
إلزام | عدم جواز نظر الدعوى                                                                             5
عدم جواز نظر الدعوى | إلزام                                                                             4
إلزام | عدم قبول الدعوى | عدم الاختصاص                                                                  4
إلزام | شطب الدعوى                                                                                      4
رفض الدعوى أو الطلب | ثبوت حق أو شراكة                                                                  4
إلزام | ثبوت حق أو شراكة                                                                                3
رفض الدعوى أو الطلب | عدم جواز نظر الدعوى                                                               3
رفض الدعوى أو الطلب | صلح                                                                               3
إلزام | صلح                                                                                             3
عدم قبول الدعوى | عدم الاختصاص                                                                          3
إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم الاختصاص                                            3
عدم الاختصاص | عدم قبول الدعوى                                                                          3
رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم جواز نظر الدعوى | عدم الاختصاص                              2
عدم قبول الدعوى | فسخ أو إنهاء                                                                          2
عدم الاختصاص | فسخ أو إنهاء                                                                             2
رفض الدعوى أو الطلب | إلزام | عدم الاختصاص                                                              2
إلزام | رفض الدعوى أو الطلب | عدم الاختصاص                                                              2
عدم الاختصاص | إلزام                                                                                    2
إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم جواز نظر الدعوى                                     2
عدم جواز نظر الدعوى | عدم الاختصاص                                                                      2
إلزام | عدم جواز نظر الدعوى | عدم الاختصاص                                                              2
إلزام | رفض الدعوى أو الطلب | ثبوت حق أو شراكة                                                          2
عدم قبول الدعوى | عدم جواز نظر الدعوى                                                                   2
عدم قبول الدعوى | إلزام | رفض الدعوى أو الطلب                                                           2
إلزام | عدم قبول الدعوى | عدم جواز نظر الدعوى | عدم الاختصاص                                            2
عدم قبول الدعوى | إلزام | عدم جواز نظر الدعوى | عدم الاختصاص                                            2
إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم الاختصاص | فسخ أو إنهاء                             1
إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | فسخ أو إنهاء                                            1
عدم قبول الدعوى | ثبوت حق أو شراكة                                                                      1
إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم جواز نظر الدعوى | عدم الاختصاص | فسخ أو إنهاء       1
رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم الاختصاص                                                    1
رفض الدعوى أو الطلب | إلزام | شطب الدعوى                                                                1
إلزام | عدم قبول الدعوى | فسخ أو إنهاء                                                                  1
عدم الاختصاص | إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم جواز نظر الدعوى                      1
إلزام | فسخ أو إنهاء | عدم الاختصاص                                                                     1
رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم جواز نظر الدعوى | فسخ أو إنهاء                              1
عدم قبول الدعوى | عدم جواز نظر الدعوى | عدم الاختصاص                                                    1
إلزام | عدم الاختصاص | ثبوت حق أو شراكة                                                                 1
إلزام | فسخ أو إنهاء | عدم قبول الدعوى                                                                  1
عدم قبول الدعوى | إلزام                                                                                 1
رفض الدعوى أو الطلب | عدم جواز نظر الدعوى | ثبوت حق أو شراكة                                            1
شطب الدعوى | إلزام | رفض الدعوى أو الطلب | عدم قبول الدعوى | عدم جواز نظر الدعوى                        1
عدم قبول الدعوى | إلزام | عدم الاختصاص                                                                  1
رفض الدعوى أو الطلب | عدم جواز نظر الدعوى | شطب الدعوى                                                  1
رفض الدعوى أو الطلب | إلزام | فسخ أو إنهاء                                                              1
إلزام | رفض الدعوى أو الطلب | عدم جواز نظر الدعوى                                                       1
عدم قبول الدعوى | رفض الدعوى أو الطلب                                                                   1
عدم الاختصاص | ثبوت حق أو شراكة                                                                         1
رفض الدعوى أو الطلب | عدم قبول الدعوى | فسخ أو إنهاء                                                    1

OUTCOME COVERAGE
Total judgments: 12477
Identified: 8176
Unidentified: 4301
Coverage: 65.53 %
Multiple outcomes: 419
RULING vs case_text disagreements: 456

SOURCE COMPARISON
RULING identified: 7940
case_text identified: 8121

DISAGREEMENT SAMPLES

Judgment: 4530547483
RULING: []
case_text: ["إلزام"]
Merged: ["إلزام"]

Judgment: 4530461975
RULING: ["رفض الدعوى أو الطلب"]
case_text: ["رفض الدعوى أو الطلب", "عدم قبول الدعوى", "عدم جواز نظر الدعوى", "عدم الاختصاص"]
Merged: ["رفض الدعوى أو الطلب", "عدم قبول الدعوى", "عدم جواز نظر الدعوى", "عدم الاختصاص"]

Judgment: 4530347893
RULING: ["إلزام"]
case_text: []
Merged: ["إلزام"]

Judgment: 4570088841
RULING: ["إلزام", "فسخ أو إنهاء"]
case_text: []
Merged: ["إلزام", "فسخ أو إنهاء"]

Judgment: 4471130640
RULING: []
case_text: ["إلزام", "عدم قبول الدعوى"]
Merged: ["إلزام", "عدم قبول الدعوى"]

Judgment: 4530513777
RULING: ["رفض الدعوى أو الطلب"]
case_text: ["إلزام", "رفض الدعوى أو الطلب"]
Merged: ["رفض الدعوى أو الطلب", "إلزام"]

Judgment: 4530357586
RULING: ["إلزام"]
case_text: []
Merged: ["إلزام"]

Judgment: 4530442993
RULING: []
case_text: ["صلح"]
Merged: ["صلح"]

Judgment: 4530438602
RULING: ["إلزام"]
case_text: ["إلزام", "عدم الاختصاص"]
Merged: ["إلزام", "عدم الاختصاص"]

Judgment: 4530518619
RULING: ["رفض الدعوى أو الطلب"]
case_text: ["إلزام", "رفض الدعوى أو الطلب", "عدم الاختصاص"]
Merged: ["رفض الدعوى أو الطلب", "إلزام", "عدم الاختصاص"]

Judgment: 4530406685
RULING: []
case_text: ["رفض الدعوى أو الطلب"]
Merged: ["رفض الدعوى أو الطلب"]

Judgment: 4530416855
RULING: ["إلزام"]
case_text: []
Merged: ["إلزام"]

Judgment: 4530388733
RULING: []
case_text: ["رفض الدعوى أو الطلب", "صلح"]
Merged: ["رفض الدعوى أو الطلب", "صلح"]

Judgment: 4530382824
RULING: ["إلزام"]
case_text: ["صلح"]
Merged: ["إلزام", "صلح"]

Judgment: 4530381498
RULING: ["رفض الدعوى أو الطلب"]
case_text: ["إلزام", "رفض الدعوى أو الطلب"]
Merged: ["رفض الدعوى أو الطلب", "إلزام"]

=================================================================
LEGAL SYSTEMS
=================================================================
                                          mentions  judgments
system
نظام المرافعات الشرعية                       14740       4010
نظام المحاكم التجارية                        12310       3664
اللائحة التنفيذية لنظام المحاكم التجارية      4432       1667
نظام المحكمة التجارية القديم                  3741       1341
نظام الشركات                                  6571       1111
نظام الإثبات                                  3288        979
نظام الإفلاس                                   944        179
نظام التحكيم                                   498        134
نظام التنفيذ                                   370        125
نظام العلامات التجارية                         422         85
نظام الأسماء التجارية                          286         74
نظام الأوراق التجارية                          188         68
نظام حماية حقوق المؤلف                         286         67
نظام العمل                                     188         59
نظام السجل التجاري                             102         49
مجلة الأحكام العدلية                            88         42
نظام الوكالات التجارية                         112         23
نظام الاستثمار                                  46         16
نظام براءات الاختراع                            58         14
نظام التعاملات الإلكترونية                      26         12
نظام الامتياز التجاري                           84         10
نظام مكافحة التستر                              28          8
نظام مكافحة الغش التجاري                        22          7
نظام المعاملات المدنية                          24          6
نظام ضريبة القيمة المضافة                       10          4
نظام المنافسة                                   34          4
نظام التجارة الإلكترونية                         2          1
نظام الملكية الفكرية                             2          1

=================================================================
ARTICLE REFERENCES BY SYSTEM
=================================================================
    article                                   system  mentions  judgments
  المادة 16                    نظام المحاكم التجارية      2824       1200
  المادة 35                   نظام المرافعات الشرعية      1273        594
  المادة 90 اللائحة التنفيذية لنظام المحاكم التجارية      1085        507
  المادة 57                   نظام المرافعات الشرعية       629        292
  المادة 76                   نظام المرافعات الشرعية       676        288
 المادة 443             نظام المحكمة التجارية القديم       438        209
  المادة 30                    نظام المحاكم التجارية       421        197
 المادة 200                   نظام المرافعات الشرعية       602        187
 المادة 527             نظام المحكمة التجارية القديم       354        175
 المادة 164 اللائحة التنفيذية لنظام المحاكم التجارية       338        159
  المادة 29                             نظام الإثبات       342        155
 المادة 128                   نظام المرافعات الشرعية       328        141
   المادة 1                                      NaN       316        125
  المادة 26                                      NaN       261        118
 المادة 139                   نظام المرافعات الشرعية       226        104
  المادة 16             نظام المحكمة التجارية القديم       212        101
المادة 57/2                   نظام المرافعات الشرعية       205         97
  المادة 31                   نظام المرافعات الشرعية       188         90
  المادة 58                    نظام المحاكم التجارية       186         89
   المادة 3                                      NaN       282         86
  المادة 42                    نظام المحاكم التجارية       176         81
  المادة 19                    نظام المحاكم التجارية       194         79
   المادة 4                                      NaN       223         77
   المادة 6                                      NaN       235         72
  المادة 66                   نظام المرافعات الشرعية       156         70
  المادة 17                    نظام المحاكم التجارية       154         69
  المادة 20                    نظام المحاكم التجارية       162         65
 المادة 133 اللائحة التنفيذية لنظام المحاكم التجارية       136         64
   المادة 2                                      NaN       195         63
  المادة 36                   نظام المرافعات الشرعية       126         58
  المادة 11                                      NaN       174         55
   المادة 5                                      NaN       135         51
  المادة 10                                      NaN       118         50
  المادة 25                    نظام المحاكم التجارية       102         50
   المادة 2             نظام المحكمة التجارية القديم       102         49
المادة 57/1                   نظام المرافعات الشرعية       102         49
   المادة 8                                      NaN       154         48
  المادة 67                   نظام المرافعات الشرعية       104         48
   المادة 7                                      NaN       130         45
  المادة 13                                      NaN       122         44
المادة 30/1                    نظام المحاكم التجارية        98         44
   المادة 9                                      NaN       121         43
  المادة 16                                      NaN       113         43
  المادة 41                   نظام المرافعات الشرعية        98         43
  المادة 58 اللائحة التنفيذية لنظام المحاكم التجارية        96         42
 المادة 179                   نظام المرافعات الشرعية        84         42
  المادة 17                             نظام الإثبات        86         41
  المادة 75                   نظام المرافعات الشرعية       100         40
 المادة 165                             نظام الشركات       118         39
المادة 16/1                    نظام المحاكم التجارية        84         39

LINKING QUALITY
Article mentions: 29156
Linked: 23541
Unlinked: 5615
Linking rate: 80.74 %

=================================================================
KNOWN CASE CHECKS
=================================================================

Judgment: 9549/3/ق
RULING outcomes: ["إلزام", "رفض الدعوى أو الطلب", "فسخ أو إنهاء"]
case_text outcomes: ["إلزام", "رفض الدعوى أو الطلب", "فسخ أو إنهاء"]
Merged: ["إلزام", "رفض الدعوى أو الطلب", "فسخ أو إنهاء"]

Judgment: 285/8/ق
RULING outcomes: ["رفض الدعوى أو الطلب"]
case_text outcomes: ["رفض الدعوى أو الطلب"]
Merged: ["رفض الدعوى أو الطلب"]

Judgment: 5128/4/ق
RULING outcomes: ["إلزام"]
case_text outcomes: ["إلزام"]
Merged: ["إلزام"]

Legal references for: 285/8/ق
   article                       system      source              linking_reason
المادة 443 نظام المحكمة التجارية القديم أسباب الحكم اسم النظام الأقرب في السياق
المادة 443 نظام المحكمة التجارية القديم النص الكامل اسم النظام الأقرب في السياق
المادة 443 نظام المحكمة التجارية القديم أسباب الحكم اسم النظام الأقرب في السياق
المادة 443 نظام المحكمة التجارية القديم النص الكامل اسم النظام الأقرب في السياق

Legal references for: 5128/4/ق
   article                       system      source                 linking_reason
المادة 443 نظام المحكمة التجارية القديم أسباب الحكم    اسم النظام الأقرب في السياق
المادة 527                         None أسباب الحكم لا يوجد اسم نظام قريب بما يكفي
المادة 443 نظام المحكمة التجارية القديم النص الكامل    اسم النظام الأقرب في السياق
المادة 527                         None النص الكامل لا يوجد اسم نظام قريب بما يكفي

Legal references for: 3414
   article                                   system       source              linking_reason
 المادة 35                   نظام المرافعات الشرعية  أسباب الحكم اسم النظام الأقرب في السياق
 المادة 35                   نظام المرافعات الشرعية  النص الكامل اسم النظام الأقرب في السياق
 المادة 16                    نظام المحاكم التجارية  أسباب الحكم اسم النظام الأقرب في السياق
المادة 768                     مجلة الأحكام العدلية  أسباب الحكم اسم النظام الأقرب في السياق
 المادة 26             نظام المحكمة التجارية القديم وقائع القضية اسم النظام الأقرب في السياق
المادة 164 اللائحة التنفيذية لنظام المحاكم التجارية وقائع القضية اسم النظام الأقرب في السياق
 المادة 26             نظام المحكمة التجارية القديم  النص الكامل اسم النظام الأقرب في السياق
المادة 164 اللائحة التنفيذية لنظام المحاكم التجارية  النص الكامل اسم النظام الأقرب في السياق
 المادة 16                    نظام المحاكم التجارية  النص الكامل اسم النظام الأقرب في السياق
المادة 768                     مجلة الأحكام العدلية  النص الكامل اسم النظام الأقرب في السياق

=================================================================
FILES SAVED
/content/esnad_arabiccr_precision_v3.csv
/content/esnad_legal_systems_v3.csv
/content/esnad_legal_articles_v3.csv
=================================================================